#!/usr/bin/env bash
set -euo pipefail

# Rebuild every migration from supabase/sql_src.
# Source files are organized by feature; migrations are generated artifacts.

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
source_root="$repo_root/supabase/sql_src"
migrations_dir="$repo_root/supabase/migrations"

if [ ! -d "$source_root" ]; then
  echo "Missing SQL source root: $source_root" >&2
  exit 1
fi

generated_sources="$(mktemp)"
all_sources="$(mktemp)"
trap 'rm -f "$generated_sources" "$all_sources"' EXIT

emit_migration() {
  local migration_file="$1"
  local feature="$2"
  shift 2

  local output_path="$migrations_dir/$migration_file"

  {
    echo "-- ============================================================================"
    echo "-- Migration: $migration_file"
    echo "-- Source of truth: supabase/sql_src"
    echo "-- Feature: $feature"
    echo "-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh"
    echo "-- ============================================================================"

    local source_path
    for source_path in "$@"; do
      if [ ! -f "$repo_root/$source_path" ]; then
        echo "Missing SQL source: $source_path" >&2
        exit 1
      fi

      echo "$source_path" >>"$generated_sources"
      echo
      echo "-- >>> $source_path"
      echo
      sed -e '${/^$/d;}' "$repo_root/$source_path"
    done
  } >"$output_path"

  echo "Generated supabase/migrations/$migration_file"
}

mkdir -p "$migrations_dir"
find "$migrations_dir" -maxdepth 1 -type f -name "*.sql" -delete

emit_migration \
  "20260714080000_platform.sql" \
  "platform" \
  "supabase/sql_src/schema/_platform/admin.sql"

emit_migration \
  "20260714080100_user_schema.sql" \
  "user schema" \
  "supabase/sql_src/schema/user/auth_command_attempts.sql" \
  "supabase/sql_src/schema/user/users.sql"

emit_migration \
  "20260714080150_storage.sql" \
  "public media storage" \
  "supabase/sql_src/schema/storage/media_bucket.sql"

emit_migration \
  "20260714080200_flight_routing_schema.sql" \
  "flight routing schema" \
  "supabase/sql_src/schema/flight_routing/data_sources.sql" \
  "supabase/sql_src/schema/flight_routing/countries.sql" \
  "supabase/sql_src/schema/flight_routing/cities.sql" \
  "supabase/sql_src/schema/flight_routing/airports.sql" \
  "supabase/sql_src/schema/flight_routing/airlines.sql" \
  "supabase/sql_src/schema/flight_routing/direct_flight_routes.sql" \
  "supabase/sql_src/schema/flight_routing/flight_route_prices.sql"


emit_migration \
  "20260714080300_route_discovery_schema.sql" \
  "route discovery schema" \
  "supabase/sql_src/schema/pseo/shared/publication_versions.sql" \
  "supabase/sql_src/schema/route_discovery/flight_route_options.sql"

emit_migration \
  "20260714080350_ingestion_schema.sql" \
  "base data ingestion schema" \
  "supabase/sql_src/schema/ingestion/raw_import_batches.sql" \
  "supabase/sql_src/schema/ingestion/raw_base_data_records.sql" \
  "supabase/sql_src/schema/ingestion/ourairports_denylist.sql"

emit_migration \
  "20260714080400_pseo_schema.sql" \
  "pSEO schema" \
  "supabase/sql_src/schema/pseo/shared/pseo_pages.sql" \
  "supabase/sql_src/schema/pseo/city/city_pages.sql" \
  "supabase/sql_src/schema/pseo/airport/airport_pages.sql" \
  "supabase/sql_src/schema/pseo/route/route_pages.sql" \
  "supabase/sql_src/schema/pseo/city/city_page_read_models.sql" \
  "supabase/sql_src/schema/pseo/airport/airport_page_read_models.sql" \
  "supabase/sql_src/schema/pseo/route/route_page_read_models.sql"

emit_migration \
  "20260714080450_shared_functions.sql" \
  "shared functions" \
  "supabase/sql_src/functions/_shared/build_rpc_error.sql"

emit_migration \
  "20260714080500_system_functions.sql" \
  "system functions" \
  "supabase/sql_src/functions/system/health_check.sql"

emit_migration \
  "20260714080600_user_functions.sql" \
  "user functions" \
  "supabase/sql_src/functions/user/handle_new_auth_user.sql" \
  "supabase/sql_src/functions/user/rpc_get_user_profile.sql" \
  "supabase/sql_src/functions/user/update_user_profile.sql" \
  "supabase/sql_src/functions/user/consume_auth_command_attempt.sql"

emit_migration \
  "20260714080700_user_triggers.sql" \
  "user triggers" \
  "supabase/sql_src/triggers/user/trg_handle_new_auth_user.sql"

emit_migration \
  "20260714080800_route_discovery_functions.sql" \
  "route discovery functions" \
  "supabase/sql_src/functions/route_discovery/calculate_haversine_distance_km.sql" \
  "supabase/sql_src/functions/route_discovery/calculate_route_schedule_intersection.sql" \
  "supabase/sql_src/functions/route_discovery/calculate_connecting_duration_minutes.sql" \
  "supabase/sql_src/functions/route_discovery/classify_route_connection_type.sql" \
  "supabase/sql_src/functions/route_discovery/refresh_route_search_options.sql" \
  "supabase/sql_src/functions/route_discovery/rpc_search_routes.sql" \
  "supabase/sql_src/functions/route_discovery/rpc_suggest_locations.sql"



emit_migration \
  "20260714080900_pseo_functions.sql" \
  "pSEO functions" \
  "supabase/sql_src/functions/pseo/city/build_city_page_payload.sql" \
  "supabase/sql_src/functions/pseo/airport/build_airport_page_payload.sql" \
  "supabase/sql_src/functions/pseo/shared/rpc_get_flight_affiliate_handoff.sql" \
  "supabase/sql_src/functions/pseo/route/build_route_page_payload.sql" \
  "supabase/sql_src/functions/pseo/shared/rpc_get_sitemap.sql" \
  "supabase/sql_src/functions/pseo/shared/refresh_page_read_models.sql" \
  "supabase/sql_src/functions/pseo/shared/publish_read_model_version.sql" \
  "supabase/sql_src/functions/pseo/shared/rpc_get_page.sql" \
  "supabase/sql_src/operations/sync_provider_pseo_pages.sql"


emit_migration \
  "20260714081000_ingestion_functions.sql" \
  "base data ingestion functions" \
  "supabase/sql_src/functions/ingestion/ingest_direct_flight_routes_batch.sql" \
  "supabase/sql_src/functions/ingestion/rpc_ingest_direct_flight_routes.sql" \
  "supabase/sql_src/functions/ingestion/publish_base_data_batch.sql" \
  "supabase/sql_src/functions/ingestion/rpc_publish_base_data_batch.sql" \
  "supabase/sql_src/functions/ingestion/rpc_get_ourairports_denylist.sql" \
  "supabase/sql_src/operations/configure_ingestion_crons.sql"



find "$source_root" -type f -name "*.sql" \
  | sed "s|$repo_root/||" \
  | sort >"$all_sources"
sort "$generated_sources" -o "$generated_sources"

if ! diff -u "$all_sources" "$generated_sources"; then
  echo "Migration generation must include every SQL source exactly once." >&2
  exit 1
fi

echo "Done: migrations regenerated from supabase/sql_src"
