-- ============================================================================
-- Migration: 20260714080100_user_schema.sql
-- Source of truth: supabase/sql_src
-- Feature: user schema
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/schema/user/auth_command_attempts.sql

-- Table: private.auth_command_attempts
-- Feature: User authentication
-- Purpose: Persist bounded counters for sensitive account-command rate limits.
-- Responsibilities: Store only hashed subjects, actions, fixed windows, and attempt counts.
-- Notes: Raw user IDs and IP addresses are never persisted.

CREATE TABLE private.auth_command_attempts (
  subject_hash       TEXT         NOT NULL,
  action             TEXT         NOT NULL,
  window_started_at  TIMESTAMPTZ  NOT NULL,
  attempt_count      INTEGER      NOT NULL,
  updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT auth_command_attempts_pkey
    PRIMARY KEY (subject_hash, action, window_started_at),

  CONSTRAINT auth_command_attempts_subject_hash_check
    CHECK (subject_hash ~ '^[0-9a-f]{64}$'),

  CONSTRAINT auth_command_attempts_action_check
    CHECK (action IN ('password_changed', 'password_recovered', 'email_changed', 'delete_account')),

  CONSTRAINT auth_command_attempts_count_check
    CHECK (attempt_count > 0)
);

REVOKE ALL ON TABLE private.auth_command_attempts FROM public, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE private.auth_command_attempts TO service_role;

-- >>> supabase/sql_src/schema/user/users.sql

-- Table: public.users
-- Feature: User
-- Purpose: Store the minimal application profile for an authenticated identity.
-- Responsibilities: Enforce profile shape, account state, ownership, and lifecycle linkage.
-- Notes: Email and credentials remain authoritative in auth.users.

CREATE TABLE public.users (
  user_id         UUID         PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  display_name    TEXT         NOT NULL,
  account_status  TEXT         NOT NULL DEFAULT 'active',
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT users_display_name_length_check
    CHECK (char_length(display_name) BETWEEN 2 AND 80),

  CONSTRAINT users_display_name_trimmed_check
    CHECK (display_name = btrim(display_name)),

  CONSTRAINT users_account_status_check
    CHECK (account_status = 'active')
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.users FROM anon, authenticated;
GRANT SELECT ON TABLE public.users TO authenticated, service_role;
GRANT INSERT, UPDATE, DELETE ON TABLE public.users TO service_role;

CREATE POLICY users_self_read
ON public.users
FOR SELECT
TO authenticated
USING (user_id = (SELECT auth.uid()));
