-- ============================================================================
-- Migration: 20260714080400_pseo_schema.sql
-- Source of truth: supabase/sql_src
-- Feature: pSEO schema
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/schema/pseo/city_direct_routes.sql

-- Table: public.city_direct_routes
-- Feature: Interactive pSEO
-- Purpose: Provide a rebuildable, filterable projection of direct routes from a city.
-- Responsibilities: Preserve scalar airport, airline, country, schedule, confidence, and freshness dimensions.

CREATE TABLE public.city_direct_routes (
  id                         UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
  origin_city_id             UUID           NOT NULL REFERENCES public.cities (id),
  origin_airport_id          UUID           NOT NULL REFERENCES public.airports (id),
  destination_city_id        UUID           NOT NULL REFERENCES public.cities (id),
  destination_airport_id     UUID           NOT NULL REFERENCES public.airports (id),
  destination_country_id     UUID           NOT NULL REFERENCES public.countries (id),
  operating_airline_id       UUID           NOT NULL REFERENCES public.airlines (id),
  marketing_airline_id       UUID           NULL REFERENCES public.airlines (id),
  flight_route_id            UUID           NOT NULL REFERENCES public.flight_routes (id),
  service_count              INTEGER        NOT NULL,
  frequency_per_week         NUMERIC(6, 2)  NULL,
  shortest_duration_minutes  INTEGER        NOT NULL,
  longest_duration_minutes   INTEGER        NOT NULL,
  earliest_departure_time    TIME           NOT NULL,
  latest_departure_time      TIME           NOT NULL,
  seasonality                TEXT           NOT NULL,
  seasonal_start             DATE           NULL,
  seasonal_end               DATE           NULL,
  confidence_score           NUMERIC(4, 3)  NOT NULL,
  source_freshness_at        TIMESTAMPTZ    NOT NULL,
  data_version               UUID           NOT NULL,
  generated_at               TIMESTAMPTZ    NOT NULL DEFAULT now(),

  CONSTRAINT city_direct_routes_version_route_key
    UNIQUE (data_version, flight_route_id),

  CONSTRAINT city_direct_routes_direction_check
    CHECK (origin_city_id <> destination_city_id),

  CONSTRAINT city_direct_routes_service_count_check
    CHECK (service_count > 0),

  CONSTRAINT city_direct_routes_duration_check
    CHECK (
      shortest_duration_minutes > 0
      AND longest_duration_minutes >= shortest_duration_minutes
    ),

  CONSTRAINT city_direct_routes_frequency_check
    CHECK (frequency_per_week IS NULL OR frequency_per_week >= 0),

  CONSTRAINT city_direct_routes_seasonality_check
    CHECK (seasonality IN ('year_round', 'seasonal', 'unknown')),

  CONSTRAINT city_direct_routes_seasonal_dates_check
    CHECK ((seasonal_start IS NULL) = (seasonal_end IS NULL)),

  CONSTRAINT city_direct_routes_confidence_check
    CHECK (confidence_score BETWEEN 0 AND 1)
);

CREATE INDEX city_direct_routes_origin_destination_idx
ON public.city_direct_routes USING btree (
  origin_city_id,
  destination_city_id,
  data_version
);

CREATE INDEX city_direct_routes_origin_airport_idx
ON public.city_direct_routes USING btree (
  origin_city_id,
  origin_airport_id,
  data_version
);

CREATE INDEX city_direct_routes_origin_airline_idx
ON public.city_direct_routes USING btree (
  origin_city_id,
  operating_airline_id,
  data_version
);

CREATE INDEX city_direct_routes_origin_country_idx
ON public.city_direct_routes USING btree (
  origin_city_id,
  destination_country_id,
  data_version
);

CREATE INDEX city_direct_routes_origin_duration_idx
ON public.city_direct_routes USING btree (
  origin_city_id,
  shortest_duration_minutes,
  data_version
);

ALTER TABLE public.city_direct_routes ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.city_direct_routes FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.city_direct_routes TO service_role;

-- >>> supabase/sql_src/schema/pseo/city_destination_summaries.sql

-- Table: public.city_destination_summaries
-- Feature: Interactive pSEO
-- Purpose: Provide stable default cards and ranking for city-to-city direct destinations.
-- Responsibilities: Aggregate direct route facts without replacing filterable route-level data.

CREATE TABLE public.city_destination_summaries (
  id                         UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
  origin_city_id             UUID            NOT NULL REFERENCES public.cities (id),
  destination_city_id        UUID            NOT NULL REFERENCES public.cities (id),
  destination_country_id     UUID            NOT NULL REFERENCES public.countries (id),
  origin_airport_count       INTEGER         NOT NULL,
  destination_airport_count  INTEGER         NOT NULL,
  airline_count              INTEGER         NOT NULL,
  direct_route_count         INTEGER         NOT NULL,
  frequency_per_week         NUMERIC(8, 2)   NULL,
  shortest_duration_minutes  INTEGER         NOT NULL,
  longest_duration_minutes   INTEGER         NOT NULL,
  distance_km                INTEGER         NULL,
  seasonality                TEXT            NOT NULL,
  confidence_score           NUMERIC(4, 3)   NOT NULL,
  ranking_score              NUMERIC(14, 4)  NOT NULL,
  source_freshness_at        TIMESTAMPTZ     NOT NULL,
  data_version               UUID            NOT NULL,
  generated_at               TIMESTAMPTZ     NOT NULL DEFAULT now(),

  CONSTRAINT city_destination_summaries_version_key
    UNIQUE (origin_city_id, destination_city_id, data_version),

  CONSTRAINT city_destination_summaries_direction_check
    CHECK (origin_city_id <> destination_city_id),

  CONSTRAINT city_destination_summaries_counts_check
    CHECK (
      origin_airport_count > 0
      AND destination_airport_count > 0
      AND airline_count > 0
      AND direct_route_count > 0
    ),

  CONSTRAINT city_destination_summaries_duration_check
    CHECK (
      shortest_duration_minutes > 0
      AND longest_duration_minutes >= shortest_duration_minutes
    ),

  CONSTRAINT city_destination_summaries_frequency_check
    CHECK (frequency_per_week IS NULL OR frequency_per_week >= 0),

  CONSTRAINT city_destination_summaries_distance_check
    CHECK (distance_km IS NULL OR distance_km > 0),

  CONSTRAINT city_destination_summaries_seasonality_check
    CHECK (seasonality IN ('year_round', 'seasonal', 'mixed', 'unknown')),

  CONSTRAINT city_destination_summaries_confidence_check
    CHECK (confidence_score BETWEEN 0 AND 1)
);

CREATE INDEX city_destination_summaries_origin_rank_idx
ON public.city_destination_summaries USING btree (
  origin_city_id,
  data_version,
  ranking_score DESC,
  destination_city_id
);

CREATE INDEX city_destination_summaries_origin_country_idx
ON public.city_destination_summaries USING btree (
  origin_city_id,
  destination_country_id,
  data_version
);

ALTER TABLE public.city_destination_summaries ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.city_destination_summaries FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.city_destination_summaries TO service_role;

-- >>> supabase/sql_src/schema/pseo/pseo_pages.sql

-- Table: public.pseo_pages
-- Feature: Interactive pSEO
-- Purpose: Register canonical URLs, publication state, and sitemap eligibility.
-- Responsibilities: Provide stable page identity and database-owned indexability metadata.

CREATE TABLE public.pseo_pages (
  id                   UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  page_type            TEXT         NOT NULL,
  entity_key           TEXT         NOT NULL,
  locale               TEXT         NOT NULL,
  canonical_path       TEXT         NOT NULL,
  display_title        TEXT         NOT NULL,
  status               TEXT         NOT NULL DEFAULT 'draft',
  is_indexable         BOOLEAN      NOT NULL DEFAULT FALSE,
  noindex_reason       TEXT         NULL,
  data_version         UUID         NULL,
  content_updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  source_freshness_at  TIMESTAMPTZ  NULL,
  generated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT pseo_pages_entity_locale_key
    UNIQUE (page_type, entity_key, locale),

  CONSTRAINT pseo_pages_canonical_locale_key
    UNIQUE (canonical_path, locale),

  CONSTRAINT pseo_pages_type_check
    CHECK (
      page_type IN (
        'city',
        'airport',
        'city_route',
        'airline_city',
        'country_route',
        'guide'
      )
    ),

  CONSTRAINT pseo_pages_entity_key_check
    CHECK (entity_key ~ '^[a-z0-9]+(?:[-:][a-z0-9]+)*$'),

  CONSTRAINT pseo_pages_locale_check
    CHECK (locale ~ '^[a-z]{2}(?:-[A-Z]{2})?$'),

  CONSTRAINT pseo_pages_canonical_path_check
    CHECK (canonical_path ~ '^/[a-z0-9]+(?:[-/][a-z0-9]+)*$'),

  CONSTRAINT pseo_pages_title_check
    CHECK (
      display_title = btrim(display_title)
      AND char_length(display_title) BETWEEN 1 AND 160
    ),

  CONSTRAINT pseo_pages_status_check
    CHECK (status IN ('draft', 'review', 'published', 'archived')),

  CONSTRAINT pseo_pages_indexability_check
    CHECK (
      (is_indexable = TRUE AND status = 'published' AND noindex_reason IS NULL)
      OR
      (is_indexable = FALSE AND noindex_reason IS NOT NULL)
    )
);

CREATE INDEX pseo_pages_sitemap_idx
ON public.pseo_pages USING btree (
  locale,
  page_type,
  canonical_path
)
WHERE is_indexable = TRUE AND status = 'published';

ALTER TABLE public.pseo_pages ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.pseo_pages FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.pseo_pages TO service_role;

-- >>> supabase/sql_src/schema/pseo/city_pages.sql

-- Table: public.city_pages
-- Feature: Interactive pSEO
-- Purpose: Store reviewed city-page content, metadata, facts, and publication state.
-- Responsibilities: Separate SEO lifecycle from normalized geographic identity.

CREATE TABLE public.city_pages (
  id                        UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  pseo_page_id              UUID         NOT NULL UNIQUE REFERENCES public.pseo_pages (id),
  city_id                   UUID         NOT NULL REFERENCES public.cities (id),
  locale                    TEXT         NOT NULL,
  canonical_slug            TEXT         NOT NULL,
  h1                        TEXT         NOT NULL,
  subheadline               TEXT         NOT NULL,
  seo_title                 TEXT         NOT NULL,
  meta_description          TEXT         NOT NULL,
  og_title                  TEXT         NOT NULL,
  og_description            TEXT         NOT NULL,
  og_image_path             TEXT         NULL,
  intro                     TEXT         NOT NULL,
  airport_summary           TEXT         NULL,
  status                    TEXT         NOT NULL DEFAULT 'draft',
  is_indexable              BOOLEAN      NOT NULL DEFAULT FALSE,
  noindex_reason            TEXT         NULL,
  primary_airport_id        UUID         NULL REFERENCES public.airports (id),
  airport_count             INTEGER      NOT NULL DEFAULT 0,
  direct_destination_count  INTEGER      NOT NULL DEFAULT 0,
  direct_country_count      INTEGER      NOT NULL DEFAULT 0,
  airline_count             INTEGER      NOT NULL DEFAULT 0,
  shortest_route_minutes    INTEGER      NULL,
  longest_route_minutes     INTEGER      NULL,
  content_reviewed_at       TIMESTAMPTZ  NULL,
  source_freshness_at       TIMESTAMPTZ  NULL,
  data_version              UUID         NULL,
  generated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
  published_at              TIMESTAMPTZ  NULL,
  created_at                TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT city_pages_city_locale_key
    UNIQUE (city_id, locale),

  CONSTRAINT city_pages_slug_locale_key
    UNIQUE (canonical_slug, locale),

  CONSTRAINT city_pages_locale_check
    CHECK (locale ~ '^[a-z]{2}(?:-[A-Z]{2})?$'),

  CONSTRAINT city_pages_slug_check
    CHECK (canonical_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),

  CONSTRAINT city_pages_content_check
    CHECK (
      h1 = btrim(h1)
      AND subheadline = btrim(subheadline)
      AND seo_title = btrim(seo_title)
      AND meta_description = btrim(meta_description)
      AND og_title = btrim(og_title)
      AND og_description = btrim(og_description)
      AND intro = btrim(intro)
    ),

  CONSTRAINT city_pages_status_check
    CHECK (status IN ('draft', 'review', 'published', 'archived')),

  CONSTRAINT city_pages_indexability_check
    CHECK (
      (is_indexable = TRUE AND status = 'published' AND noindex_reason IS NULL)
      OR
      (is_indexable = FALSE AND noindex_reason IS NOT NULL)
    ),

  CONSTRAINT city_pages_counts_check
    CHECK (
      airport_count >= 0
      AND direct_destination_count >= 0
      AND direct_country_count >= 0
      AND airline_count >= 0
    ),

  CONSTRAINT city_pages_duration_check
    CHECK (
      (shortest_route_minutes IS NULL) = (longest_route_minutes IS NULL)
      AND (
        shortest_route_minutes IS NULL
        OR (
          shortest_route_minutes > 0
          AND longest_route_minutes >= shortest_route_minutes
        )
      )
    )
);

CREATE INDEX city_pages_status_idx
ON public.city_pages USING btree (status, is_indexable, locale);

ALTER TABLE public.city_pages ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.city_pages FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.city_pages TO service_role;

-- >>> supabase/sql_src/schema/pseo/city_page_airport_content.sql

-- Table: public.city_page_airport_content
-- Feature: Interactive pSEO
-- Purpose: Store reviewed airport-hub copy and ordering for one localized city page.
-- Responsibilities: Keep locale-specific editorial content outside normalized airport facts.

CREATE TABLE public.city_page_airport_content (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  city_page_id   UUID         NOT NULL REFERENCES public.city_pages (id) ON DELETE CASCADE,
  airport_id     UUID         NOT NULL REFERENCES public.airports (id),
  hub_label      TEXT         NOT NULL,
  description    TEXT         NOT NULL,
  display_order  SMALLINT     NOT NULL,
  status         TEXT         NOT NULL DEFAULT 'draft',
  reviewed_at    TIMESTAMPTZ  NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT city_page_airport_content_page_airport_key
    UNIQUE (city_page_id, airport_id),

  CONSTRAINT city_page_airport_content_page_order_key
    UNIQUE (city_page_id, display_order),

  CONSTRAINT city_page_airport_content_hub_label_check
    CHECK (
      hub_label = btrim(hub_label)
      AND char_length(hub_label) BETWEEN 2 AND 40
    ),

  CONSTRAINT city_page_airport_content_description_check
    CHECK (
      description = btrim(description)
      AND char_length(description) BETWEEN 20 AND 1000
    ),

  CONSTRAINT city_page_airport_content_order_check
    CHECK (display_order > 0),

  CONSTRAINT city_page_airport_content_status_check
    CHECK (status IN ('draft', 'review', 'published'))
);

CREATE INDEX city_page_airport_content_page_status_order_idx
ON public.city_page_airport_content USING btree (
  city_page_id,
  status,
  display_order
);

ALTER TABLE public.city_page_airport_content ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.city_page_airport_content FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.city_page_airport_content TO service_role;

-- >>> supabase/sql_src/schema/pseo/city_page_faqs.sql

-- Table: public.city_page_faqs
-- Feature: Interactive pSEO
-- Purpose: Store ordered, reviewed FAQ content for city pages.
-- Responsibilities: Distinguish editorial, data-backed, and hybrid answers.

CREATE TABLE public.city_page_faqs (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  city_page_id   UUID         NOT NULL REFERENCES public.city_pages (id) ON DELETE CASCADE,
  question       TEXT         NOT NULL,
  answer         TEXT         NOT NULL,
  answer_type    TEXT         NOT NULL,
  display_order  SMALLINT     NOT NULL,
  status         TEXT         NOT NULL DEFAULT 'draft',
  reviewed_at    TIMESTAMPTZ  NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT city_page_faqs_page_order_key
    UNIQUE (city_page_id, display_order),

  CONSTRAINT city_page_faqs_page_question_key
    UNIQUE (city_page_id, question),

  CONSTRAINT city_page_faqs_question_check
    CHECK (
      question = btrim(question)
      AND char_length(question) BETWEEN 5 AND 240
    ),

  CONSTRAINT city_page_faqs_answer_check
    CHECK (
      answer = btrim(answer)
      AND char_length(answer) BETWEEN 10 AND 2000
    ),

  CONSTRAINT city_page_faqs_answer_type_check
    CHECK (answer_type IN ('editorial', 'data_backed', 'hybrid')),

  CONSTRAINT city_page_faqs_order_check
    CHECK (display_order > 0),

  CONSTRAINT city_page_faqs_status_check
    CHECK (status IN ('draft', 'review', 'published'))
);

CREATE INDEX city_page_faqs_page_status_order_idx
ON public.city_page_faqs USING btree (
  city_page_id,
  status,
  display_order
);

ALTER TABLE public.city_page_faqs ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.city_page_faqs FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.city_page_faqs TO service_role;

-- >>> supabase/sql_src/schema/pseo/pseo_internal_links.sql

-- Table: public.pseo_internal_links
-- Feature: Interactive pSEO
-- Purpose: Store a precomputed semantic internal-link graph.
-- Responsibilities: Keep anchor, placement, relevance, and data-version decisions deterministic.

CREATE TABLE public.pseo_internal_links (
  id                UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
  source_page_id    UUID            NOT NULL REFERENCES public.pseo_pages (id) ON DELETE CASCADE,
  target_page_id    UUID            NOT NULL REFERENCES public.pseo_pages (id) ON DELETE CASCADE,
  link_cluster      TEXT            NOT NULL,
  anchor_text       TEXT            NOT NULL,
  secondary_text    TEXT            NULL,
  display_zone      TEXT            NOT NULL,
  relevance_score   NUMERIC(8, 4)   NOT NULL,
  display_order     SMALLINT        NOT NULL,
  is_featured       BOOLEAN         NOT NULL DEFAULT FALSE,
  data_version      UUID            NULL,
  generated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),

  CONSTRAINT pseo_internal_links_target_key
    UNIQUE (source_page_id, target_page_id, link_cluster),

  CONSTRAINT pseo_internal_links_direction_check
    CHECK (source_page_id <> target_page_id),

  CONSTRAINT pseo_internal_links_cluster_check
    CHECK (
      link_cluster IN (
        'popular_routes',
        'airports',
        'airlines',
        'direct_countries',
        'change_source_city',
        'reverse_routes',
        'guides'
      )
    ),

  CONSTRAINT pseo_internal_links_anchor_check
    CHECK (
      anchor_text = btrim(anchor_text)
      AND char_length(anchor_text) BETWEEN 1 AND 180
    ),

  CONSTRAINT pseo_internal_links_zone_check
    CHECK (display_zone ~ '^[a-z0-9]+(?:_[a-z0-9]+)*$'),

  CONSTRAINT pseo_internal_links_score_check
    CHECK (relevance_score >= 0),

  CONSTRAINT pseo_internal_links_order_check
    CHECK (display_order > 0)
);

CREATE INDEX pseo_internal_links_source_cluster_order_idx
ON public.pseo_internal_links USING btree (
  source_page_id,
  link_cluster,
  display_order,
  relevance_score DESC
);

ALTER TABLE public.pseo_internal_links ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.pseo_internal_links FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.pseo_internal_links TO service_role;
