-- ============================================================================
-- Migration: 20260714080200_flight_routing_schema.sql
-- Source of truth: supabase/sql_src
-- Feature: flight routing schema
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/schema/flight_routing/data_sources.sql

-- Table: admin.data_sources
-- Feature: Flight Routing
-- Purpose: Record data provenance and permitted usage before domain data is published.
-- Responsibilities: Identify sources, separate environments, and preserve license capabilities.

CREATE TABLE admin.data_sources (
  id                    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  code                  TEXT         NOT NULL UNIQUE,
  provider_code         TEXT         NOT NULL DEFAULT 'internal',
  name                  TEXT         NOT NULL,
  source_type           TEXT         NOT NULL,
  environment_scope     TEXT         NOT NULL,
  production_allowed    BOOLEAN      NOT NULL DEFAULT FALSE,
  seo_allowed           BOOLEAN      NOT NULL DEFAULT FALSE,
  derived_data_allowed  BOOLEAN      NOT NULL DEFAULT FALSE,
  storage_allowed       BOOLEAN      NOT NULL DEFAULT FALSE,
  retention_days        INTEGER      NULL,
  production_display_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  cache_allowed         BOOLEAN      NOT NULL DEFAULT FALSE,
  max_cache_ttl_seconds INTEGER      NULL,
  attribution_text      TEXT         NULL,
  attribution_url       TEXT         NULL,
  rights_effective_at   TIMESTAMPTZ  NULL,
  rights_expires_at     TIMESTAMPTZ  NULL,
  license_notes         TEXT         NULL,
  created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT data_sources_code_check
    CHECK (code ~ '^[a-z0-9]+(?:[_-][a-z0-9]+)*$'),

  CONSTRAINT data_sources_provider_code_key
    UNIQUE (provider_code, code),

  CONSTRAINT data_sources_provider_code_check
    CHECK (provider_code ~ '^[a-z0-9]+(?:[_-][a-z0-9]+)*$'),

  CONSTRAINT data_sources_name_trimmed_check
    CHECK (name = btrim(name) AND char_length(name) BETWEEN 1 AND 120),

  CONSTRAINT data_sources_type_check
    CHECK (source_type IN ('base_data', 'content_observation', 'schedule', 'development_fixture')),

  CONSTRAINT data_sources_environment_check
    CHECK (environment_scope IN ('development', 'production')),

  CONSTRAINT data_sources_retention_check
    CHECK (
      (storage_allowed = FALSE AND retention_days IS NULL)
      OR (storage_allowed = TRUE AND retention_days > 0)
    ),

  CONSTRAINT data_sources_cache_check
    CHECK (
      (cache_allowed = FALSE AND max_cache_ttl_seconds IS NULL)
      OR (cache_allowed = TRUE AND max_cache_ttl_seconds > 0)
    ),

  CONSTRAINT data_sources_attribution_check
    CHECK (
      (attribution_text IS NULL) = (attribution_url IS NULL)
      AND (
        attribution_url IS NULL
        OR attribution_url ~ '^https://'
      )
    ),

  CONSTRAINT data_sources_rights_window_check
    CHECK (
      (rights_effective_at IS NULL) = (rights_expires_at IS NULL)
      AND (
        rights_effective_at IS NULL
        OR rights_effective_at < rights_expires_at
      )
    ),

  CONSTRAINT data_sources_development_rights_check
    CHECK (
      environment_scope = 'production'
      OR (
        production_allowed = FALSE
        AND production_display_allowed = FALSE
        AND seo_allowed = FALSE
      )
    )
);

REVOKE ALL ON TABLE admin.data_sources FROM public, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE admin.data_sources TO service_role;

-- >>> supabase/sql_src/schema/flight_routing/countries.sql

-- Table: public.countries
-- Feature: Flight Routing
-- Purpose: Provide normalized country identity for cities, airports, and airlines.
-- Responsibilities: Enforce ISO codes, stable slugs, and source lineage.

CREATE TABLE public.countries (
  id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  iso2        TEXT         NOT NULL UNIQUE,
  iso3        TEXT         NOT NULL UNIQUE,
  name        TEXT         NOT NULL,
  slug        TEXT         NOT NULL UNIQUE,
  region      TEXT         NULL,
  subregion   TEXT         NULL,
  source_id   UUID         NOT NULL REFERENCES admin.data_sources (id),
  source_record_id TEXT    NOT NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT countries_source_record_key
    UNIQUE (source_id, source_record_id),

  CONSTRAINT countries_iso2_check
    CHECK (iso2 ~ '^[A-Z]{2}$'),

  CONSTRAINT countries_iso3_check
    CHECK (iso3 ~ '^[A-Z]{3}$'),

  CONSTRAINT countries_name_trimmed_check
    CHECK (name = btrim(name) AND char_length(name) BETWEEN 1 AND 120),

  CONSTRAINT countries_slug_check
    CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

ALTER TABLE public.countries ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.countries FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.countries TO service_role;

-- >>> supabase/sql_src/schema/flight_routing/cities.sql

-- Table: public.cities
-- Feature: Flight Routing
-- Purpose: Group airports by a normalized city identity.
-- Responsibilities: Link cities to countries and preserve optional geographic metadata.

CREATE TABLE public.cities (
  id          UUID              PRIMARY KEY DEFAULT gen_random_uuid(),
  country_id  UUID              NOT NULL REFERENCES public.countries (id),
  name        TEXT              NOT NULL,
  slug        TEXT              NOT NULL,
  iata_code   TEXT              NULL UNIQUE,
  currency_code TEXT            NULL,
  primary_language TEXT         NULL,
  latitude    DOUBLE PRECISION  NULL,
  longitude   DOUBLE PRECISION  NULL,
  timezone    TEXT              NULL,
  source_id   UUID              NOT NULL REFERENCES admin.data_sources (id),
  source_record_id TEXT         NOT NULL,
  created_at  TIMESTAMPTZ       NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ       NOT NULL DEFAULT now(),

  CONSTRAINT cities_source_record_key
    UNIQUE (source_id, source_record_id),

  CONSTRAINT cities_country_slug_key
    UNIQUE (country_id, slug),

  CONSTRAINT cities_name_trimmed_check
    CHECK (name = btrim(name) AND char_length(name) BETWEEN 1 AND 120),

  CONSTRAINT cities_slug_check
    CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),

  CONSTRAINT cities_iata_code_check
    CHECK (iata_code IS NULL OR iata_code ~ '^[A-Z]{3}$'),

  CONSTRAINT cities_currency_code_check
    CHECK (currency_code IS NULL OR currency_code ~ '^[A-Z]{3}$'),

  CONSTRAINT cities_primary_language_check
    CHECK (primary_language IS NULL OR primary_language ~ '^[a-z]{2,3}(?:-[A-Z]{2})?$'),

  CONSTRAINT cities_latitude_check
    CHECK (latitude BETWEEN -90 AND 90),

  CONSTRAINT cities_longitude_check
    CHECK (longitude BETWEEN -180 AND 180),

  CONSTRAINT cities_coordinates_pair_check
    CHECK ((latitude IS NULL) = (longitude IS NULL))
);

CREATE INDEX cities_country_id_idx
ON public.cities USING btree (country_id);

ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.cities FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.cities TO service_role;

-- >>> supabase/sql_src/schema/flight_routing/airports.sql

-- Table: public.airports
-- Feature: Flight Routing
-- Purpose: Represent the airport nodes used by direct and one-stop route search.
-- Responsibilities: Enforce codes, location, operational state, and source lineage.

CREATE TABLE public.airports (
  id                UUID              PRIMARY KEY DEFAULT gen_random_uuid(),
  iata              TEXT              NULL,
  icao              TEXT              NULL,
  name              TEXT              NOT NULL,
  slug              TEXT              NOT NULL UNIQUE,
  image_path        TEXT              NULL,
  city_id           UUID              NULL REFERENCES public.cities (id),
  country_id        UUID              NOT NULL REFERENCES public.countries (id),
  latitude          DOUBLE PRECISION  NULL,
  longitude         DOUBLE PRECISION  NULL,
  timezone          TEXT              NULL,
  airport_type      TEXT              NOT NULL,
  status            TEXT              NOT NULL DEFAULT 'unknown',
  source_id         UUID              NOT NULL REFERENCES admin.data_sources (id),
  source_record_id  TEXT              NOT NULL,
  last_verified_at  TIMESTAMPTZ       NULL,
  created_at        TIMESTAMPTZ       NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ       NOT NULL DEFAULT now(),

  CONSTRAINT airports_source_record_key
    UNIQUE (source_id, source_record_id),

  CONSTRAINT airports_iata_check
    CHECK (iata IS NULL OR iata ~ '^[A-Z]{3}$'),

  CONSTRAINT airports_icao_check
    CHECK (icao IS NULL OR icao ~ '^[A-Z0-9]{4}$'),

  CONSTRAINT airports_name_trimmed_check
    CHECK (name = btrim(name) AND char_length(name) BETWEEN 1 AND 160),

  CONSTRAINT airports_slug_check
    CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),

  CONSTRAINT airports_image_path_check
    CHECK (
      image_path IS NULL
      OR (
        image_path = btrim(image_path)
        AND char_length(image_path) BETWEEN 1 AND 512
        AND image_path LIKE 'airports/%'
        AND image_path !~* '^[a-z][a-z0-9+.-]*://'
        AND image_path !~ '(^|/)\.\.?(/|$)'
        AND image_path !~ '[?#\\]'
      )
    ),

  CONSTRAINT airports_latitude_check
    CHECK (latitude BETWEEN -90 AND 90),

  CONSTRAINT airports_longitude_check
    CHECK (longitude BETWEEN -180 AND 180),

  CONSTRAINT airports_coordinates_pair_check
    CHECK ((latitude IS NULL) = (longitude IS NULL)),

  CONSTRAINT airports_type_check
    CHECK (
      airport_type IN (
        'large_airport',
        'medium_airport',
        'small_airport',
        'heliport',
        'seaplane_base',
        'balloonport',
        'closed'
      )
    ),

  CONSTRAINT airports_status_check
    CHECK (status IN ('active', 'inactive', 'unknown'))
);

CREATE UNIQUE INDEX airports_iata_key
ON public.airports USING btree (iata)
WHERE iata IS NOT NULL;

CREATE UNIQUE INDEX airports_icao_key
ON public.airports USING btree (icao)
WHERE icao IS NOT NULL;

CREATE INDEX airports_city_id_idx
ON public.airports USING btree (city_id);

CREATE INDEX airports_country_id_idx
ON public.airports USING btree (country_id);

ALTER TABLE public.airports ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.airports FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.airports TO service_role;

-- >>> supabase/sql_src/schema/flight_routing/airlines.sql

-- Table: public.airlines
-- Feature: Flight Routing
-- Purpose: Represent airline operators associated with flight routes.
-- Responsibilities: Enforce operator codes, operational state, and source lineage.

CREATE TABLE public.airlines (
  id                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  iata              TEXT         NULL,
  icao              TEXT         NULL,
  name              TEXT         NOT NULL,
  slug              TEXT         NOT NULL UNIQUE,
  logo_path         TEXT         NULL,
  country_id        UUID         NULL REFERENCES public.countries (id),
  alliance          TEXT         NULL,
  business_model    TEXT         NOT NULL DEFAULT 'unknown',
  status            TEXT         NOT NULL DEFAULT 'unknown',
  source_id         UUID         NOT NULL REFERENCES admin.data_sources (id),
  source_record_id  TEXT         NOT NULL,
  last_verified_at  TIMESTAMPTZ  NULL,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT airlines_source_record_key
    UNIQUE (source_id, source_record_id),

  CONSTRAINT airlines_iata_check
    CHECK (iata IS NULL OR iata ~ '^[A-Z0-9]{2}$'),

  CONSTRAINT airlines_icao_check
    CHECK (icao IS NULL OR icao ~ '^[A-Z0-9]{3}$'),

  CONSTRAINT airlines_code_presence_check
    CHECK (iata IS NOT NULL OR icao IS NOT NULL),

  CONSTRAINT airlines_name_trimmed_check
    CHECK (name = btrim(name) AND char_length(name) BETWEEN 1 AND 160),

  CONSTRAINT airlines_slug_check
    CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),

  CONSTRAINT airlines_logo_path_check
    CHECK (
      logo_path IS NULL
      OR (
        logo_path = btrim(logo_path)
        AND char_length(logo_path) BETWEEN 1 AND 512
        AND logo_path LIKE 'airlines/%'
        AND logo_path !~* '^[a-z][a-z0-9+.-]*://'
        AND logo_path !~ '(^|/)\.\.?(/|$)'
        AND logo_path !~ '[?#\\]'
      )
    ),

  CONSTRAINT airlines_alliance_trimmed_check
    CHECK (
      alliance IS NULL
      OR (
        alliance = btrim(alliance)
        AND char_length(alliance) BETWEEN 1 AND 80
      )
    ),

  CONSTRAINT airlines_business_model_check
    CHECK (
      business_model IN (
        'full_service',
        'low_cost',
        'regional',
        'charter',
        'cargo',
        'hybrid',
        'unknown'
      )
    ),

  CONSTRAINT airlines_status_check
    CHECK (status IN ('active', 'inactive', 'unknown'))
);

CREATE UNIQUE INDEX airlines_iata_key
ON public.airlines USING btree (iata)
WHERE iata IS NOT NULL;

CREATE UNIQUE INDEX airlines_icao_key
ON public.airlines USING btree (icao)
WHERE icao IS NOT NULL;

CREATE INDEX airlines_country_id_idx
ON public.airlines USING btree (country_id);

ALTER TABLE public.airlines ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.airlines FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.airlines TO service_role;

-- >>> supabase/sql_src/schema/flight_routing/flight_route_prices.sql

-- Table: public.flight_route_prices
-- Feature: Flight Route Prices
-- Purpose: Store short-lived provider prices for pSEO display; never a live offer inventory.

CREATE TABLE public.flight_route_prices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  public_reference TEXT NOT NULL DEFAULT ('obs_' || replace(gen_random_uuid()::TEXT, '-', '')),
  origin_city_id UUID NOT NULL REFERENCES public.cities (id),
  destination_city_id UUID NOT NULL REFERENCES public.cities (id),
  origin_airport_id UUID NULL REFERENCES public.airports (id),
  destination_airport_id UUID NULL REFERENCES public.airports (id),
  canonical_airline_id UUID NULL REFERENCES public.airlines (id),
  provider_airline_iata TEXT NULL,
  observation_type TEXT NOT NULL,
  trip_type TEXT NOT NULL,
  direct BOOLEAN NULL,
  transfer_count INTEGER NULL,
  observed_amount NUMERIC(14,2) NULL,
  currency_code TEXT NULL,
  market_code TEXT NOT NULL,
  locale TEXT NOT NULL,
  departure_date DATE NULL,
  return_date DATE NULL,
  duration_minutes INTEGER NULL,
  source_id UUID NOT NULL REFERENCES admin.data_sources (id),
  data_source TEXT NOT NULL,
  provider_code TEXT NOT NULL,
  source_record_id TEXT NOT NULL,
  observed_at TIMESTAMPTZ NOT NULL,
  provider_expires_at TIMESTAMPTZ NULL,
  valid_until TIMESTAMPTZ NOT NULL,
  affiliate_path TEXT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  data_version UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT flight_route_prices_source_record_key UNIQUE (source_id, source_record_id),
  CONSTRAINT flight_route_prices_public_reference_key UNIQUE (public_reference),
  CONSTRAINT flight_route_prices_public_reference_check CHECK (public_reference ~ '^obs_[0-9a-f]{32}$'),
  CONSTRAINT flight_route_prices_direction_check CHECK (origin_city_id <> destination_city_id),
  CONSTRAINT flight_route_prices_type_check
    CHECK (observation_type IN ('popular_direction', 'cached_fare', 'special_offer', 'price_calendar')),
  CONSTRAINT flight_route_prices_trip_check CHECK (trip_type IN ('one_way', 'return')),
  CONSTRAINT flight_route_prices_transfer_check CHECK (transfer_count IS NULL OR transfer_count >= 0),
  CONSTRAINT flight_route_prices_direct_check CHECK (direct IS NULL OR transfer_count IS NULL OR direct = (transfer_count = 0)),
  CONSTRAINT flight_route_prices_amount_check
    CHECK (
      (observed_amount IS NULL AND currency_code IS NULL)
      OR (observed_amount >= 0 AND currency_code ~ '^[A-Z]{3}$')
    ),
  CONSTRAINT flight_route_prices_airline_check CHECK (provider_airline_iata IS NULL OR provider_airline_iata ~ '^[A-Z0-9]{2,3}$'),
  CONSTRAINT flight_route_prices_market_check CHECK (market_code ~ '^[a-z]{2}$'),
  CONSTRAINT flight_route_prices_data_source_check CHECK (data_source ~ '^[a-z0-9]+(?:[_-][a-z0-9]+)*$'),
  CONSTRAINT flight_route_prices_provider_check CHECK (provider_code ~ '^[a-z0-9]+(?:[_-][a-z0-9]+)*$'),
  CONSTRAINT flight_route_prices_source_consistency_check CHECK (data_source = provider_code),
  CONSTRAINT flight_route_prices_locale_check CHECK (locale ~ '^[a-z]{2}(?:-[A-Z]{2})?$'),
  CONSTRAINT flight_route_prices_dates_check CHECK (return_date IS NULL OR departure_date IS NULL OR return_date >= departure_date),
  CONSTRAINT flight_route_prices_duration_check CHECK (duration_minutes IS NULL OR duration_minutes > 0),
  CONSTRAINT flight_route_prices_validity_check
    CHECK (
      valid_until > observed_at
      AND valid_until <= observed_at + interval '7 days'
      AND (provider_expires_at IS NULL OR valid_until <= provider_expires_at)
    ),
  CONSTRAINT flight_route_prices_affiliate_check CHECK (affiliate_path IS NULL OR (affiliate_path LIKE '/%' AND affiliate_path NOT LIKE '//%')),
  CONSTRAINT flight_route_prices_status_check CHECK (status IN ('draft', 'published', 'expired'))
);

CREATE INDEX flight_route_prices_route_idx ON public.flight_route_prices
  (origin_city_id, destination_city_id, status, valid_until, market_code, currency_code);

ALTER TABLE public.flight_route_prices ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.flight_route_prices FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.flight_route_prices TO service_role;
