-- ============================================================================
-- Migration: 20260714080000_platform.sql
-- Source of truth: supabase/sql_src
-- Feature: platform
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/schema/_platform/admin.sql

-- Schema: admin
-- Purpose: Operational state for ingestion, publishing, and maintenance workflows.

CREATE SCHEMA IF NOT EXISTS admin;

REVOKE ALL ON SCHEMA admin FROM anon, authenticated;
GRANT USAGE ON SCHEMA admin TO service_role;
