-- ============================================================================
-- Migration: 20260714080150_storage.sql
-- Source of truth: supabase/sql_src
-- Feature: public media storage
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/schema/storage/media_bucket.sql

-- Storage bucket: media
-- Feature: Public media
-- Purpose: Store frontend-ready airport images and airline logos.
-- Responsibilities: Provide public reads while restricting file size and supported image types.

INSERT INTO storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
VALUES (
  'media',
  'media',
  TRUE,
  10485760,
  ARRAY[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/avif',
    'image/svg+xml'
  ]
)
ON CONFLICT (id) DO UPDATE
SET
  name = EXCLUDED.name,
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;
