-- ============================================================================
-- Migration: 20260714080400_pseo_schema.sql
-- Source of truth: supabase/sql_src
-- Feature: pSEO schema
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/schema/pseo/shared/route_price_estimates.sql

-- Table: public.route_price_estimates
-- Feature: Route Price Estimates
-- Purpose: Store provider-neutral derived price ranges without live offer or availability claims.

CREATE TABLE public.route_price_estimates (
  id                      UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  origin_city_id          UUID          NOT NULL REFERENCES public.cities (id),
  destination_city_id     UUID          NOT NULL REFERENCES public.cities (id),
  origin_airport_id       UUID          NULL REFERENCES public.airports (id),
  destination_airport_id  UUID          NULL REFERENCES public.airports (id),
  airline_id              UUID          NULL REFERENCES public.airlines (id),
  trip_type               TEXT          NOT NULL,
  cabin                   TEXT          NOT NULL,
  stop_bucket             TEXT          NOT NULL,
  baggage_included        BOOLEAN       NULL,
  price_min               NUMERIC(14,2) NOT NULL,
  price_max               NUMERIC(14,2) NOT NULL,
  currency_code           TEXT          NOT NULL,
  estimate_method         TEXT          NOT NULL,
  sample_window_start     DATE          NOT NULL,
  sample_window_end       DATE          NOT NULL,
  sample_count            INTEGER       NULL,
  source_id               UUID          NOT NULL REFERENCES admin.data_sources (id),
  source_record_id        TEXT          NOT NULL,
  confidence_score        NUMERIC(4,3)  NOT NULL,
  last_verified_at        TIMESTAMPTZ   NOT NULL,
  valid_until             TIMESTAMPTZ   NOT NULL,
  status                  TEXT          NOT NULL DEFAULT 'draft',
  data_version            UUID          NOT NULL,
  created_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),

  CONSTRAINT route_price_estimates_source_record_key UNIQUE (source_id, source_record_id),
  CONSTRAINT route_price_estimates_direction_check CHECK (origin_city_id <> destination_city_id),
  CONSTRAINT route_price_estimates_trip_type_check CHECK (trip_type IN ('one_way', 'return')),
  CONSTRAINT route_price_estimates_cabin_check CHECK (cabin IN ('economy', 'premium_economy', 'business', 'first', 'any')),
  CONSTRAINT route_price_estimates_stops_check CHECK (stop_bucket IN ('direct', 'one_stop', 'two_stops', 'three_stops', 'any')),
  CONSTRAINT route_price_estimates_price_check CHECK (price_min >= 0 AND price_max >= price_min),
  CONSTRAINT route_price_estimates_currency_check CHECK (currency_code ~ '^[A-Z]{3}$'),
  CONSTRAINT route_price_estimates_window_check CHECK (sample_window_start <= sample_window_end),
  CONSTRAINT route_price_estimates_sample_check CHECK (sample_count IS NULL OR sample_count > 0),
  CONSTRAINT route_price_estimates_confidence_check CHECK (confidence_score BETWEEN 0 AND 1),
  CONSTRAINT route_price_estimates_validity_check CHECK (valid_until > last_verified_at),
  CONSTRAINT route_price_estimates_status_check CHECK (status IN ('draft', 'review', 'published', 'expired'))
);

CREATE INDEX route_price_estimates_market_idx ON public.route_price_estimates USING btree (origin_city_id, destination_city_id, status, valid_until, cabin, stop_bucket);
ALTER TABLE public.route_price_estimates ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.route_price_estimates FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.route_price_estimates TO service_role;

-- >>> supabase/sql_src/schema/pseo/shared/pseo_pages.sql

-- Table: public.pseo_pages
-- Feature: Interactive pSEO
-- Purpose: Register canonical URLs, publication state, and sitemap eligibility.
-- Responsibilities: Provide stable page identity and database-owned indexability metadata.

CREATE TABLE public.pseo_pages (
  id                   UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  page_type            TEXT         NOT NULL,
  entity_key           TEXT         NOT NULL,
  locale               TEXT         NOT NULL,
  canonical_path       TEXT         NOT NULL,
  display_title        TEXT         NOT NULL,
  status               TEXT         NOT NULL DEFAULT 'draft',
  is_indexable         BOOLEAN      NOT NULL DEFAULT FALSE,
  noindex_reason       TEXT         NULL,
  data_version         UUID         NULL REFERENCES public.publication_versions (id),
  content_updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  source_freshness_at  TIMESTAMPTZ  NULL,
  generated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT pseo_pages_entity_locale_key
    UNIQUE (page_type, entity_key, locale),

  CONSTRAINT pseo_pages_canonical_locale_key
    UNIQUE (canonical_path, locale),

  CONSTRAINT pseo_pages_type_check
    CHECK (
      page_type IN (
        'city',
        'airport',
        'city_route',
        'airline_city',
        'country_route',
        'guide'
      )
    ),

  CONSTRAINT pseo_pages_entity_key_check
    CHECK (entity_key ~ '^[a-z0-9]+(?:[-:][a-z0-9]+)*$'),

  CONSTRAINT pseo_pages_locale_check
    CHECK (locale ~ '^[a-z]{2}(?:-[A-Z]{2})?$'),

  CONSTRAINT pseo_pages_canonical_path_check
    CHECK (canonical_path = '/' OR canonical_path ~ '^/[a-z0-9]+(?:[-/][a-z0-9]+)*$'),

  CONSTRAINT pseo_pages_title_check
    CHECK (
      display_title = btrim(display_title)
      AND char_length(display_title) BETWEEN 1 AND 160
    ),

  CONSTRAINT pseo_pages_status_check
    CHECK (status IN ('draft', 'review', 'published', 'archived')),

  CONSTRAINT pseo_pages_indexability_check
    CHECK (
      (is_indexable = TRUE AND status = 'published' AND noindex_reason IS NULL)
      OR
      (is_indexable = FALSE AND noindex_reason IS NOT NULL)
    )
);

CREATE INDEX pseo_pages_sitemap_idx
ON public.pseo_pages USING btree (
  locale,
  page_type,
  canonical_path
)
WHERE is_indexable = TRUE AND status = 'published';

ALTER TABLE public.pseo_pages ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.pseo_pages FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.pseo_pages TO service_role;

-- >>> supabase/sql_src/schema/pseo/homepage/homepage_statistics.sql

-- Table: public.homepage_statistics
-- Feature: Homepage
-- Purpose: Store one bounded public coverage snapshot for the current publication.

CREATE TABLE public.homepage_statistics (
  singleton_key       BOOLEAN      PRIMARY KEY DEFAULT TRUE,
  city_count          INTEGER      NOT NULL,
  airport_count       INTEGER      NOT NULL,
  direct_route_count  INTEGER      NOT NULL,
  data_version        UUID         NOT NULL REFERENCES public.publication_versions (id),
  generated_at        TIMESTAMPTZ  NOT NULL,

  CONSTRAINT homepage_statistics_singleton_check
    CHECK (singleton_key = TRUE),

  CONSTRAINT homepage_statistics_counts_check
    CHECK (city_count >= 0 AND airport_count >= 0 AND direct_route_count >= 0)
);

ALTER TABLE public.homepage_statistics ENABLE ROW LEVEL SECURITY;

CREATE POLICY homepage_statistics_public_read
ON public.homepage_statistics
FOR SELECT
TO anon, authenticated
USING (TRUE);

REVOKE ALL ON TABLE public.homepage_statistics FROM anon, authenticated;
GRANT SELECT ON TABLE public.homepage_statistics TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.homepage_statistics TO service_role;

-- >>> supabase/sql_src/schema/pseo/city/city_pages.sql

-- Table: public.city_pages
-- Feature: Interactive pSEO
-- Purpose: Store reviewed city-page editorial content.
-- Responsibilities: Link editorial content to the canonical pSEO registry and normalized city.

CREATE TABLE public.city_pages (
  id                        UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  pseo_page_id              UUID         NOT NULL UNIQUE REFERENCES public.pseo_pages (id),
  city_id                   UUID         NOT NULL REFERENCES public.cities (id),
  locale                    TEXT         NOT NULL,
  route_direction           TEXT         NOT NULL DEFAULT 'outbound',
  h1                        TEXT         NOT NULL,
  subheadline               TEXT         NOT NULL,
  seo_title                 TEXT         NOT NULL,
  meta_description          TEXT         NOT NULL,
  og_title                  TEXT         NOT NULL,
  og_description            TEXT         NOT NULL,
  og_image_path             TEXT         NULL,
  intro                     TEXT         NOT NULL,
  airport_summary           TEXT         NULL,
  primary_airport_id        UUID         NULL REFERENCES public.airports (id),
  content_reviewed_at       TIMESTAMPTZ  NULL,
  created_at                TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT city_pages_city_locale_key
    UNIQUE (city_id, locale, route_direction),

  CONSTRAINT city_pages_direction_check
    CHECK (route_direction IN ('outbound', 'inbound')),

  CONSTRAINT city_pages_locale_check
    CHECK (locale ~ '^[a-z]{2}(?:-[A-Z]{2})?$'),

  CONSTRAINT city_pages_content_check
    CHECK (
      h1 = btrim(h1)
      AND subheadline = btrim(subheadline)
      AND seo_title = btrim(seo_title)
      AND meta_description = btrim(meta_description)
      AND og_title = btrim(og_title)
      AND og_description = btrim(og_description)
      AND intro = btrim(intro)
    )
);

ALTER TABLE public.city_pages ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.city_pages FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.city_pages TO service_role;

-- >>> supabase/sql_src/schema/pseo/city/city_facts.sql

-- Table: public.city_facts
-- Feature: City pSEO
-- Purpose: Store reviewed, cited, structured city knowledge.

CREATE TABLE public.city_facts (
  id                  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  city_id             UUID         NOT NULL REFERENCES public.cities (id),
  locale              TEXT         NOT NULL,
  fact_type           TEXT         NOT NULL,
  title               TEXT         NOT NULL,
  body                TEXT         NOT NULL,
  structured_value    JSONB        NULL,
  primary_source_url  TEXT         NOT NULL,
  last_verified_at    TIMESTAMPTZ  NOT NULL,
  valid_from          DATE         NULL,
  valid_to            DATE         NULL,
  status              TEXT         NOT NULL DEFAULT 'draft',
  data_version        UUID         NOT NULL,
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT city_facts_identity_key UNIQUE (city_id, locale, fact_type, data_version),
  CONSTRAINT city_facts_type_check CHECK (fact_type IN ('currency', 'language', 'timezone', 'entry_guidance', 'climate', 'local_transport', 'travel_tip')),
  CONSTRAINT city_facts_status_check CHECK (status IN ('draft', 'review', 'published')),
  CONSTRAINT city_facts_validity_check CHECK ((valid_from IS NULL) = (valid_to IS NULL))
);

CREATE INDEX city_facts_page_idx ON public.city_facts USING btree (city_id, locale, status, fact_type);
ALTER TABLE public.city_facts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.city_facts FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.city_facts TO service_role;

-- >>> supabase/sql_src/schema/pseo/city/city_page_airport_content.sql

-- Table: public.city_page_airport_content
-- Feature: Interactive pSEO
-- Purpose: Store reviewed airport-hub copy and ordering for one localized city page.
-- Responsibilities: Keep locale-specific editorial content outside normalized airport facts.

CREATE TABLE public.city_page_airport_content (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  city_page_id   UUID         NOT NULL REFERENCES public.city_pages (id) ON DELETE CASCADE,
  airport_id     UUID         NOT NULL REFERENCES public.airports (id),
  hub_label      TEXT         NOT NULL,
  description    TEXT         NOT NULL,
  display_order  SMALLINT     NOT NULL,
  status         TEXT         NOT NULL DEFAULT 'draft',
  reviewed_at    TIMESTAMPTZ  NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT city_page_airport_content_page_airport_key
    UNIQUE (city_page_id, airport_id),

  CONSTRAINT city_page_airport_content_page_order_key
    UNIQUE (city_page_id, display_order),

  CONSTRAINT city_page_airport_content_hub_label_check
    CHECK (
      hub_label = btrim(hub_label)
      AND char_length(hub_label) BETWEEN 2 AND 40
    ),

  CONSTRAINT city_page_airport_content_description_check
    CHECK (
      description = btrim(description)
      AND char_length(description) BETWEEN 20 AND 1000
    ),

  CONSTRAINT city_page_airport_content_order_check
    CHECK (display_order > 0),

  CONSTRAINT city_page_airport_content_status_check
    CHECK (status IN ('draft', 'review', 'published'))
);

CREATE INDEX city_page_airport_content_page_status_order_idx
ON public.city_page_airport_content USING btree (
  city_page_id,
  status,
  display_order
);

ALTER TABLE public.city_page_airport_content ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.city_page_airport_content FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.city_page_airport_content TO service_role;

-- >>> supabase/sql_src/schema/pseo/city/city_page_faqs.sql

-- Table: public.city_page_faqs
-- Feature: Interactive pSEO
-- Purpose: Store ordered, reviewed FAQ content for city pages.
-- Responsibilities: Distinguish editorial, data-backed, and hybrid answers.

CREATE TABLE public.city_page_faqs (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  city_page_id   UUID         NOT NULL REFERENCES public.city_pages (id) ON DELETE CASCADE,
  locale         TEXT         NOT NULL DEFAULT 'en-GB',
  question       TEXT         NOT NULL,
  answer         TEXT         NOT NULL,
  answer_type    TEXT         NOT NULL,
  display_order  SMALLINT     NOT NULL,
  status         TEXT         NOT NULL DEFAULT 'draft',
  reviewed_at    TIMESTAMPTZ  NULL,
  primary_source_url TEXT     NULL,
  last_verified_at TIMESTAMPTZ NULL,
  data_version   UUID         NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT city_page_faqs_page_order_key
    UNIQUE (city_page_id, locale, display_order),

  CONSTRAINT city_page_faqs_page_question_key
    UNIQUE (city_page_id, locale, question),

  CONSTRAINT city_page_faqs_locale_check
    CHECK (locale ~ '^[a-z]{2}(?:-[A-Z]{2})?$'),

  CONSTRAINT city_page_faqs_question_check
    CHECK (
      question = btrim(question)
      AND char_length(question) BETWEEN 5 AND 240
    ),

  CONSTRAINT city_page_faqs_answer_check
    CHECK (
      answer = btrim(answer)
      AND char_length(answer) BETWEEN 10 AND 2000
    ),

  CONSTRAINT city_page_faqs_answer_type_check
    CHECK (answer_type IN ('editorial', 'data_backed', 'hybrid')),

  CONSTRAINT city_page_faqs_order_check
    CHECK (display_order > 0),

  CONSTRAINT city_page_faqs_status_check
    CHECK (status IN ('draft', 'review', 'published'))
);

CREATE INDEX city_page_faqs_page_status_order_idx
ON public.city_page_faqs USING btree (
  city_page_id,
  status,
  display_order
);

ALTER TABLE public.city_page_faqs ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.city_page_faqs FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.city_page_faqs TO service_role;

-- >>> supabase/sql_src/schema/pseo/city/city_content_sections.sql

-- Table: public.city_content_sections
-- Feature: City pSEO
-- Purpose: Store bounded reviewed editorial sections for one City Hub.

CREATE TABLE public.city_content_sections (
  id                  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  city_page_id        UUID         NOT NULL REFERENCES public.city_pages (id) ON DELETE CASCADE,
  locale              TEXT         NOT NULL,
  section_type        TEXT         NOT NULL,
  heading             TEXT         NOT NULL,
  body                TEXT         NOT NULL,
  display_order       SMALLINT     NOT NULL,
  status              TEXT         NOT NULL DEFAULT 'draft',
  primary_source_url  TEXT         NULL,
  last_verified_at    TIMESTAMPTZ  NULL,
  reviewed_at         TIMESTAMPTZ  NULL,
  data_version        UUID         NOT NULL,
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT city_content_sections_order_key
    UNIQUE (city_page_id, locale, display_order, data_version),

  CONSTRAINT city_content_sections_type_check
    CHECK (section_type IN ('route_context', 'airport_context', 'travel_context', 'methodology', 'data_disclaimer')),

  CONSTRAINT city_content_sections_status_check
    CHECK (status IN ('draft', 'review', 'published')),

  CONSTRAINT city_content_sections_order_check
    CHECK (display_order > 0)
);

ALTER TABLE public.city_content_sections ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.city_content_sections FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.city_content_sections TO service_role;

-- >>> supabase/sql_src/schema/pseo/airport/airport_pages.sql

-- Table: public.airport_pages
-- Feature: Interactive pSEO
-- Purpose: Store reviewed airport-page editorial content.
-- Responsibilities: Link editorial content to the canonical pSEO registry and normalized airport.

CREATE TABLE public.airport_pages (
  id                          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  pseo_page_id                UUID         NOT NULL UNIQUE REFERENCES public.pseo_pages (id),
  airport_id                  UUID         NOT NULL REFERENCES public.airports (id),
  locale                      TEXT         NOT NULL,
  h1                          TEXT         NOT NULL,
  subheadline                 TEXT         NOT NULL,
  seo_title                   TEXT         NOT NULL,
  meta_description            TEXT         NOT NULL,
  og_title                    TEXT         NOT NULL,
  og_description              TEXT         NOT NULL,
  og_image_path               TEXT         NULL,
  intro                       TEXT         NOT NULL,
  orientation_summary         TEXT         NOT NULL,
  arrival_summary             TEXT         NOT NULL,
  departure_summary           TEXT         NOT NULL,
  primary_city_area_label     TEXT         NULL,
  city_distance_km            NUMERIC(8,2) NULL,
  content_reviewed_at         TIMESTAMPTZ  NULL,
  created_at                  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at                  TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT airport_pages_airport_locale_key
    UNIQUE (airport_id, locale),

  CONSTRAINT airport_pages_locale_check
    CHECK (locale ~ '^[a-z]{2}(?:-[A-Z]{2})?$'),

  CONSTRAINT airport_pages_content_check
    CHECK (
      h1 = btrim(h1)
      AND subheadline = btrim(subheadline)
      AND seo_title = btrim(seo_title)
      AND meta_description = btrim(meta_description)
      AND og_title = btrim(og_title)
      AND og_description = btrim(og_description)
      AND intro = btrim(intro)
      AND orientation_summary = btrim(orientation_summary)
      AND arrival_summary = btrim(arrival_summary)
      AND departure_summary = btrim(departure_summary)
    ),

  CONSTRAINT airport_pages_city_distance_check
    CHECK (
      city_distance_km IS NULL
      OR city_distance_km >= 0
    )
);

ALTER TABLE public.airport_pages ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.airport_pages FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.airport_pages TO service_role;

-- >>> supabase/sql_src/schema/pseo/airport/airport_journey_steps.sql

-- Table: public.airport_journey_steps
-- Feature: Airport Journey pSEO
-- Purpose: Store ordered, reviewed arrival and departure guidance.

CREATE TABLE public.airport_journey_steps (
  id                  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  airport_page_id     UUID         NOT NULL REFERENCES public.airport_pages (id) ON DELETE CASCADE,
  locale              TEXT         NOT NULL,
  journey_type        TEXT         NOT NULL,
  audience            TEXT         NOT NULL DEFAULT 'all',
  title               TEXT         NOT NULL,
  body                TEXT         NOT NULL,
  display_order       SMALLINT     NOT NULL,
  primary_source_url  TEXT         NOT NULL,
  last_verified_at    TIMESTAMPTZ  NOT NULL,
  status              TEXT         NOT NULL DEFAULT 'draft',
  data_version        UUID         NOT NULL,
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT airport_journey_steps_order_key
    UNIQUE (airport_page_id, locale, journey_type, audience, display_order, data_version),

  CONSTRAINT airport_journey_steps_type_check
    CHECK (journey_type IN ('arrival', 'departure')),

  CONSTRAINT airport_journey_steps_audience_check
    CHECK (audience IN ('all', 'domestic', 'international')),

  CONSTRAINT airport_journey_steps_status_check
    CHECK (status IN ('draft', 'review', 'published')),

  CONSTRAINT airport_journey_steps_order_check
    CHECK (display_order > 0)
);

CREATE INDEX airport_journey_steps_page_status_order_idx
ON public.airport_journey_steps USING btree (
  airport_page_id,
  locale,
  journey_type,
  status,
  display_order
);

ALTER TABLE public.airport_journey_steps ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.airport_journey_steps FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.airport_journey_steps TO service_role;

-- >>> supabase/sql_src/schema/pseo/airport/airport_access_options.sql

-- Table: public.airport_access_options
-- Feature: Interactive pSEO
-- Purpose: Store reviewed ways to travel to and from an airport.

CREATE TABLE public.airport_access_options (
  id                       UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  airport_page_id          UUID          NOT NULL REFERENCES public.airport_pages (id) ON DELETE CASCADE,
  journey_direction       TEXT          NOT NULL DEFAULT 'from_airport',
  access_type              TEXT          NOT NULL,
  name                     TEXT          NOT NULL,
  destination_label        TEXT          NOT NULL,
  summary                  TEXT          NOT NULL,
  duration_min_minutes     INTEGER       NULL,
  duration_max_minutes     INTEGER       NULL,
  price_min                NUMERIC(12,2) NULL,
  price_max                NUMERIC(12,2) NULL,
  currency_code            TEXT          NULL,
  operating_hours_summary  TEXT          NULL,
  pickup_location_summary  TEXT          NULL,
  best_for_label           TEXT          NULL,
  luggage_summary          TEXT          NULL,
  accessibility_summary    TEXT          NULL,
  booking_url              TEXT          NULL,
  primary_source_url       TEXT          NOT NULL,
  last_verified_at         TIMESTAMPTZ   NOT NULL,
  display_order            SMALLINT      NOT NULL,
  status                   TEXT          NOT NULL DEFAULT 'draft',
  created_at               TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ   NOT NULL DEFAULT now(),

  CONSTRAINT airport_access_options_page_order_key
    UNIQUE (airport_page_id, display_order),

  CONSTRAINT airport_access_options_type_check
    CHECK (access_type IN ('rail', 'metro', 'bus', 'taxi', 'ride_hailing', 'transfer', 'other')),

  CONSTRAINT airport_access_options_direction_check
    CHECK (journey_direction IN ('from_airport', 'to_airport', 'both')),

  CONSTRAINT airport_access_options_duration_check
    CHECK (
      (duration_min_minutes IS NULL) = (duration_max_minutes IS NULL)
      AND (
        duration_min_minutes IS NULL
        OR (duration_min_minutes > 0 AND duration_max_minutes >= duration_min_minutes)
      )
    ),

  CONSTRAINT airport_access_options_price_check
    CHECK (
      (price_min IS NULL AND price_max IS NULL AND currency_code IS NULL)
      OR (
        price_min >= 0
        AND price_max >= price_min
        AND currency_code ~ '^[A-Z]{3}$'
      )
    ),

  CONSTRAINT airport_access_options_order_check
    CHECK (display_order > 0),

  CONSTRAINT airport_access_options_status_check
    CHECK (status IN ('draft', 'review', 'published'))
);

CREATE INDEX airport_access_options_page_status_order_idx
ON public.airport_access_options USING btree (airport_page_id, status, display_order);

ALTER TABLE public.airport_access_options ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.airport_access_options FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.airport_access_options TO service_role;

-- >>> supabase/sql_src/schema/pseo/airport/airport_lounges.sql

-- Table: public.airport_lounges
-- Feature: Interactive pSEO
-- Purpose: Store reviewed lounge summaries relevant to flight planning.

CREATE TABLE public.airport_lounges (
  id                  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  airport_page_id     UUID         NOT NULL REFERENCES public.airport_pages (id) ON DELETE CASCADE,
  name                TEXT         NOT NULL,
  location_summary    TEXT         NOT NULL,
  location_type       TEXT         NOT NULL DEFAULT 'unknown',
  access_summary      TEXT         NOT NULL,
  operating_hours_summary TEXT     NULL,
  amenities           TEXT[]       NOT NULL DEFAULT '{}'::TEXT[],
  estimated_price_min NUMERIC(12,2) NULL,
  estimated_price_max NUMERIC(12,2) NULL,
  currency_code       TEXT         NULL,
  affiliate_url       TEXT         NULL,
  official_url        TEXT         NULL,
  primary_source_url  TEXT         NOT NULL,
  last_verified_at    TIMESTAMPTZ  NOT NULL,
  display_order       SMALLINT     NOT NULL,
  status              TEXT         NOT NULL DEFAULT 'draft',
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT airport_lounges_page_name_key
    UNIQUE (airport_page_id, name),

  CONSTRAINT airport_lounges_page_order_key
    UNIQUE (airport_page_id, display_order),

  CONSTRAINT airport_lounges_location_type_check
    CHECK (location_type IN ('airside', 'landside', 'unknown')),

  CONSTRAINT airport_lounges_amenities_check
    CHECK (amenities <@ ARRAY['wifi', 'food', 'drinks', 'showers', 'rest_area', 'work_area']::TEXT[]),

  CONSTRAINT airport_lounges_price_check
    CHECK (
      (estimated_price_min IS NULL AND estimated_price_max IS NULL AND currency_code IS NULL)
      OR (
        estimated_price_min >= 0
        AND estimated_price_max >= estimated_price_min
        AND currency_code ~ '^[A-Z]{3}$'
      )
    ),

  CONSTRAINT airport_lounges_order_check
    CHECK (display_order > 0),

  CONSTRAINT airport_lounges_status_check
    CHECK (status IN ('draft', 'review', 'published'))
);

CREATE INDEX airport_lounges_page_status_order_idx
ON public.airport_lounges USING btree (airport_page_id, status, display_order);

ALTER TABLE public.airport_lounges ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.airport_lounges FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.airport_lounges TO service_role;

-- >>> supabase/sql_src/schema/pseo/airport/airport_parking_information.sql

-- Table: public.airport_parking_information
-- Feature: Interactive pSEO
-- Purpose: Store one reviewed parking overview per localized airport page.

CREATE TABLE public.airport_parking_information (
  id                      UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  airport_page_id         UUID         NOT NULL UNIQUE REFERENCES public.airport_pages (id) ON DELETE CASCADE,
  summary                 TEXT         NOT NULL,
  short_stay_available    BOOLEAN      NULL,
  long_stay_available     BOOLEAN      NULL,
  reservation_available  BOOLEAN      NULL,
  shuttle_available      BOOLEAN      NULL,
  official_url            TEXT         NULL,
  primary_source_url      TEXT         NOT NULL,
  last_verified_at        TIMESTAMPTZ  NOT NULL,
  status                  TEXT         NOT NULL DEFAULT 'draft',
  created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT airport_parking_information_status_check
    CHECK (status IN ('draft', 'review', 'published'))
);

CREATE INDEX airport_parking_information_page_status_idx
ON public.airport_parking_information USING btree (airport_page_id, status);

ALTER TABLE public.airport_parking_information ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.airport_parking_information FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.airport_parking_information TO service_role;

-- >>> supabase/sql_src/schema/pseo/airport/airport_page_notices.sql

-- Table: public.airport_page_notices
-- Feature: Interactive pSEO
-- Purpose: Store durable, reviewed airport planning notices.

CREATE TABLE public.airport_page_notices (
  id                  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  airport_page_id     UUID         NOT NULL REFERENCES public.airport_pages (id) ON DELETE CASCADE,
  notice_type         TEXT         NOT NULL,
  title               TEXT         NOT NULL,
  body                TEXT         NOT NULL,
  severity            TEXT         NOT NULL DEFAULT 'info',
  primary_source_url  TEXT         NOT NULL,
  last_verified_at    TIMESTAMPTZ  NOT NULL,
  display_order       SMALLINT     NOT NULL,
  status              TEXT         NOT NULL DEFAULT 'draft',
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT airport_page_notices_page_order_key
    UNIQUE (airport_page_id, display_order),

  CONSTRAINT airport_page_notices_type_check
    CHECK (notice_type IN ('general', 'access', 'connection', 'airport_confusion')),

  CONSTRAINT airport_page_notices_severity_check
    CHECK (severity IN ('info', 'important')),

  CONSTRAINT airport_page_notices_order_check
    CHECK (display_order > 0),

  CONSTRAINT airport_page_notices_status_check
    CHECK (status IN ('draft', 'review', 'published'))
);

CREATE INDEX airport_page_notices_page_status_order_idx
ON public.airport_page_notices USING btree (airport_page_id, status, display_order);

ALTER TABLE public.airport_page_notices ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.airport_page_notices FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.airport_page_notices TO service_role;

-- >>> supabase/sql_src/schema/pseo/airport/airport_page_faqs.sql

-- Table: public.airport_page_faqs
-- Feature: Interactive pSEO
-- Purpose: Store ordered, reviewed FAQ content for airport pages.

CREATE TABLE public.airport_page_faqs (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  airport_page_id  UUID         NOT NULL REFERENCES public.airport_pages (id) ON DELETE CASCADE,
  locale           TEXT         NOT NULL DEFAULT 'en-GB',
  question         TEXT         NOT NULL,
  answer           TEXT         NOT NULL,
  answer_type      TEXT         NOT NULL,
  display_order    SMALLINT     NOT NULL,
  status           TEXT         NOT NULL DEFAULT 'draft',
  reviewed_at      TIMESTAMPTZ  NULL,
  primary_source_url TEXT       NULL,
  last_verified_at TIMESTAMPTZ  NULL,
  data_version     UUID         NULL,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT airport_page_faqs_page_order_key
    UNIQUE (airport_page_id, locale, display_order),

  CONSTRAINT airport_page_faqs_page_question_key
    UNIQUE (airport_page_id, locale, question),

  CONSTRAINT airport_page_faqs_locale_check
    CHECK (locale ~ '^[a-z]{2}(?:-[A-Z]{2})?$'),

  CONSTRAINT airport_page_faqs_answer_type_check
    CHECK (answer_type IN ('editorial', 'data_backed', 'hybrid')),

  CONSTRAINT airport_page_faqs_order_check
    CHECK (display_order > 0),

  CONSTRAINT airport_page_faqs_status_check
    CHECK (status IN ('draft', 'review', 'published'))
);

CREATE INDEX airport_page_faqs_page_status_order_idx
ON public.airport_page_faqs USING btree (airport_page_id, status, display_order);

ALTER TABLE public.airport_page_faqs ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.airport_page_faqs FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.airport_page_faqs TO service_role;

-- >>> supabase/sql_src/schema/pseo/airport/airport_facilities.sql

-- Table: public.airport_facilities
-- Feature: Airport pSEO
-- Purpose: Store reviewed terminal or airport-wide facility guidance.

CREATE TABLE public.airport_facilities (
  id                  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  airport_id          UUID         NOT NULL REFERENCES public.airports (id),
  terminal_id         UUID         NULL REFERENCES public.airport_terminals (id),
  locale              TEXT         NOT NULL,
  category            TEXT         NOT NULL,
  name                TEXT         NOT NULL,
  summary             TEXT         NOT NULL,
  operating_hours     TEXT         NULL,
  primary_source_url  TEXT         NOT NULL,
  last_verified_at    TIMESTAMPTZ  NOT NULL,
  status              TEXT         NOT NULL DEFAULT 'draft',
  display_order       SMALLINT     NOT NULL,
  data_version        UUID         NOT NULL,
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT airport_facilities_identity_key UNIQUE (airport_id, locale, name, data_version),
  CONSTRAINT airport_facilities_category_check CHECK (category IN ('wifi', 'food', 'shopping', 'shower', 'luggage', 'prayer', 'accessibility', 'family', 'medical', 'other')),
  CONSTRAINT airport_facilities_status_check CHECK (status IN ('draft', 'review', 'published')),
  CONSTRAINT airport_facilities_order_check CHECK (display_order > 0)
);

CREATE INDEX airport_facilities_page_idx ON public.airport_facilities USING btree (airport_id, locale, status, display_order);
ALTER TABLE public.airport_facilities ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.airport_facilities FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.airport_facilities TO service_role;

-- >>> supabase/sql_src/schema/pseo/route/route_pages.sql

-- Table: public.route_pages
-- Feature: Route pSEO
-- Purpose: Store reviewed city-pair Route Page editorial content.

CREATE TABLE public.route_pages (
  id                         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  pseo_page_id               UUID         NOT NULL UNIQUE REFERENCES public.pseo_pages (id),
  origin_city_id             UUID         NOT NULL REFERENCES public.cities (id),
  destination_city_id        UUID         NOT NULL REFERENCES public.cities (id),
  locale                     TEXT         NOT NULL,
  h1                         TEXT         NOT NULL,
  subheadline                TEXT         NOT NULL,
  seo_title                  TEXT         NOT NULL,
  meta_description           TEXT         NOT NULL,
  intro                      TEXT         NOT NULL,
  content_reviewed_at        TIMESTAMPTZ  NULL,
  created_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at                 TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT route_pages_market_key UNIQUE (origin_city_id, destination_city_id, locale),
  CONSTRAINT route_pages_direction_check CHECK (origin_city_id <> destination_city_id),
  CONSTRAINT route_pages_locale_check CHECK (locale ~ '^[a-z]{2}(?:-[A-Z]{2})?$')
);
ALTER TABLE public.route_pages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.route_pages FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.route_pages TO service_role;

-- >>> supabase/sql_src/schema/pseo/route/route_page_faqs.sql

-- Table: public.route_page_faqs
-- Feature: Route pSEO
-- Purpose: Store reviewed ordered Route Page FAQs.

CREATE TABLE public.route_page_faqs (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  route_page_id  UUID         NOT NULL REFERENCES public.route_pages (id) ON DELETE CASCADE,
  locale         TEXT         NOT NULL DEFAULT 'en-GB',
  question       TEXT         NOT NULL,
  answer         TEXT         NOT NULL,
  answer_type    TEXT         NOT NULL,
  display_order  SMALLINT     NOT NULL,
  status         TEXT         NOT NULL DEFAULT 'draft',
  reviewed_at    TIMESTAMPTZ  NULL,
  primary_source_url TEXT     NULL,
  last_verified_at TIMESTAMPTZ NULL,
  data_version   UUID         NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT route_page_faqs_order_key UNIQUE (route_page_id, locale, display_order),
  CONSTRAINT route_page_faqs_question_key UNIQUE (route_page_id, locale, question),
  CONSTRAINT route_page_faqs_locale_check CHECK (locale ~ '^[a-z]{2}(?:-[A-Z]{2})?$'),
  CONSTRAINT route_page_faqs_type_check CHECK (answer_type IN ('editorial', 'data_backed', 'hybrid')),
  CONSTRAINT route_page_faqs_status_check CHECK (status IN ('draft', 'review', 'published'))
);

ALTER TABLE public.route_page_faqs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.route_page_faqs FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.route_page_faqs TO service_role;

-- >>> supabase/sql_src/schema/pseo/route/route_page_airport_comparisons.sql

-- Table: public.route_page_airport_comparisons
-- Feature: Route pSEO
-- Purpose: Store reviewed origin/destination airport comparison facts.

CREATE TABLE public.route_page_airport_comparisons (
  id                  UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  route_page_id       UUID          NOT NULL REFERENCES public.route_pages (id) ON DELETE CASCADE,
  airport_id          UUID          NOT NULL REFERENCES public.airports (id),
  endpoint_role       TEXT          NOT NULL,
  transfer_summary    TEXT          NOT NULL,
  duration_min_minutes INTEGER      NULL,
  duration_max_minutes INTEGER      NULL,
  price_min           NUMERIC(12,2) NULL,
  price_max           NUMERIC(12,2) NULL,
  currency_code       TEXT          NULL,
  primary_source_url  TEXT          NOT NULL,
  last_verified_at    TIMESTAMPTZ   NOT NULL,
  display_order       SMALLINT      NOT NULL,
  status              TEXT          NOT NULL DEFAULT 'draft',
  created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),

  CONSTRAINT route_page_airports_identity_key UNIQUE (route_page_id, airport_id, endpoint_role),
  CONSTRAINT route_page_airports_role_check CHECK (endpoint_role IN ('origin', 'destination')),
  CONSTRAINT route_page_airports_status_check CHECK (status IN ('draft', 'review', 'published'))
);

ALTER TABLE public.route_page_airport_comparisons ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.route_page_airport_comparisons FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.route_page_airport_comparisons TO service_role;

-- >>> supabase/sql_src/schema/pseo/route/route_page_travel_facts.sql

-- Table: public.route_page_travel_facts
-- Feature: Route pSEO
-- Purpose: Store reviewed, cited route-specific travel preparation facts.

CREATE TABLE public.route_page_travel_facts (
  id                  UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  route_page_id       UUID         NOT NULL REFERENCES public.route_pages (id) ON DELETE CASCADE,
  locale              TEXT         NOT NULL,
  fact_type           TEXT         NOT NULL,
  title               TEXT         NOT NULL,
  body                TEXT         NOT NULL,
  structured_value    JSONB        NULL,
  primary_source_url  TEXT         NOT NULL,
  last_verified_at    TIMESTAMPTZ  NOT NULL,
  status              TEXT         NOT NULL DEFAULT 'draft',
  display_order       SMALLINT     NOT NULL,
  data_version        UUID         NOT NULL,
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT route_page_travel_facts_identity_key UNIQUE (route_page_id, locale, fact_type, data_version),
  CONSTRAINT route_page_travel_facts_type_check CHECK (fact_type IN ('timezone', 'entry_guidance', 'transit_guidance', 'currency', 'language', 'arrival_transport', 'travel_tip')),
  CONSTRAINT route_page_travel_facts_status_check CHECK (status IN ('draft', 'review', 'published'))
);

ALTER TABLE public.route_page_travel_facts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.route_page_travel_facts FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.route_page_travel_facts TO service_role;

-- >>> supabase/sql_src/schema/pseo/route/route_page_editorial_sections.sql

-- Table: public.route_page_editorial_sections
-- Feature: Route pSEO
-- Purpose: Store bounded reviewed editorial sections without provider-specific layout fields.

CREATE TABLE public.route_page_editorial_sections (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  route_page_id  UUID         NOT NULL REFERENCES public.route_pages (id) ON DELETE CASCADE,
  locale         TEXT         NOT NULL,
  section_type   TEXT         NOT NULL,
  heading        TEXT         NOT NULL,
  body           TEXT         NOT NULL,
  display_order  SMALLINT     NOT NULL,
  status         TEXT         NOT NULL DEFAULT 'draft',
  reviewed_at    TIMESTAMPTZ  NULL,
  primary_source_url TEXT     NULL,
  last_verified_at TIMESTAMPTZ NULL,
  data_version   UUID         NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT route_page_editorial_order_key UNIQUE (route_page_id, locale, display_order),
  CONSTRAINT route_page_editorial_type_check CHECK (section_type IN ('direct', 'indirect', 'schedule', 'before_you_fly', 'alternatives', 'methodology', 'disclosure')),
  CONSTRAINT route_page_editorial_status_check CHECK (status IN ('draft', 'review', 'published'))
);

ALTER TABLE public.route_page_editorial_sections ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.route_page_editorial_sections FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.route_page_editorial_sections TO service_role;

-- >>> supabase/sql_src/schema/pseo/city/city_page_read_models.sql

CREATE TABLE public.city_page_read_models (
  id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  publication_version_id UUID        NOT NULL REFERENCES public.publication_versions (id) ON DELETE CASCADE,
  city_id                UUID        NOT NULL REFERENCES public.cities (id),
  locale                 TEXT        NOT NULL,
  canonical_slug         TEXT        NOT NULL,
  payload                JSONB       NOT NULL,
  generated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT city_page_read_models_identity_key
  UNIQUE (publication_version_id, city_id, locale),

  CONSTRAINT city_page_read_models_slug_key
  UNIQUE (publication_version_id, canonical_slug, locale),

  CONSTRAINT city_page_read_models_payload_check
  CHECK (jsonb_typeof(payload) = 'object')
);

CREATE INDEX city_page_read_models_lookup_idx
ON public.city_page_read_models USING btree (canonical_slug, locale, publication_version_id);

ALTER TABLE public.city_page_read_models ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.city_page_read_models FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.city_page_read_models TO service_role;

-- >>> supabase/sql_src/schema/pseo/airport/airport_page_read_models.sql

CREATE TABLE public.airport_page_read_models (
  id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  publication_version_id UUID        NOT NULL REFERENCES public.publication_versions (id) ON DELETE CASCADE,
  airport_id             UUID        NOT NULL REFERENCES public.airports (id),
  locale                 TEXT        NOT NULL,
  airport_iata           TEXT        NOT NULL,
  payload                JSONB       NOT NULL,
  generated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT airport_page_read_models_identity_key
  UNIQUE (publication_version_id, airport_id, locale),

  CONSTRAINT airport_page_read_models_iata_key
  UNIQUE (publication_version_id, airport_iata, locale),

  CONSTRAINT airport_page_read_models_iata_check
  CHECK (airport_iata ~ '^[A-Z0-9]{3}$'),

  CONSTRAINT airport_page_read_models_payload_check
  CHECK (jsonb_typeof(payload) = 'object')
);

CREATE INDEX airport_page_read_models_lookup_idx
ON public.airport_page_read_models USING btree (airport_iata, locale, publication_version_id);

ALTER TABLE public.airport_page_read_models ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.airport_page_read_models FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.airport_page_read_models TO service_role;

-- >>> supabase/sql_src/schema/pseo/route/route_page_read_models.sql

CREATE TABLE public.route_page_read_models (
  id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  publication_version_id UUID        NOT NULL REFERENCES public.publication_versions (id) ON DELETE CASCADE,
  route_page_id          UUID        NOT NULL REFERENCES public.route_pages (id),
  locale                 TEXT        NOT NULL,
  canonical_slug         TEXT        NOT NULL,
  payload                JSONB       NOT NULL,
  generated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT route_page_read_models_identity_key
  UNIQUE (publication_version_id, route_page_id, locale),

  CONSTRAINT route_page_read_models_slug_key
  UNIQUE (publication_version_id, canonical_slug, locale),

  CONSTRAINT route_page_read_models_payload_check
  CHECK (jsonb_typeof(payload) = 'object')
);

CREATE INDEX route_page_read_models_lookup_idx
ON public.route_page_read_models USING btree (canonical_slug, locale, publication_version_id);

ALTER TABLE public.route_page_read_models ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.route_page_read_models FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.route_page_read_models TO service_role;

-- >>> supabase/sql_src/schema/pseo/shared/pseo_internal_links.sql

-- Table: public.pseo_internal_links
-- Feature: Interactive pSEO
-- Purpose: Store a precomputed semantic internal-link graph.
-- Responsibilities: Keep anchor, placement, relevance, and data-version decisions deterministic.

CREATE TABLE public.pseo_internal_links (
  id                UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
  source_page_id    UUID            NOT NULL REFERENCES public.pseo_pages (id) ON DELETE CASCADE,
  target_page_id    UUID            NOT NULL REFERENCES public.pseo_pages (id) ON DELETE CASCADE,
  link_cluster      TEXT            NOT NULL,
  anchor_text       TEXT            NOT NULL,
  secondary_text    TEXT            NULL,
  display_zone      TEXT            NOT NULL,
  relevance_score   NUMERIC(8, 4)   NOT NULL,
  display_order     SMALLINT        NOT NULL,
  is_featured       BOOLEAN         NOT NULL DEFAULT FALSE,
  data_version      UUID            NULL,
  generated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),

  CONSTRAINT pseo_internal_links_target_key
    UNIQUE (source_page_id, target_page_id, link_cluster),

  CONSTRAINT pseo_internal_links_direction_check
    CHECK (source_page_id <> target_page_id),

  CONSTRAINT pseo_internal_links_cluster_check
    CHECK (
      link_cluster IN (
        'popular_routes',
        'airports',
        'airlines',
        'direct_countries',
        'change_source_city',
        'reverse_routes',
        'guides',
        'outbound_routes',
        'inbound_routes',
        'nearby_airports',
        'city_flights_from',
        'city_flights_to',
        'airport_airlines'
      )
    ),

  CONSTRAINT pseo_internal_links_anchor_check
    CHECK (
      anchor_text = btrim(anchor_text)
      AND char_length(anchor_text) BETWEEN 1 AND 180
    ),

  CONSTRAINT pseo_internal_links_zone_check
    CHECK (display_zone ~ '^[a-z0-9]+(?:_[a-z0-9]+)*$'),

  CONSTRAINT pseo_internal_links_score_check
    CHECK (relevance_score >= 0),

  CONSTRAINT pseo_internal_links_order_check
    CHECK (display_order > 0)
);

CREATE INDEX pseo_internal_links_source_cluster_order_idx
ON public.pseo_internal_links USING btree (
  source_page_id,
  link_cluster,
  display_order,
  relevance_score DESC
);

ALTER TABLE public.pseo_internal_links ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.pseo_internal_links FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.pseo_internal_links TO service_role;
