-- ============================================================================
-- Migration: 20260714080300_route_discovery_schema.sql
-- Source of truth: supabase/sql_src
-- Feature: route discovery schema
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/schema/pseo/shared/publication_versions.sql

-- Table: public.publication_versions
-- Feature: Shared Read Models
-- Purpose: Track atomic candidate and current read-model publications.

CREATE TABLE public.publication_versions (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  status         TEXT         NOT NULL DEFAULT 'building',
  is_current     BOOLEAN      NOT NULL DEFAULT FALSE,
  source_type    TEXT         NOT NULL,
  started_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  published_at   TIMESTAMPTZ  NULL,
  failure_code   TEXT         NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT publication_versions_status_check
    CHECK (status IN ('building', 'published', 'failed', 'retired')),

  CONSTRAINT publication_versions_source_check
    CHECK (source_type IN ('production', 'staging', 'development_fixture')),

  CONSTRAINT publication_versions_current_check
    CHECK (is_current = FALSE OR (status = 'published' AND published_at IS NOT NULL)),

  CONSTRAINT publication_versions_failure_check
    CHECK ((status = 'failed') = (failure_code IS NOT NULL))
);

CREATE UNIQUE INDEX publication_versions_one_current_idx
ON public.publication_versions USING btree (is_current)
WHERE is_current = TRUE;

ALTER TABLE public.publication_versions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.publication_versions FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.publication_versions TO service_role;

-- >>> supabase/sql_src/schema/route_discovery/flight_route_options.sql

-- Table: public.flight_route_options
-- Feature: Flight Route Discovery
-- Purpose: Disposable, versioned read projection built from fresh route prices.

CREATE TABLE public.flight_route_options (
  id UUID NOT NULL,
  publication_version_id UUID NOT NULL REFERENCES public.publication_versions (id) ON DELETE CASCADE,
  origin_city_id UUID NOT NULL REFERENCES public.cities (id),
  origin_city_slug TEXT NOT NULL,
  origin_country_code TEXT NOT NULL,
  destination_city_id UUID NOT NULL REFERENCES public.cities (id),
  destination_city_slug TEXT NOT NULL,
  destination_country_code TEXT NOT NULL,
  origin_airport_id UUID NOT NULL REFERENCES public.airports (id),
  origin_airport_iata TEXT NOT NULL,
  destination_airport_id UUID NOT NULL REFERENCES public.airports (id),
  destination_airport_iata TEXT NOT NULL,
  canonical_airline_id UUID NULL REFERENCES public.airlines (id),
  provider_airline_iata TEXT NULL,
  evidence_type TEXT NOT NULL,
  confidence_score NUMERIC(4,3) NOT NULL,
  observed_amount NUMERIC(14,2) NULL,
  currency_code TEXT NULL,
  observation_valid_until TIMESTAMPTZ NULL,
  route_path TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (publication_version_id, id),
  CONSTRAINT flight_route_options_direction_check CHECK (origin_city_id <> destination_city_id),
  CONSTRAINT flight_route_options_amount_check
    CHECK (
      (observed_amount IS NULL AND currency_code IS NULL)
      OR (observed_amount >= 0 AND currency_code ~ '^[A-Z]{3}$')
    )
);

CREATE INDEX flight_route_options_origin_idx ON public.flight_route_options
  (publication_version_id, origin_city_slug, confidence_score DESC, id);
CREATE INDEX flight_route_options_pair_idx ON public.flight_route_options
  (publication_version_id, origin_city_slug, destination_city_slug, confidence_score DESC, id);

ALTER TABLE public.flight_route_options ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.flight_route_options FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.flight_route_options TO service_role;
