-- ============================================================================
-- Migration: 20260714080800_route_discovery_functions.sql
-- Source of truth: supabase/sql_src
-- Feature: route discovery functions
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/functions/route_discovery/calculate_layover_minutes.sql

-- ============================================================================
-- Function: public.calculate_layover_minutes
-- Feature: Route Discovery
-- Purpose: Calculate connection time using two local timestamps at the same airport.
-- Responsibilities: Normalize a same-day or next-day departure into a positive minute interval.
-- Notes: The caller applies the accepted minimum and maximum connection bounds.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.calculate_layover_minutes(
  p_arrival_local_time TIME,
  p_arrival_day_offset SMALLINT,
  p_next_departure_local_time TIME
)
RETURNS INTEGER
LANGUAGE sql
IMMUTABLE
STRICT
SET search_path = ''
AS $$
  WITH minute_values AS (
    SELECT
      (
        p_arrival_day_offset::INTEGER * 1440
        + extract(HOUR FROM p_arrival_local_time)::INTEGER * 60
        + extract(MINUTE FROM p_arrival_local_time)::INTEGER
      ) AS arrival_minute,
      (
        extract(HOUR FROM p_next_departure_local_time)::INTEGER * 60
        + extract(MINUTE FROM p_next_departure_local_time)::INTEGER
      ) AS departure_minute
  )
  SELECT
    CASE
      WHEN mod(mod(departure_minute - arrival_minute, 1440) + 1440, 1440) = 0
        THEN 1440
      ELSE mod(mod(departure_minute - arrival_minute, 1440) + 1440, 1440)
    END
  FROM minute_values;
$$;

REVOKE ALL ON FUNCTION public.calculate_layover_minutes(TIME, SMALLINT, TIME) FROM public;
GRANT EXECUTE ON FUNCTION public.calculate_layover_minutes(TIME, SMALLINT, TIME) TO service_role;

-- >>> supabase/sql_src/functions/route_discovery/refresh_route_options.sql

-- ============================================================================
-- Function: public.refresh_route_options
-- Feature: Route Discovery
-- Purpose: Rebuild direct through three-stop route options atomically.
-- Responsibilities: Bound graph expansion, reject cycles, enforce schedule compatibility, and version results.
-- Notes: Stored discovery is not live availability and never creates fare or baggage claims.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.refresh_route_options()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  ------------------------------------------------------------------
  -- Refresh state
  ------------------------------------------------------------------
  v_data_version UUID := gen_random_uuid();
  v_total_count  INTEGER := 0;
  v_counts       JSONB := '{}'::JSONB;
BEGIN
  -- STEP 01: Serialize refreshes and replace the prior version atomically.
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('public.refresh_route_options', 0)
  );
  DELETE FROM public.route_options;

  -- STEP 02: Expand eligible schedule paths to at most four legs (three stops).
  INSERT INTO public.route_options (
    origin_airport_id,
    destination_airport_id,
    stop_count,
    service_ids,
    flight_route_ids,
    origin_airport_ids,
    destination_airport_ids,
    connection_airport_ids,
    operating_airline_ids,
    marketing_airline_ids,
    departure_local_times,
    arrival_local_times,
    leg_duration_minutes,
    layover_minutes_by_connection,
    total_flight_minutes,
    layover_minutes,
    total_duration_minutes,
    departure_local_time,
    arrival_local_time,
    arrival_day_offset,
    valid_from,
    valid_to,
    days_of_week,
    confidence_score,
    data_version
  )
  WITH RECURSIVE route_paths AS (
    SELECT
      route.origin_airport_id,
      route.destination_airport_id,
      ARRAY[route.origin_airport_id, route.destination_airport_id]::UUID[] AS airport_path,
      ARRAY[service.id]::UUID[] AS service_ids,
      ARRAY[route.id]::UUID[] AS flight_route_ids,
      ARRAY[route.origin_airport_id]::UUID[] AS origin_airport_ids,
      ARRAY[route.destination_airport_id]::UUID[] AS destination_airport_ids,
      '{}'::UUID[] AS connection_airport_ids,
      ARRAY[service.operating_airline_id]::UUID[] AS operating_airline_ids,
      ARRAY[COALESCE(service.marketing_airline_id, service.operating_airline_id)]::UUID[] AS marketing_airline_ids,
      ARRAY[service.departure_local_time]::TIME[] AS departure_local_times,
      ARRAY[service.arrival_local_time]::TIME[] AS arrival_local_times,
      ARRAY[service.duration_minutes]::INTEGER[] AS leg_duration_minutes,
      '{}'::INTEGER[] AS layover_minutes_by_connection,
      service.duration_minutes AS total_flight_minutes,
      0 AS layover_minutes,
      service.duration_minutes AS total_duration_minutes,
      service.departure_local_time,
      service.arrival_local_time,
      service.arrival_day_offset::INTEGER AS arrival_day_offset,
      service.valid_from,
      service.valid_to,
      service.days_of_week,
      LEAST(route.confidence_score, service.confidence_score)::NUMERIC(4,3) AS confidence_score
    FROM public.flight_services service
    JOIN public.flight_routes route
      ON route.id = service.flight_route_id
    JOIN admin.data_sources source
      ON source.id = route.source_id
    WHERE route.status IN ('verified_active', 'likely_active', 'seasonal')
      AND (
        source.derived_data_allowed = TRUE
        OR source.source_type = 'development_fixture'
      )

    UNION ALL

    SELECT
      path.origin_airport_id,
      next_route.destination_airport_id,
      path.airport_path || next_route.destination_airport_id,
      path.service_ids || next_service.id,
      path.flight_route_ids || next_route.id,
      path.origin_airport_ids || next_route.origin_airport_id,
      path.destination_airport_ids || next_route.destination_airport_id,
      path.connection_airport_ids || next_route.origin_airport_id,
      path.operating_airline_ids || next_service.operating_airline_id,
      path.marketing_airline_ids || COALESCE(next_service.marketing_airline_id, next_service.operating_airline_id),
      path.departure_local_times || next_service.departure_local_time,
      path.arrival_local_times || next_service.arrival_local_time,
      path.leg_duration_minutes || next_service.duration_minutes,
      path.layover_minutes_by_connection || connection.layover_minutes,
      path.total_flight_minutes + next_service.duration_minutes,
      path.layover_minutes + connection.layover_minutes,
      path.total_duration_minutes + connection.layover_minutes + next_service.duration_minutes,
      path.departure_local_time,
      next_service.arrival_local_time,
      path.arrival_day_offset
        + CASE WHEN next_service.departure_local_time <= path.arrival_local_time THEN 1 ELSE 0 END
        + next_service.arrival_day_offset,
      GREATEST(path.valid_from, next_service.valid_from),
      LEAST(path.valid_to, next_service.valid_to),
      schedule_days.days_of_week,
      LEAST(path.confidence_score, next_route.confidence_score, next_service.confidence_score)::NUMERIC(4,3)
    FROM route_paths path
    JOIN public.flight_routes next_route
      ON next_route.origin_airport_id = path.destination_airport_id
    JOIN public.flight_services next_service
      ON next_service.flight_route_id = next_route.id
    JOIN admin.data_sources next_source
      ON next_source.id = next_route.source_id
    CROSS JOIN LATERAL (
      SELECT public.calculate_layover_minutes(
        path.arrival_local_time,
        path.arrival_day_offset::SMALLINT,
        next_service.departure_local_time
      ) AS layover_minutes
    ) connection
    CROSS JOIN LATERAL (
      SELECT ARRAY(
        SELECT day_value
        FROM UNNEST(path.days_of_week) day_value
        INTERSECT
        SELECT day_value
        FROM UNNEST(next_service.days_of_week) day_value
        ORDER BY day_value
      )::SMALLINT[] AS days_of_week
    ) schedule_days
    WHERE cardinality(path.service_ids) < 4
      AND next_route.status IN ('verified_active', 'likely_active', 'seasonal')
      AND (
        next_source.derived_data_allowed = TRUE
        OR next_source.source_type = 'development_fixture'
      )
      AND NOT (next_route.destination_airport_id = ANY(path.airport_path))
      AND next_route.destination_airport_id <> path.origin_airport_id
      AND GREATEST(path.valid_from, next_service.valid_from)
        <= LEAST(path.valid_to, next_service.valid_to)
      AND cardinality(schedule_days.days_of_week) > 0
      AND connection.layover_minutes BETWEEN 45 AND 1440
      AND path.total_duration_minutes + connection.layover_minutes + next_service.duration_minutes <= 10080
      AND path.arrival_day_offset
        + CASE WHEN next_service.departure_local_time <= path.arrival_local_time THEN 1 ELSE 0 END
        + next_service.arrival_day_offset <= 7
  ),
  ranked_paths AS (
    SELECT
      path.*,
      ROW_NUMBER() OVER (
        PARTITION BY path.origin_airport_id, path.destination_airport_id, cardinality(path.service_ids)
        ORDER BY path.total_duration_minutes, path.confidence_score DESC, path.service_ids::TEXT
      ) AS candidate_rank
    FROM route_paths path
  )
  SELECT
    path.origin_airport_id,
    path.destination_airport_id,
    (cardinality(path.service_ids) - 1)::SMALLINT,
    path.service_ids,
    path.flight_route_ids,
    path.origin_airport_ids,
    path.destination_airport_ids,
    path.connection_airport_ids,
    path.operating_airline_ids,
    path.marketing_airline_ids,
    path.departure_local_times,
    path.arrival_local_times,
    path.leg_duration_minutes,
    path.layover_minutes_by_connection,
    path.total_flight_minutes,
    path.layover_minutes,
    path.total_duration_minutes,
    path.departure_local_time,
    path.arrival_local_time,
    path.arrival_day_offset::SMALLINT,
    path.valid_from,
    path.valid_to,
    path.days_of_week,
    path.confidence_score,
    v_data_version
  FROM ranked_paths path
  WHERE path.candidate_rank <= 200;

  GET DIAGNOSTICS v_total_count = ROW_COUNT;

  -- STEP 03: Return versioned counts by stop depth for operational verification.
  SELECT COALESCE(
    jsonb_object_agg(stop_count::TEXT, option_count ORDER BY stop_count),
    '{}'::JSONB
  )
  INTO v_counts
  FROM (
    SELECT stop_count, COUNT(*) AS option_count
    FROM public.route_options
    GROUP BY stop_count
  ) counts;

  RETURN jsonb_build_object(
    'data_version', v_data_version,
    'counts_by_stop', v_counts,
    'total_count', v_total_count,
    'max_stops', 3
  );
END;
$$;

REVOKE ALL ON FUNCTION public.refresh_route_options() FROM public;
GRANT EXECUTE ON FUNCTION public.refresh_route_options() TO service_role;

-- >>> supabase/sql_src/functions/route_discovery/refresh_route_search_options.sql

-- ============================================================================
-- Function: private.refresh_route_search_options
-- Purpose: Rebuild the shared searchable route projection for one candidate version.
-- Responsibilities: Resolve identities, ordered codes, canonical paths, and display-safe prices.
-- ============================================================================

CREATE OR REPLACE FUNCTION private.refresh_route_search_options(p_publication_version_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
VOLATILE
SET search_path = ''
AS $$
DECLARE
  v_count INTEGER;
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.publication_versions version
    WHERE version.id = p_publication_version_id
      AND version.status = 'building'
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'ERR_PUBLICATION_VERSION_INVALID';
  END IF;

  DELETE FROM public.route_search_options
  WHERE publication_version_id = p_publication_version_id;

  INSERT INTO public.route_search_options (
    id,
    publication_version_id,
    origin_city_id,
    origin_city_slug,
    destination_city_id,
    destination_city_slug,
    origin_airport_id,
    origin_airport_iata,
    destination_airport_id,
    destination_airport_iata,
    stop_count,
    connection_airport_ids,
    connection_airport_iatas,
    operating_airline_ids,
    operating_airline_iatas,
    departure_local_time,
    arrival_local_time,
    arrival_day_offset,
    days_of_week,
    valid_from,
    valid_to,
    total_flight_minutes,
    layover_minutes,
    maximum_layover_minutes,
    total_duration_minutes,
    confidence_score,
    route_path,
    price_state,
    price_min,
    price_max,
    currency_code,
    price_valid_until
  )
  SELECT
    option.id,
    p_publication_version_id,
    origin_city.id,
    origin_city.slug,
    destination_city.id,
    destination_city.slug,
    origin_airport.id,
    origin_airport.iata,
    destination_airport.id,
    destination_airport.iata,
    option.stop_count,
    option.connection_airport_ids,
    ARRAY(
      SELECT airport.iata
      FROM unnest(option.connection_airport_ids) WITH ORDINALITY item(id, position)
      JOIN public.airports airport
        ON airport.id = item.id
      ORDER BY item.position
    ),
    option.operating_airline_ids,
    ARRAY(
      SELECT airline.iata
      FROM unnest(option.operating_airline_ids) WITH ORDINALITY item(id, position)
      JOIN public.airlines airline
        ON airline.id = item.id
      ORDER BY item.position
    ),
    option.departure_local_time,
    option.arrival_local_time,
    option.arrival_day_offset,
    option.days_of_week,
    option.valid_from,
    option.valid_to,
    option.total_flight_minutes,
    option.layover_minutes,
    COALESCE((SELECT max(minutes) FROM unnest(option.layover_minutes_by_connection) minutes), 0),
    option.total_duration_minutes,
    option.confidence_score,
    format('/flights/%s-to-%s', origin_city.slug, destination_city.slug),
    COALESCE(price.state, 'missing'),
    price.price_min,
    price.price_max,
    price.currency_code,
    price.valid_until
  FROM public.route_options option
  JOIN public.airports origin_airport
    ON origin_airport.id = option.origin_airport_id
  JOIN public.cities origin_city
    ON origin_city.id = origin_airport.city_id
  JOIN public.airports destination_airport
    ON destination_airport.id = option.destination_airport_id
  JOIN public.cities destination_city
    ON destination_city.id = destination_airport.city_id
  LEFT JOIN LATERAL (
    SELECT
      'available'::TEXT AS state,
      estimate.price_min,
      estimate.price_max,
      estimate.currency_code,
      estimate.valid_until
    FROM public.route_price_estimates estimate
    JOIN admin.data_sources source
      ON source.id = estimate.source_id
    WHERE estimate.origin_city_id = origin_city.id
      AND estimate.destination_city_id = destination_city.id
      AND estimate.status = 'published'
      AND estimate.valid_until > now()
      AND source.production_display_allowed = TRUE
      AND source.derived_data_allowed = TRUE
      AND (
        source.rights_effective_at IS NULL
        OR now() BETWEEN source.rights_effective_at AND source.rights_expires_at
      )
    ORDER BY
      estimate.confidence_score DESC,
      estimate.last_verified_at DESC,
      estimate.id
    LIMIT 1
  ) price ON TRUE;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION private.refresh_route_search_options(UUID)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.refresh_route_search_options(UUID) TO service_role;

-- >>> supabase/sql_src/functions/route_discovery/rpc_search_route_options_v2.sql

-- ============================================================================
-- Function: public.rpc_search_route_options_v2
-- Purpose: Search one shared route projection for every page consumer.
-- Responsibilities: Validate scope/filters, apply deterministic keyset pagination, and return facets.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.rpc_search_route_options_v2(p_input JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SET search_path = ''
AS $$
DECLARE
  v_version_id UUID;
  v_scope_type TEXT;
  v_scope_key TEXT;
  v_scope_from TEXT;
  v_scope_to TEXT;
  v_filters JSONB;
  v_max_stops INTEGER;
  v_airlines TEXT[];
  v_connections TEXT[];
  v_max_duration INTEGER;
  v_max_layover INTEGER;
  v_cabin TEXT;
  v_price_max NUMERIC;
  v_currency TEXT;
  v_page_size INTEGER;
  v_cursor_stops INTEGER;
  v_cursor_duration INTEGER;
  v_cursor_confidence NUMERIC;
  v_cursor_id UUID;
  v_result JSONB;
BEGIN
  IF jsonb_typeof(p_input) IS DISTINCT FROM 'object'
    OR p_input - ARRAY['scope', 'filters', 'page_size', 'after'] <> '{}'::JSONB
    OR jsonb_typeof(p_input->'scope') <> 'object'
    OR jsonb_typeof(COALESCE(p_input->'filters', '{}'::JSONB)) <> 'object'
    OR COALESCE(p_input->'filters', '{}'::JSONB)
      - ARRAY[
        'max_stops',
        'airlines',
        'connection_airports',
        'max_duration_minutes',
        'max_layover_minutes',
        'cabin',
        'price_max',
        'currency'
      ] <> '{}'::JSONB
  THEN
    RETURN private.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
  END IF;

  v_scope_type := p_input #>> '{scope,type}';
  v_scope_key := p_input #>> '{scope,key}';
  v_scope_from := p_input #>> '{scope,from}';
  v_scope_to := p_input #>> '{scope,to}';
  v_filters := COALESCE(p_input->'filters', '{}'::JSONB);
  v_max_stops := COALESCE((v_filters->>'max_stops')::INTEGER, 3);
  v_max_duration := NULLIF(v_filters->>'max_duration_minutes', '')::INTEGER;
  v_max_layover := NULLIF(v_filters->>'max_layover_minutes', '')::INTEGER;
  v_cabin := COALESCE(NULLIF(v_filters->>'cabin', ''), 'any');
  v_price_max := NULLIF(v_filters->>'price_max', '')::NUMERIC;
  v_currency := upper(NULLIF(btrim(COALESCE(v_filters->>'currency', '')), ''));
  v_page_size := COALESCE((p_input->>'page_size')::INTEGER, 20);

  IF v_scope_type IS NULL
    OR v_scope_type NOT IN ('global', 'origin_city', 'origin_airport', 'city_pair')
    OR (
      v_scope_type = 'global'
      AND (p_input->'scope') - ARRAY['type'] <> '{}'::JSONB
    )
    OR (
      v_scope_type IN ('origin_city', 'origin_airport')
      AND (
        (p_input->'scope') - ARRAY['type', 'key'] <> '{}'::JSONB
        OR NULLIF(btrim(COALESCE(v_scope_key, '')), '') IS NULL
      )
    )
    OR (
      v_scope_type = 'city_pair'
      AND (
        (p_input->'scope') - ARRAY['type', 'from', 'to'] <> '{}'::JSONB
        OR NULLIF(btrim(COALESCE(v_scope_from, '')), '') IS NULL
        OR NULLIF(btrim(COALESCE(v_scope_to, '')), '') IS NULL
        OR v_scope_from = v_scope_to
      )
    )
    OR (v_scope_type = 'origin_airport' AND upper(v_scope_key) !~ '^[A-Z0-9]{3}$')
    OR v_max_stops NOT BETWEEN 0 AND 3
    OR v_page_size NOT BETWEEN 1 AND 100
    OR (v_max_duration IS NOT NULL AND v_max_duration NOT BETWEEN 1 AND 10080)
    OR (v_max_layover IS NOT NULL AND v_max_layover NOT BETWEEN 1 AND 1440)
    OR (v_price_max IS NOT NULL AND v_price_max < 0)
    OR ((v_price_max IS NULL) <> (v_currency IS NULL))
    OR (v_currency IS NOT NULL AND v_currency !~ '^[A-Z]{3}$')
    OR v_cabin NOT IN ('any', 'economy', 'premium_economy', 'business', 'first')
    OR (v_filters ? 'airlines' AND jsonb_typeof(v_filters->'airlines') <> 'array')
    OR (
      v_filters ? 'connection_airports'
      AND jsonb_typeof(v_filters->'connection_airports') <> 'array'
    )
  THEN
    RETURN private.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
  END IF;

  IF v_filters ? 'airlines' THEN
    SELECT COALESCE(array_agg(DISTINCT upper(value)), '{}'::TEXT[])
    INTO v_airlines
    FROM jsonb_array_elements_text(v_filters->'airlines');
  ELSE
    v_airlines := '{}'::TEXT[];
  END IF;

  IF v_filters ? 'connection_airports' THEN
    SELECT COALESCE(array_agg(DISTINCT upper(value)), '{}'::TEXT[])
    INTO v_connections
    FROM jsonb_array_elements_text(v_filters->'connection_airports');
  ELSE
    v_connections := '{}'::TEXT[];
  END IF;

  IF EXISTS (SELECT 1 FROM unnest(v_airlines) code WHERE code !~ '^[A-Z0-9]{2}$')
    OR EXISTS (SELECT 1 FROM unnest(v_connections) code WHERE code !~ '^[A-Z0-9]{3}$')
  THEN
    RETURN private.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route code filter.');
  END IF;

  SELECT version.id
  INTO v_version_id
  FROM public.publication_versions version
  WHERE version.is_current = TRUE;

  IF v_version_id IS NULL THEN
    RETURN private.build_rpc_error('[]'::JSONB, 'ERR_ROUTE_DISCOVERY_UNAVAILABLE', 'No route publication is available.');
  END IF;

  IF p_input->>'after' IS NOT NULL THEN
    BEGIN
      v_cursor_stops := split_part(p_input->>'after', ':', 1)::INTEGER;
      v_cursor_duration := split_part(p_input->>'after', ':', 2)::INTEGER;
      v_cursor_confidence := split_part(p_input->>'after', ':', 3)::NUMERIC;
      v_cursor_id := split_part(p_input->>'after', ':', 4)::UUID;
    EXCEPTION WHEN OTHERS THEN
      RETURN private.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route cursor.');
    END;
  END IF;

  WITH filtered AS MATERIALIZED (
    SELECT option.*
    FROM public.route_search_options option
    WHERE option.publication_version_id = v_version_id
      AND option.stop_count <= v_max_stops
      AND (v_scope_type <> 'origin_city' OR option.origin_city_slug = v_scope_key)
      AND (v_scope_type <> 'origin_airport' OR option.origin_airport_iata = upper(v_scope_key))
      AND (v_scope_type <> 'city_pair' OR (option.origin_city_slug = v_scope_from AND option.destination_city_slug = v_scope_to))
      AND (v_max_duration IS NULL OR option.total_duration_minutes <= v_max_duration)
      AND (v_max_layover IS NULL OR option.maximum_layover_minutes <= v_max_layover)
      AND (cardinality(v_airlines) = 0 OR option.operating_airline_iatas && v_airlines)
      AND (cardinality(v_connections) = 0 OR option.connection_airport_iatas && v_connections)
      AND (v_price_max IS NULL OR (option.price_state = 'available' AND option.price_min <= v_price_max AND option.currency_code = v_currency))
  ),
  page AS (
    SELECT filtered.*
    FROM filtered
    WHERE v_cursor_id IS NULL
      OR (filtered.stop_count, filtered.total_duration_minutes, -filtered.confidence_score, filtered.id)
        > (v_cursor_stops, v_cursor_duration, -v_cursor_confidence, v_cursor_id)
    ORDER BY filtered.stop_count, filtered.total_duration_minutes, filtered.confidence_score DESC, filtered.id
    LIMIT v_page_size
  )
  SELECT jsonb_build_object(
    'data', COALESCE((SELECT jsonb_agg(jsonb_build_object(
      'id', page.id,
      'from', page.origin_airport_iata,
      'to', page.destination_airport_iata,
      'stops', page.stop_count,
      'connection_airports', to_jsonb(page.connection_airport_iatas),
      'operating_airlines', to_jsonb(page.operating_airline_iatas),
      'total_flight_minutes', page.total_flight_minutes,
      'layover_minutes', page.layover_minutes,
      'total_duration_minutes', page.total_duration_minutes,
      'schedule', jsonb_build_object('departure_local_time', page.departure_local_time, 'arrival_local_time', page.arrival_local_time, 'arrival_day_offset', page.arrival_day_offset, 'days_of_week', page.days_of_week, 'valid_from', page.valid_from, 'valid_to', page.valid_to),
      'route_path', page.route_path,
      'price', CASE WHEN page.price_state = 'available' THEN jsonb_build_object('state','available','price_min',page.price_min,'price_max',page.price_max,'currency_code',page.currency_code,'valid_until',page.price_valid_until) ELSE jsonb_build_object('state','unavailable','reason',page.price_state,'estimate',NULL) END,
      'self_transfer', 'unknown', 'through_baggage', 'unknown', 'fare_rules', 'unknown', 'live_availability', 'unknown'
    ) ORDER BY page.stop_count, page.total_duration_minutes, page.confidence_score DESC, page.id) FROM page), '[]'::JSONB),
    'meta', jsonb_build_object(
      'data_version', v_version_id,
      'total', (SELECT count(*) FROM filtered),
      'page_size', v_page_size,
      'next_cursor', (SELECT format('%s:%s:%s:%s', page.stop_count, page.total_duration_minutes, page.confidence_score, page.id) FROM page ORDER BY page.stop_count DESC, page.total_duration_minutes DESC, page.confidence_score, page.id DESC LIMIT 1),
      'facets', jsonb_build_object(
        'stops', (SELECT COALESCE(jsonb_agg(to_jsonb(facet) ORDER BY facet.value), '[]'::JSONB) FROM (SELECT stop_count value, count(*)::INTEGER count FROM filtered GROUP BY stop_count) facet),
        'airlines', (SELECT COALESCE(jsonb_agg(to_jsonb(facet) ORDER BY facet.value), '[]'::JSONB) FROM (SELECT code value, count(*)::INTEGER count FROM filtered CROSS JOIN LATERAL unnest(operating_airline_iatas) code GROUP BY code) facet),
        'connections', (SELECT COALESCE(jsonb_agg(to_jsonb(facet) ORDER BY facet.value), '[]'::JSONB) FROM (SELECT code value, count(*)::INTEGER count FROM filtered CROSS JOIN LATERAL unnest(connection_airport_iatas) code GROUP BY code) facet)
      )
    ),
    'error', NULL
  )
  INTO v_result;

  RETURN v_result;
EXCEPTION
  WHEN invalid_text_representation OR numeric_value_out_of_range THEN
    RETURN private.build_rpc_error(
      '[]'::JSONB,
      'ERR_INVALID_REQUEST',
      'Invalid route search request.'
    );
END;
$$;

REVOKE ALL ON FUNCTION public.rpc_search_route_options_v2(JSONB)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_search_route_options_v2(JSONB) TO service_role;
