-- ============================================================================
-- Migration: 20260714080900_pseo_functions.sql
-- Source of truth: supabase/sql_src
-- Feature: pSEO functions
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/functions/pseo/city/build_city_page_payload.sql

-- ============================================================================
-- Function: admin.build_city_page_payload
-- Purpose: Compose one public-safe City page payload for a publication candidate.
-- Responsibilities: Allowlist city identity, content, routes, and lifecycle metadata.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.build_city_page_payload(p_input JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_slug      TEXT := lower(p_input->>'city_slug');
  v_locale    TEXT := COALESCE(NULLIF(p_input->>'locale', ''), 'en-GB');
  v_direction TEXT := COALESCE(NULLIF(p_input->>'route_direction', ''), 'outbound');
  v_version   UUID := (p_input->>'publication_version_id')::UUID;
  v_page      public.city_pages%ROWTYPE;
  v_city      public.cities%ROWTYPE;
  v_registry  public.pseo_pages%ROWTYPE;
BEGIN
  SELECT page.*
  INTO v_page
  FROM public.city_pages AS page
  JOIN public.pseo_pages AS registry
    ON registry.id = page.pseo_page_id
  WHERE registry.entity_key = v_slug
    AND page.locale = v_locale
    AND page.route_direction = v_direction;

  IF v_page.id IS NULL THEN
    RETURN admin.build_rpc_error(NULL, 'ERR_NOT_FOUND', 'City page not found.');
  END IF;

  SELECT * INTO v_city FROM public.cities WHERE id = v_page.city_id;
  SELECT * INTO v_registry FROM public.pseo_pages WHERE id = v_page.pseo_page_id;

  RETURN jsonb_build_object(
    'data', jsonb_build_object(
      'city', jsonb_build_object(
        'name', v_city.name,
        'slug', v_city.slug,
        'iata_code', v_city.iata_code,
        'timezone', v_city.timezone,
        'currency_code', v_city.currency_code,
        'primary_language', v_city.primary_language
      ),
      'content', v_page.content,
      'routes', COALESCE((
        SELECT jsonb_agg(jsonb_build_object(
          'from', option.origin_airport_iata,
          'to', option.destination_airport_iata,
          'airline', option.provider_airline_iata,
          'observed_amount', option.observed_amount,
          'currency_code', option.currency_code,
          'valid_until', option.observation_valid_until,
          'route_path', option.route_path
        ) ORDER BY option.confidence_score DESC, option.observed_amount NULLS LAST)
        FROM public.flight_route_options AS option
        WHERE option.publication_version_id = v_version
          AND (
            (v_direction = 'outbound' AND option.origin_city_id = v_city.id)
            OR (v_direction = 'inbound' AND option.destination_city_id = v_city.id)
          )
      ), '[]'::JSONB)
    ),
    'meta', jsonb_build_object(
      'canonical_path', v_registry.canonical_path,
      'is_indexable', v_registry.is_indexable,
      'noindex_reason', v_registry.noindex_reason,
      'data_version', 'v_' || md5(v_version::TEXT),
      'source_freshness_at', v_registry.source_freshness_at
    ),
    'error', NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION admin.build_city_page_payload(JSONB)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.build_city_page_payload(JSONB) TO service_role;

-- >>> supabase/sql_src/functions/pseo/airport/build_airport_page_payload.sql

-- ============================================================================
-- Function: admin.build_airport_page_payload
-- Purpose: Compose one public-safe Airport page payload for a publication candidate.
-- Responsibilities: Allowlist airport identity, content, routes, and lifecycle metadata.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.build_airport_page_payload(p_input JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_iata     TEXT := upper(p_input->>'airport_iata');
  v_locale   TEXT := COALESCE(NULLIF(p_input->>'locale', ''), 'en-GB');
  v_version  UUID := (p_input->>'publication_version_id')::UUID;
  v_page     public.airport_pages%ROWTYPE;
  v_airport  public.airports%ROWTYPE;
  v_registry public.pseo_pages%ROWTYPE;
BEGIN
  SELECT page.*
  INTO v_page
  FROM public.airport_pages AS page
  JOIN public.airports AS airport
    ON airport.id = page.airport_id
  WHERE airport.iata = v_iata
    AND page.locale = v_locale;

  IF v_page.id IS NULL THEN
    RETURN admin.build_rpc_error(NULL, 'ERR_NOT_FOUND', 'Airport page not found.');
  END IF;

  SELECT * INTO v_airport FROM public.airports WHERE id = v_page.airport_id;
  SELECT * INTO v_registry FROM public.pseo_pages WHERE id = v_page.pseo_page_id;

  RETURN jsonb_build_object(
    'data', jsonb_build_object(
      'airport', jsonb_build_object(
        'iata', v_airport.iata,
        'icao', v_airport.icao,
        'name', v_airport.name,
        'slug', v_airport.slug,
        'image_path', v_airport.image_path,
        'timezone', v_airport.timezone
      ),
      'content', v_page.content,
      'routes', COALESCE((
        SELECT jsonb_agg(jsonb_build_object(
          'from', option.origin_airport_iata,
          'to', option.destination_airport_iata,
          'airline', option.provider_airline_iata,
          'observed_amount', option.observed_amount,
          'currency_code', option.currency_code,
          'valid_until', option.observation_valid_until,
          'route_path', option.route_path
        ) ORDER BY option.confidence_score DESC, option.observed_amount NULLS LAST)
        FROM public.flight_route_options AS option
        WHERE option.publication_version_id = v_version
          AND (
            option.origin_airport_id = v_airport.id
            OR option.destination_airport_id = v_airport.id
          )
      ), '[]'::JSONB)
    ),
    'meta', jsonb_build_object(
      'canonical_path', v_registry.canonical_path,
      'is_indexable', v_registry.is_indexable,
      'noindex_reason', v_registry.noindex_reason,
      'data_version', 'v_' || md5(v_version::TEXT),
      'source_freshness_at', v_registry.source_freshness_at
    ),
    'error', NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION admin.build_airport_page_payload(JSONB)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.build_airport_page_payload(JSONB) TO service_role;

-- >>> supabase/sql_src/functions/pseo/shared/rpc_get_flight_affiliate_handoff.sql

-- ============================================================================
-- Function: public.rpc_get_flight_affiliate_handoff
-- Purpose: Resolve an opaque public observation reference to an allowlisted partner URL.
-- Responsibilities: Enforce freshness, provider allowlisting, and server-owned destinations.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.rpc_get_flight_affiliate_handoff(p_observation_ref TEXT)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
  SELECT CASE
    WHEN observation.public_reference IS NULL THEN
      jsonb_build_object(
        'data', NULL,
        'error', jsonb_build_object('code', 'ERR_HANDOFF_UNAVAILABLE')
      )
    ELSE
      jsonb_build_object(
        'data', jsonb_build_object(
          'url', 'https://www.aviasales.com' || observation.affiliate_path,
          'expires_at', observation.valid_until,
          'disclosure', 'Tripways may earn a commission if you book through this link. Final price and availability are confirmed by Aviasales.'
        ),
        'error', NULL
      )
  END
  FROM (SELECT p_observation_ref AS requested_reference) AS input
  LEFT JOIN public.flight_route_prices AS observation
    ON observation.public_reference = input.requested_reference
   AND observation.status = 'published'
   AND observation.valid_until > now()
   AND observation.affiliate_path IS NOT NULL
   AND observation.provider_code = 'travelpayouts';
$$;

REVOKE ALL ON FUNCTION public.rpc_get_flight_affiliate_handoff(TEXT)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_get_flight_affiliate_handoff(TEXT) TO service_role;

-- >>> supabase/sql_src/functions/pseo/homepage/rpc_get_homepage_statistics.sql

-- ============================================================================
-- Function: public.rpc_get_homepage_statistics
-- Purpose: Return current canonical route coverage for the product homepage.
-- Responsibilities: Aggregate bounded data points directly from the current publication.
-- Notes: Homepage copy and layout remain frontend-owned.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.rpc_get_homepage_statistics()
RETURNS JSONB
LANGUAGE sql
STABLE
SET search_path = ''
AS $$
  SELECT jsonb_build_object(
    'data', jsonb_build_object(
      'origin_city_count', count(DISTINCT option.origin_city_id)::INTEGER,
      'origin_airport_count', count(DISTINCT option.origin_airport_id)::INTEGER,
      'published_direct_route_count', count(DISTINCT option.route_path)::INTEGER
    ),
    'meta', jsonb_build_object(
      'data_version', 'v_' || md5(version.id::TEXT),
      'generated_at', version.published_at
    ),
    'error', NULL
  )
  FROM public.publication_versions AS version
  LEFT JOIN public.flight_route_options AS option
    ON option.publication_version_id = version.id
  WHERE version.is_current = TRUE
    AND version.status = 'published'
  GROUP BY version.id, version.published_at;
$$;

REVOKE ALL ON FUNCTION public.rpc_get_homepage_statistics()
FROM public;
GRANT EXECUTE ON FUNCTION public.rpc_get_homepage_statistics()
TO anon, authenticated, service_role;

-- >>> supabase/sql_src/functions/pseo/route/build_route_page_payload.sql

-- ============================================================================
-- Function: admin.build_route_page_payload
-- Purpose: Compose one public-safe Route page payload for a publication candidate.
-- Responsibilities: Allowlist route identity, observations, options, and lifecycle metadata.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.build_route_page_payload(p_input JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SET search_path = ''
AS $$
DECLARE
  v_locale   TEXT := COALESCE(NULLIF(p_input->>'locale', ''), 'en-GB');
  v_page     public.route_pages%ROWTYPE;
  v_registry public.pseo_pages%ROWTYPE;
  v_version  UUID := (p_input->>'publication_version_id')::UUID;
BEGIN
  SELECT page.*
  INTO v_page
  FROM public.route_pages AS page
  JOIN public.pseo_pages AS registry
    ON registry.id = page.pseo_page_id
  WHERE registry.entity_key = lower(p_input->>'route_slug')
    AND page.locale = v_locale;

  IF v_page.id IS NULL THEN
    RETURN admin.build_rpc_error(NULL, 'ERR_NOT_FOUND', 'Route page not found.');
  END IF;

  SELECT * INTO v_registry FROM public.pseo_pages WHERE id = v_page.pseo_page_id;

  RETURN jsonb_build_object(
    'data', jsonb_build_object(
      'route', jsonb_build_object(
        'origin', (
          SELECT jsonb_build_object(
            'name', city.name,
            'slug', city.slug,
            'iata_code', city.iata_code
          )
          FROM public.cities AS city
          WHERE city.id = v_page.origin_city_id
        ),
        'destination', (
          SELECT jsonb_build_object(
            'name', city.name,
            'slug', city.slug,
            'iata_code', city.iata_code
          )
          FROM public.cities AS city
          WHERE city.id = v_page.destination_city_id
        )
      ),
      'content', v_page.content,
      'route_options', COALESCE((
        SELECT jsonb_agg(jsonb_build_object(
          'from', option.origin_airport_iata,
          'to', option.destination_airport_iata,
          'airline', option.provider_airline_iata,
          'evidence_type', option.evidence_type,
          'confidence_score', option.confidence_score
        ) ORDER BY option.confidence_score DESC)
        FROM public.flight_route_options AS option
        WHERE option.publication_version_id = v_version
          AND option.origin_city_id = v_page.origin_city_id
          AND option.destination_city_id = v_page.destination_city_id
      ), '[]'::JSONB),
      'observations', COALESCE((
        SELECT jsonb_agg(jsonb_build_object(
          'observation_ref', item.public_reference,
          'observed_amount', item.observed_amount,
          'currency_code', item.currency_code,
          'departure_date', item.departure_date,
          'direct', item.direct,
          'observed_at', item.observed_at,
          'valid_until', item.valid_until
        ) ORDER BY item.observed_amount NULLS LAST, item.observed_at DESC)
        FROM public.flight_route_prices AS item
        JOIN admin.data_sources AS source
          ON source.id = item.source_id
        WHERE item.origin_city_id = v_page.origin_city_id
          AND item.destination_city_id = v_page.destination_city_id
          AND item.status = 'published'
          AND item.valid_until > now()
          AND source.production_display_allowed
      ), '[]'::JSONB),
      'disclosure', 'Cached observations are not live offers; final price and availability are confirmed by the booking partner.'
    ),
    'meta', jsonb_build_object(
      'canonical_path', v_registry.canonical_path,
      'is_indexable', v_registry.is_indexable,
      'noindex_reason', v_registry.noindex_reason,
      'data_version', 'v_' || md5(v_version::TEXT),
      'source_freshness_at', v_registry.source_freshness_at
    ),
    'error', NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION admin.build_route_page_payload(JSONB)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.build_route_page_payload(JSONB) TO service_role;

-- >>> supabase/sql_src/functions/pseo/shared/rpc_get_sitemap.sql

-- ============================================================================
-- Function: public.rpc_get_sitemap
-- Purpose: Return the current set of indexable canonical pSEO URLs.
-- Responsibilities: Apply publication and locale filters at the database boundary.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.rpc_get_sitemap(p_input JSONB DEFAULT '{}'::JSONB)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
  SELECT jsonb_build_object(
    'data', COALESCE(
      jsonb_agg(
        jsonb_build_object(
          'path', page.canonical_path,
          'locale', page.locale,
          'page_type', page.page_type,
          'last_modified', page.content_updated_at
        )
        ORDER BY page.canonical_path
      ),
      '[]'::JSONB
    ),
    'meta', jsonb_build_object('only_indexable', TRUE),
    'error', NULL
  )
  FROM public.pseo_pages AS page
  WHERE page.status = 'published'
    AND page.is_indexable
    AND page.noindex_reason IS NULL
    AND (
      NOT p_input ? 'locale'
      OR page.locale = p_input->>'locale'
    );
$$;

REVOKE ALL ON FUNCTION public.rpc_get_sitemap(JSONB)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_get_sitemap(JSONB) TO service_role;

-- >>> supabase/sql_src/functions/pseo/shared/refresh_page_read_models.sql

-- ============================================================================
-- Function: admin.refresh_page_read_models
-- Purpose: Materialize all page-specific single-load read models for one candidate version.
-- Responsibilities: Compose bounded page payloads outside the public request path.
-- Notes: Private builders compose bounded modules only during publication.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.refresh_page_read_models(p_publication_version_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SET search_path = ''
AS $$
DECLARE
  v_city_count INTEGER;
  v_airport_count INTEGER;
  v_route_count INTEGER;
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.publication_versions version
    WHERE version.id = p_publication_version_id
      AND version.status = 'building'
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'ERR_PUBLICATION_VERSION_INVALID';
  END IF;

  DELETE FROM public.city_page_read_models WHERE publication_version_id = p_publication_version_id;
  DELETE FROM public.airport_page_read_models WHERE publication_version_id = p_publication_version_id;
  DELETE FROM public.route_page_read_models WHERE publication_version_id = p_publication_version_id;

  INSERT INTO public.city_page_read_models (
    publication_version_id,
    city_id,
    locale,
    canonical_slug,
    payload,
    metadata
  )
  SELECT
    p_publication_version_id,
    city_page.city_id,
    city_page.locale,
    registry.entity_key,
    built.response->'data',
    built.response->'meta'
  FROM public.city_pages city_page
  JOIN public.pseo_pages AS registry ON registry.id = city_page.pseo_page_id
  CROSS JOIN LATERAL (
    SELECT admin.build_city_page_payload(jsonb_build_object(
      'city_slug', registry.entity_key,
      'locale', city_page.locale,
      'route_direction', city_page.route_direction,
      'destination_limit', 20,
      'publication_version_id', p_publication_version_id
    )) AS response
  ) AS built
  WHERE city_page.route_direction = 'outbound'
    AND registry.status <> 'archived';
  GET DIAGNOSTICS v_city_count = ROW_COUNT;

  INSERT INTO public.airport_page_read_models (
    publication_version_id,
    airport_id,
    locale,
    airport_iata,
    payload,
    metadata
  )
  SELECT
    p_publication_version_id,
    airport_page.airport_id,
    airport_page.locale,
    airport.iata,
    built.response->'data',
    built.response->'meta'
  FROM public.airport_pages airport_page
  JOIN public.airports airport
    ON airport.id = airport_page.airport_id
  JOIN public.pseo_pages AS registry ON registry.id = airport_page.pseo_page_id
  CROSS JOIN LATERAL (
    SELECT admin.build_airport_page_payload(jsonb_build_object(
      'airport_iata', airport.iata,
      'locale', airport_page.locale,
      'publication_version_id', p_publication_version_id
    )) AS response
  ) AS built
  WHERE registry.status <> 'archived';
  GET DIAGNOSTICS v_airport_count = ROW_COUNT;

  INSERT INTO public.route_page_read_models (
    publication_version_id,
    route_page_id,
    locale,
    canonical_slug,
    payload,
    metadata
  )
  SELECT
    p_publication_version_id,
    route_page.id,
    route_page.locale,
    registry.entity_key,
    built.response->'data',
    built.response->'meta'
  FROM public.route_pages route_page
  JOIN public.pseo_pages AS registry ON registry.id = route_page.pseo_page_id
  CROSS JOIN LATERAL (
    SELECT admin.build_route_page_payload(jsonb_build_object(
      'route_slug', registry.entity_key,
      'locale', route_page.locale,
      'publication_version_id', p_publication_version_id
    )) AS response
  ) AS built
  WHERE registry.status <> 'archived';
  GET DIAGNOSTICS v_route_count = ROW_COUNT;

  RETURN jsonb_build_object(
    'city', v_city_count,
    'airport', v_airport_count,
    'route', v_route_count
  );
END;
$$;

REVOKE ALL ON FUNCTION admin.refresh_page_read_models(UUID)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.refresh_page_read_models(UUID) TO service_role;

-- >>> supabase/sql_src/functions/pseo/shared/publish_read_model_version.sql

-- ============================================================================
-- Function: public.publish_read_model_version
-- Purpose: Atomically build and publish one complete shared read-model version.
-- Responsibilities: Refresh route search and all page models before flipping the current marker.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.publish_read_model_version(p_source_type TEXT DEFAULT 'development_fixture')
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SET search_path = ''
AS $$
DECLARE
  v_version_id UUID;
  v_route_count INTEGER;
  v_page_counts JSONB;
BEGIN
  IF p_source_type NOT IN ('production', 'staging', 'development_fixture') THEN
    RETURN admin.build_rpc_error(NULL, 'ERR_INVALID_REQUEST', 'Invalid publication source type.');
  END IF;

  -- STEP 01: Serialize publishers so two candidates cannot race the current marker.
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('tripways:read-model-publication', 0)
  );

  INSERT INTO public.publication_versions (source_type)
  VALUES (p_source_type)
  RETURNING id
  INTO v_version_id;

  -- STEP 02: Keep candidate failures in a subtransaction and preserve the current version.
  BEGIN
    v_route_count := admin.refresh_route_search_options(v_version_id);

    -- STEP 02A: Derive both constrained lifecycle fields in one registry update.
    WITH page_eligibility AS (
      SELECT
        registry.id,
        p_source_type = 'production'
        AND registry.status = 'published'
        AND CASE
        WHEN registry.page_type = 'city' THEN EXISTS (
          SELECT 1
          FROM public.city_pages AS content
          JOIN public.flight_route_options AS route
           ON route.publication_version_id = v_version_id
           AND route.origin_city_id = content.city_id
          WHERE content.pseo_page_id = registry.id
            AND content.content_reviewed_at IS NOT NULL
        )
        WHEN registry.page_type = 'airport' THEN EXISTS (
          SELECT 1
          FROM public.airport_pages AS content
          JOIN public.flight_route_options AS route
           ON route.publication_version_id = v_version_id
           AND route.origin_airport_id = content.airport_id
          WHERE content.pseo_page_id = registry.id
            AND content.content_reviewed_at IS NOT NULL
        )
        WHEN registry.page_type = 'city_route' THEN EXISTS (
          SELECT 1
          FROM public.route_pages AS content
          JOIN public.flight_route_options AS route
            ON route.publication_version_id = v_version_id
           AND route.origin_city_id = content.origin_city_id
           AND route.destination_city_id = content.destination_city_id
          WHERE content.pseo_page_id = registry.id
            AND content.content_reviewed_at IS NOT NULL
        )
        ELSE FALSE
        END AS is_eligible
      FROM public.pseo_pages AS registry
    )
    UPDATE public.pseo_pages AS registry
    SET
      is_indexable = eligibility.is_eligible,
      noindex_reason = CASE
        WHEN eligibility.is_eligible THEN NULL
        WHEN p_source_type = 'development_fixture' THEN 'development_fixture'
        WHEN p_source_type = 'staging' THEN 'staging_environment'
        WHEN registry.status <> 'published' THEN 'not_published'
        WHEN registry.page_type IN ('city', 'airport', 'city_route') THEN 'source_not_seo_eligible'
        ELSE COALESCE(registry.noindex_reason, 'unsupported_page_type')
      END,
      data_version = v_version_id,
      generated_at = now()
    FROM page_eligibility AS eligibility
    WHERE eligibility.id = registry.id;

    v_page_counts := admin.refresh_page_read_models(v_version_id);

    IF v_route_count = 0 THEN
      RAISE EXCEPTION USING
        ERRCODE = '23514',
        MESSAGE = 'ERR_PUBLICATION_INCOMPLETE';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      UPDATE public.publication_versions
      SET
        status = 'failed',
        failure_code = CASE
          WHEN SQLERRM ~ '^ERR_[A-Z0-9_]+$' THEN SQLERRM
          ELSE 'ERR_PUBLICATION_FAILED'
        END
      WHERE id = v_version_id;

      RETURN admin.build_rpc_error(
        NULL,
        'ERR_PUBLICATION_FAILED',
        'Read-model publication failed.'
      );
  END;

  -- STEP 03: Flip all page and search readers to the complete candidate atomically.
  UPDATE public.publication_versions
  SET
    is_current = FALSE,
    status = 'retired'
  WHERE is_current = TRUE;

  UPDATE public.publication_versions
  SET
    status = 'published',
    is_current = TRUE,
    published_at = now()
  WHERE id = v_version_id;

  RETURN jsonb_build_object(
    'data', jsonb_build_object(
      'data_version', v_version_id,
      'route_options', v_route_count,
      'pages', v_page_counts
    ),
    'meta', jsonb_build_object('data_version', v_version_id, 'published_at', now()),
    'error', NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION public.publish_read_model_version(TEXT)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.publish_read_model_version(TEXT) TO service_role;

-- >>> supabase/sql_src/functions/pseo/shared/rpc_get_page.sql

-- ============================================================================
-- Function: public.rpc_get_page
-- Purpose: Load one complete page from its dedicated current read model.
-- Responsibilities: Normalize identity and perform exactly one page-model lookup.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.rpc_get_page(p_input JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SET search_path = ''
AS $$
DECLARE
  v_page_type TEXT := p_input->>'page_type';
  v_entity_key TEXT := p_input->>'entity_key';
  v_locale TEXT := COALESCE(NULLIF(p_input->>'locale', ''), 'en-GB');
  v_version_id UUID;
  v_payload JSONB;
  v_metadata JSONB;
  v_generated_at TIMESTAMPTZ;
BEGIN
  IF jsonb_typeof(p_input) IS DISTINCT FROM 'object'
    OR p_input - ARRAY['page_type', 'entity_key', 'locale'] <> '{}'::JSONB
    OR v_page_type NOT IN ('city', 'airport', 'route')
    OR v_entity_key IS NULL
    OR v_locale !~ '^[a-z]{2}(?:-[A-Z]{2})?$'
  THEN
    RETURN admin.build_rpc_error(NULL, 'ERR_INVALID_REQUEST', 'Invalid page request.');
  END IF;

  -- STEP 01: Select the requested row and its current version in one indexed statement.
  IF v_page_type = 'city' THEN
    SELECT model.payload, model.metadata, model.generated_at, version.id
    INTO v_payload, v_metadata, v_generated_at, v_version_id
    FROM public.city_page_read_models model
    INNER JOIN public.publication_versions version
      ON version.id = model.publication_version_id
      AND version.is_current = TRUE
    WHERE model.canonical_slug = lower(v_entity_key)
      AND model.locale = v_locale;
  ELSIF v_page_type = 'airport' THEN
    SELECT model.payload, model.metadata, model.generated_at, version.id
    INTO v_payload, v_metadata, v_generated_at, v_version_id
    FROM public.airport_page_read_models model
    INNER JOIN public.publication_versions version
      ON version.id = model.publication_version_id
      AND version.is_current = TRUE
    WHERE model.airport_iata = upper(v_entity_key)
      AND model.locale = v_locale;
  ELSE
    SELECT model.payload, model.metadata, model.generated_at, version.id
    INTO v_payload, v_metadata, v_generated_at, v_version_id
    FROM public.route_page_read_models model
    INNER JOIN public.publication_versions version
      ON version.id = model.publication_version_id
      AND version.is_current = TRUE
    WHERE model.canonical_slug = lower(v_entity_key)
      AND model.locale = v_locale;
  END IF;

  IF v_payload IS NULL THEN
    RETURN admin.build_rpc_error(NULL, 'ERR_PAGE_NOT_FOUND', 'Current page not found.');
  END IF;

  -- STEP 02: Return the materialized payload without rebuilding page modules at request time.
  RETURN jsonb_build_object(
    'data', v_payload,
    'meta', v_metadata || jsonb_build_object(
      'page_type', v_page_type,
      'entity_key', v_entity_key,
      'data_version', 'v_' || md5(v_version_id::TEXT),
      'generated_at', v_generated_at
    ),
    'error', NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION public.rpc_get_page(JSONB)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_get_page(JSONB) TO service_role;

-- >>> supabase/sql_src/operations/sync_provider_pseo_pages.sql

-- ============================================================================
-- Function: admin.sync_provider_pseo_pages
-- Purpose: Synchronize factual pSEO source pages from canonical provider data.
-- Responsibilities: Create noindex city, airport, and fresh route source documents.
-- Notes: Generated content is never marked reviewed and cannot pass production indexing gates.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.sync_provider_pseo_pages(p_environment TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_status          TEXT;
  v_noindex_reason  TEXT;
  v_city_count      INTEGER := 0;
  v_airport_count   INTEGER := 0;
  v_route_count     INTEGER := 0;
BEGIN
  IF p_environment NOT IN ('development_fixture', 'staging', 'production') THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'ERR_PUBLICATION_SOURCE_INVALID';
  END IF;

  v_status := CASE WHEN p_environment = 'development_fixture' THEN 'draft' ELSE 'published' END;
  v_noindex_reason := CASE
    WHEN p_environment = 'staging' THEN 'staging_environment'
    WHEN p_environment = 'development_fixture' THEN 'development_fixture'
    ELSE 'source_not_seo_eligible'
  END;

  -- STEP 01: Create registries for unambiguous cities with an active airport.
  INSERT INTO public.pseo_pages (
    page_type, entity_key, locale, canonical_path, display_title, status,
    is_indexable, noindex_reason, source_freshness_at
  )
  SELECT
    'city', city.slug, 'en-GB', '/flights-from-' || city.slug,
    'Flights from ' || city.name, v_status, FALSE, v_noindex_reason, city.updated_at
  FROM public.cities AS city
  WHERE EXISTS (
      SELECT 1 FROM public.airports AS airport
      WHERE airport.city_id = city.id AND airport.status = 'active'
    )
    AND NOT EXISTS (
      SELECT 1 FROM public.cities AS duplicate
      WHERE duplicate.slug = city.slug AND duplicate.id <> city.id
    )
  ON CONFLICT (page_type, entity_key, locale) DO UPDATE
  SET source_freshness_at = EXCLUDED.source_freshness_at,
      generated_at = now();

  INSERT INTO public.city_pages (
    pseo_page_id, city_id, locale, route_direction, primary_airport_id, content,
    content_reviewed_at
  )
  SELECT
    registry.id, city.id, 'en-GB', 'outbound', airport.id,
    jsonb_build_object(
      'seo', jsonb_build_object(
        'h1', 'Flights from ' || city.name,
        'title', 'Flights from ' || city.name || ' | Tripways',
        'meta_description', 'Explore recently observed route prices from ' || city.name || '.'
      ),
      'intro', 'Explore factual airport identities and recently observed route prices from ' || city.name || '.'
    ),
    NULL
  FROM public.cities AS city
  JOIN public.pseo_pages AS registry
    ON registry.page_type = 'city' AND registry.entity_key = city.slug AND registry.locale = 'en-GB'
  JOIN LATERAL (
    SELECT candidate.id
    FROM public.airports AS candidate
    WHERE candidate.city_id = city.id AND candidate.status = 'active'
    ORDER BY
      CASE candidate.airport_type WHEN 'large_airport' THEN 1 WHEN 'medium_airport' THEN 2 ELSE 3 END,
      candidate.iata
    LIMIT 1
  ) AS airport ON TRUE
  ON CONFLICT (city_id, locale, route_direction) DO NOTHING;
  GET DIAGNOSTICS v_city_count = ROW_COUNT;

  -- STEP 02: Create registries and aggregate source documents for active airports.
  INSERT INTO public.pseo_pages (
    page_type, entity_key, locale, canonical_path, display_title, status,
    is_indexable, noindex_reason, source_freshness_at
  )
  SELECT
    'airport', lower(airport.iata), 'en-GB', '/airports/' || lower(airport.iata),
    airport.name || ' (' || airport.iata || ')', v_status, FALSE, v_noindex_reason,
    airport.updated_at
  FROM public.airports AS airport
  WHERE airport.status = 'active' AND airport.iata IS NOT NULL
  ON CONFLICT (page_type, entity_key, locale) DO UPDATE
  SET source_freshness_at = EXCLUDED.source_freshness_at,
      generated_at = now();

  INSERT INTO public.airport_pages (
    pseo_page_id, airport_id, locale, content, content_reviewed_at
  )
  SELECT
    registry.id, airport.id, 'en-GB',
    jsonb_build_object(
      'seo', jsonb_build_object(
        'h1', airport.name || ' (' || airport.iata || ')',
        'title', airport.name || ' Airport Guide | Tripways',
        'meta_description', 'View factual airport and location information for ' || airport.name || '.'
      ),
      'orientation', airport.name || ' serves ' || city.name || ', ' || country.name || '.'
    ),
    NULL
  FROM public.airports AS airport
  JOIN public.cities AS city ON city.id = airport.city_id
  JOIN public.countries AS country ON country.id = airport.country_id
  JOIN public.pseo_pages AS registry
    ON registry.page_type = 'airport'
   AND registry.entity_key = lower(airport.iata)
   AND registry.locale = 'en-GB'
  WHERE airport.status = 'active' AND airport.iata IS NOT NULL
  ON CONFLICT (airport_id, locale) DO NOTHING;
  GET DIAGNOSTICS v_airport_count = ROW_COUNT;

  -- STEP 03: Create directional route pages only from fresh provider prices.
  INSERT INTO public.pseo_pages (
    page_type, entity_key, locale, canonical_path, display_title, status,
    is_indexable, noindex_reason, source_freshness_at
  )
  SELECT
    'city_route', origin.slug || '-' || destination.slug, 'en-GB',
    '/flights/' || origin.slug || '-' || destination.slug,
    'Flights from ' || origin.name || ' to ' || destination.name,
    v_status, FALSE, v_noindex_reason, max(price.observed_at)
  FROM public.flight_route_prices AS price
  JOIN public.cities AS origin ON origin.id = price.origin_city_id
  JOIN public.cities AS destination ON destination.id = price.destination_city_id
  WHERE price.status = 'published' AND price.valid_until > now()
  GROUP BY origin.slug, origin.name, destination.slug, destination.name
  ON CONFLICT (page_type, entity_key, locale) DO UPDATE
  SET source_freshness_at = GREATEST(
        public.pseo_pages.source_freshness_at,
        EXCLUDED.source_freshness_at
      ),
      generated_at = now();

  INSERT INTO public.route_pages (
    pseo_page_id, origin_city_id, destination_city_id, locale, content,
    content_reviewed_at
  )
  SELECT DISTINCT ON (origin.id, destination.id)
    registry.id, origin.id, destination.id, 'en-GB',
    jsonb_build_object(
      'seo', jsonb_build_object(
        'h1', 'Flights from ' || origin.name || ' to ' || destination.name,
        'title', origin.name || ' to ' || destination.name || ' Flights | Tripways',
        'meta_description', 'Compare recently observed route prices from ' || origin.name || ' to ' || destination.name || '.'
      ),
      'intro', 'Compare recently observed route prices before checking current availability with the booking partner.'
    ),
    NULL
  FROM public.flight_route_prices AS price
  JOIN public.cities AS origin ON origin.id = price.origin_city_id
  JOIN public.cities AS destination ON destination.id = price.destination_city_id
  JOIN public.pseo_pages AS registry
    ON registry.page_type = 'city_route'
   AND registry.entity_key = origin.slug || '-' || destination.slug
   AND registry.locale = 'en-GB'
  WHERE price.status = 'published' AND price.valid_until > now()
  ORDER BY origin.id, destination.id, price.observed_at DESC
  ON CONFLICT (origin_city_id, destination_city_id, locale) DO NOTHING;
  GET DIAGNOSTICS v_route_count = ROW_COUNT;

  RETURN jsonb_build_object(
    'city_pages_created', v_city_count,
    'airport_pages_created', v_airport_count,
    'route_pages_created', v_route_count
  );
END;
$$;

REVOKE ALL ON FUNCTION admin.sync_provider_pseo_pages(TEXT)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.sync_provider_pseo_pages(TEXT) TO service_role;
