-- ============================================================================
-- Migration: 20260714080350_ingestion_schema.sql
-- Source of truth: supabase/sql_src
-- Feature: base data ingestion schema
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/schema/ingestion/raw_import_batches.sql

-- Table: admin.raw_import_batches
-- Feature: Base Data Ingestion
-- Purpose: Record immutable provider batch receipts before canonical publication.
-- Responsibilities: Preserve source provenance, checksum idempotency, and batch lifecycle state.

CREATE TABLE admin.raw_import_batches (
  id                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  source_id         UUID         NOT NULL REFERENCES admin.data_sources (id),
  provider_version  TEXT         NOT NULL,
  checksum          TEXT         NOT NULL,
  idempotency_key   TEXT         NOT NULL,
  received_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  source_time       TIMESTAMPTZ  NULL,
  source_url        TEXT         NULL,
  source_etag       TEXT         NULL,
  downloaded_bytes  INTEGER      NULL,
  raw_record_count  INTEGER      NULL,
  eligible_record_count INTEGER  NULL,
  filtered_record_count INTEGER  NULL,
  invalid_record_count INTEGER   NULL,
  filter_version    TEXT         NULL,
  status            TEXT         NOT NULL DEFAULT 'received',
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT raw_import_batches_source_checksum_key
    UNIQUE (source_id, checksum),

  CONSTRAINT raw_import_batches_source_idempotency_key
    UNIQUE (source_id, idempotency_key),

  CONSTRAINT raw_import_batches_provider_version_check
    CHECK (
      provider_version = btrim(provider_version)
      AND char_length(provider_version) BETWEEN 1 AND 40
    ),

  CONSTRAINT raw_import_batches_checksum_check
    CHECK (checksum ~ '^[a-f0-9]{64}$'),

  CONSTRAINT raw_import_batches_idempotency_key_check
    CHECK (
      idempotency_key = btrim(idempotency_key)
      AND char_length(idempotency_key) BETWEEN 8 AND 128
    ),

  CONSTRAINT raw_import_batches_status_check
    CHECK (
      status IN (
        'received',
        'validated',
        'awaiting_review',
        'published',
        'rejected',
        'unchanged'
      )
    ),

  CONSTRAINT raw_import_batches_download_metrics_check
    CHECK (
      (downloaded_bytes IS NULL OR downloaded_bytes >= 0)
      AND (raw_record_count IS NULL OR raw_record_count >= 0)
      AND (eligible_record_count IS NULL OR eligible_record_count >= 0)
      AND (filtered_record_count IS NULL OR filtered_record_count >= 0)
      AND (invalid_record_count IS NULL OR invalid_record_count >= 0)
    ),

  CONSTRAINT raw_import_batches_source_url_check
    CHECK (source_url IS NULL OR source_url ~ '^https://'),

  CONSTRAINT raw_import_batches_filter_version_check
    CHECK (
      filter_version IS NULL
      OR (
        filter_version = btrim(filter_version)
        AND char_length(filter_version) BETWEEN 1 AND 80
      )
    )
);

CREATE INDEX raw_import_batches_source_received_idx
ON admin.raw_import_batches USING btree (source_id, received_at DESC);

REVOKE ALL ON TABLE admin.raw_import_batches FROM public, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE admin.raw_import_batches TO service_role;

-- >>> supabase/sql_src/schema/ingestion/raw_base_data_records.sql

-- Table: admin.raw_base_data_records
-- Feature: Base Data Ingestion
-- Purpose: Preserve bounded provider records inside the internal ingestion boundary.
-- Responsibilities: Link records to a batch and record their validation outcome.

CREATE TABLE admin.raw_base_data_records (
  id                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id          UUID         NOT NULL REFERENCES admin.raw_import_batches (id) ON DELETE CASCADE,
  record_type       TEXT         NOT NULL,
  source_key        TEXT         NOT NULL,
  payload           JSONB        NOT NULL,
  validation_state  TEXT         NOT NULL DEFAULT 'pending',
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT raw_base_data_records_batch_identity_key
    UNIQUE (batch_id, record_type, source_key),

  CONSTRAINT raw_base_data_records_type_check
    CHECK (
      record_type IN (
        'country',
        'city',
        'place_alias',
        'metro_area',
        'airport',
        'airport_terminal',
        'airline',
        'flight_route',
        'flight_service',
        'route_price_estimate',
        'city_fact',
        'airport_facility',
        'airport_fact',
        'page_editorial_content'
      )
    ),

  CONSTRAINT raw_base_data_records_source_key_check
    CHECK (
      source_key = btrim(source_key)
      AND char_length(source_key) BETWEEN 1 AND 160
    ),

  CONSTRAINT raw_base_data_records_payload_object_check
    CHECK (jsonb_typeof(payload) = 'object'),

  CONSTRAINT raw_base_data_records_validation_state_check
    CHECK (validation_state IN ('pending', 'valid', 'invalid'))
);

CREATE INDEX raw_base_data_records_batch_idx
ON admin.raw_base_data_records USING btree (batch_id);

REVOKE ALL ON TABLE admin.raw_base_data_records FROM public, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE admin.raw_base_data_records TO service_role;

-- >>> supabase/sql_src/schema/ingestion/flight_route_cache_states.sql

-- Table: admin.flight_route_cache_states
-- Feature: On-demand Flight Route Cache
-- Purpose: Coordinate demand, leases, freshness, and cooldown without storing provider payloads.

CREATE TABLE admin.flight_route_cache_states (
  cache_key              TEXT        PRIMARY KEY,
  origin_iata            TEXT        NOT NULL,
  destination_iata       TEXT        NULL,
  market_code            TEXT        NOT NULL,
  currency_code          TEXT        NOT NULL,
  locale                 TEXT        NOT NULL,
  status                 TEXT        NOT NULL DEFAULT 'idle',
  lease_token            TEXT        NULL,
  lease_expires_at       TIMESTAMPTZ NULL,
  next_refresh_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_requested_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_attempted_at      TIMESTAMPTZ NULL,
  last_succeeded_at      TIMESTAMPTZ NULL,
  refreshed_at           TIMESTAMPTZ NULL,
  valid_until            TIMESTAMPTZ NULL,
  observation_count      INTEGER     NOT NULL DEFAULT 0,
  consecutive_failures   INTEGER     NOT NULL DEFAULT 0,
  failure_code           TEXT        NULL,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT flight_route_cache_states_key_check
    CHECK (cache_key ~ '^frc_[0-9a-f]{32}$'),

  CONSTRAINT flight_route_cache_states_origin_check
    CHECK (origin_iata ~ '^[A-Z0-9]{3}$'),

  CONSTRAINT flight_route_cache_states_destination_check
    CHECK (destination_iata IS NULL OR destination_iata ~ '^[A-Z0-9]{3}$'),

  CONSTRAINT flight_route_cache_states_direction_check
    CHECK (destination_iata IS NULL OR destination_iata <> origin_iata),

  CONSTRAINT flight_route_cache_states_market_check
    CHECK (market_code ~ '^[a-z]{2}$'),

  CONSTRAINT flight_route_cache_states_currency_check
    CHECK (currency_code ~ '^[A-Z]{3}$'),

  CONSTRAINT flight_route_cache_states_locale_check
    CHECK (locale ~ '^[a-z]{2}(?:-[A-Z]{2})?$'),

  CONSTRAINT flight_route_cache_states_status_check
    CHECK (status IN ('idle', 'refreshing', 'fresh', 'empty', 'failed')),

  CONSTRAINT flight_route_cache_states_lease_check
    CHECK ((lease_token IS NULL) = (lease_expires_at IS NULL)),

  CONSTRAINT flight_route_cache_states_count_check
    CHECK (observation_count >= 0 AND consecutive_failures >= 0)
);

CREATE INDEX flight_route_cache_states_due_idx
ON admin.flight_route_cache_states USING btree (next_refresh_at, last_requested_at)
WHERE status IN ('fresh', 'empty', 'failed');

CREATE INDEX flight_route_cache_states_lease_idx
ON admin.flight_route_cache_states USING btree (lease_expires_at)
WHERE status = 'refreshing';

ALTER TABLE admin.flight_route_cache_states ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE admin.flight_route_cache_states FROM public, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE admin.flight_route_cache_states TO service_role;

-- >>> supabase/sql_src/schema/ingestion/ourairports_denylist.sql

-- Table: admin.ourairports_denylist
-- Feature: OurAirports Ingestion
-- Purpose: Exclude IATA airports that do not fit Tripways commercial coverage.
-- Responsibilities: Keep reviewed exclusions auditable and outside provider adapter code.

CREATE TABLE admin.ourairports_denylist (
  iata        TEXT         PRIMARY KEY,
  reason      TEXT         NOT NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT ourairports_denylist_iata_check
    CHECK (iata ~ '^[A-Z]{3}$'),

  CONSTRAINT ourairports_denylist_reason_check
    CHECK (reason = btrim(reason) AND char_length(reason) BETWEEN 1 AND 240)
);

REVOKE ALL ON TABLE admin.ourairports_denylist FROM public, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE admin.ourairports_denylist TO service_role;
