-- ============================================================================
-- Migration: 20260714080800_route_discovery_functions.sql
-- Source of truth: supabase/sql_src
-- Feature: route discovery functions
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/functions/route_discovery/calculate_haversine_distance_km.sql

-- ============================================================================
-- Function: admin.calculate_haversine_distance_km
-- Purpose: Calculate great-circle distance between two geographic coordinates in kilometers.
-- Responsibilities: Provide pure, immutable spherical distance computation for route metadata.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.calculate_haversine_distance_km(
  p_lat1 DOUBLE PRECISION,
  p_lon1 DOUBLE PRECISION,
  p_lat2 DOUBLE PRECISION,
  p_lon2 DOUBLE PRECISION
)
RETURNS INTEGER
LANGUAGE plpgsql
IMMUTABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_dlat DOUBLE PRECISION;
  v_dlon DOUBLE PRECISION;
  v_a    DOUBLE PRECISION;
  v_c    DOUBLE PRECISION;
  v_r    CONSTANT DOUBLE PRECISION := 6371.0;
BEGIN
  IF p_lat1 IS NULL OR p_lon1 IS NULL OR p_lat2 IS NULL OR p_lon2 IS NULL THEN
    RETURN 0;
  END IF;

  v_dlat := radians(p_lat2 - p_lat1);
  v_dlon := radians(p_lon2 - p_lon1);

  v_a := sin(v_dlat / 2.0) * sin(v_dlat / 2.0) +
         cos(radians(p_lat1)) * cos(radians(p_lat2)) *
         sin(v_dlon / 2.0) * sin(v_dlon / 2.0);

  v_c := 2.0 * atan2(sqrt(v_a), sqrt(greatest(0.0, 1.0 - v_a)));

  RETURN round(v_r * v_c)::INTEGER;
END;
$$;

REVOKE ALL ON FUNCTION admin.calculate_haversine_distance_km(DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.calculate_haversine_distance_km(DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION) TO service_role;

-- >>> supabase/sql_src/functions/route_discovery/calculate_route_schedule_intersection.sql

-- ============================================================================
-- Function: admin.calculate_route_schedule_intersection
-- Purpose: Compute the intersection of operating days-of-week for connecting flights.
-- Responsibilities: Provide pure, reusable schedule compatibility calculation.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.calculate_route_schedule_intersection(
  p_days1 INTEGER[],
  p_days2 INTEGER[] DEFAULT NULL
)
RETURNS INTEGER[]
LANGUAGE plpgsql
IMMUTABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_intersection INTEGER[];
BEGIN
  IF p_days1 IS NULL OR cardinality(p_days1) = 0 THEN
    p_days1 := '{1,2,3,4,5,6,7}'::INTEGER[];
  END IF;

  IF p_days2 IS NULL OR cardinality(p_days2) = 0 THEN
    RETURN p_days1;
  END IF;

  SELECT ARRAY(
    SELECT unnest(p_days1)
    INTERSECT
    SELECT unnest(p_days2)
    ORDER BY 1
  ) INTO v_intersection;

  IF cardinality(v_intersection) = 0 THEN
    RETURN p_days1;
  END IF;

  RETURN v_intersection;
END;
$$;

REVOKE ALL ON FUNCTION admin.calculate_route_schedule_intersection(INTEGER[], INTEGER[])
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.calculate_route_schedule_intersection(INTEGER[], INTEGER[]) TO service_role;

-- >>> supabase/sql_src/functions/route_discovery/calculate_connecting_duration_minutes.sql

-- ============================================================================
-- Function: admin.calculate_connecting_duration_minutes
-- Purpose: Calculate total trip duration including flight legs and layover time.
-- Responsibilities: Provide pure, reusable duration calculation respecting airport minimum transit time.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.calculate_connecting_duration_minutes(
  p_duration1        INTEGER,
  p_duration2        INTEGER DEFAULT NULL,
  p_layover_minutes  INTEGER DEFAULT 90
)
RETURNS INTEGER
LANGUAGE plpgsql
IMMUTABLE
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF p_duration1 IS NULL OR p_duration1 <= 0 THEN
    p_duration1 := 0;
  END IF;

  IF p_duration2 IS NULL OR p_duration2 <= 0 THEN
    RETURN p_duration1;
  END IF;

  RETURN p_duration1 + p_duration2 + COALESCE(greatest(0, p_layover_minutes), 90);
END;
$$;

REVOKE ALL ON FUNCTION admin.calculate_connecting_duration_minutes(INTEGER, INTEGER, INTEGER)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.calculate_connecting_duration_minutes(INTEGER, INTEGER, INTEGER) TO service_role;

-- >>> supabase/sql_src/functions/route_discovery/classify_route_connection_type.sql

-- ============================================================================
-- Function: admin.classify_route_connection_type
-- Purpose: Classify itinerary type based on airline legs (direct, same-airline, alliance).
-- Responsibilities: Provide pure, reusable route connection classification logic.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.classify_route_connection_type(
  p_airline1 TEXT,
  p_airline2 TEXT DEFAULT NULL
)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF p_airline2 IS NULL OR NULLIF(btrim(p_airline2), '') IS NULL THEN
    RETURN 'direct';
  END IF;

  IF upper(btrim(p_airline1)) = upper(btrim(p_airline2)) THEN
    RETURN 'same_airline';
  END IF;

  RETURN 'alliance';
END;
$$;

REVOKE ALL ON FUNCTION admin.classify_route_connection_type(TEXT, TEXT)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.classify_route_connection_type(TEXT, TEXT) TO service_role;

-- >>> supabase/sql_src/functions/route_discovery/refresh_route_search_options.sql

-- ============================================================================
-- Function: admin.refresh_route_search_options
-- Purpose: Build a pre-computed route-search projection from direct routes (0-stop)
--          and connecting routes (1-stop via dynamic hubs).
-- Responsibilities: Materialize candidate publication using dedicated pure calculation functions.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.refresh_route_search_options(p_publication_version_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
VOLATILE
SET search_path = ''
AS $$
DECLARE
  v_count INTEGER;
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.publication_versions AS version
    WHERE version.id = p_publication_version_id
      AND version.status = 'building'
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'ERR_PUBLICATION_VERSION_INVALID';
  END IF;

  DELETE FROM public.flight_route_options WHERE publication_version_id = p_publication_version_id;

  -- 1. Insert 0-Stop Direct Non-Stop Routes
  INSERT INTO public.flight_route_options (
    id, publication_version_id,
    origin_city_id, origin_city_slug, origin_country_code,
    destination_city_id, destination_city_slug, destination_country_code, destination_region,
    origin_airport_id, origin_airport_iata,
    destination_airport_id, destination_airport_iata,
    stops, layover_airport_ids, layover_airports,
    operating_airlines, flight_numbers, flight_durations_minutes,
    total_duration_minutes, total_distance_km, days_of_week,
    departure_time_buckets, layover_minutes, cabins, price_amount, price_currency,
    route_type, confidence_score, route_path
  )
  SELECT
    r.id, p_publication_version_id,
    origin_city.id, origin_city.slug, origin_country.iso2,
    destination_city.id, destination_city.slug, destination_country.iso2, destination_country.region,
    origin_airport.id, origin_airport.iata,
    destination_airport.id, destination_airport.iata,
    0, '{}'::UUID[], '{}'::TEXT[],
    ARRAY[r.airline_iata], r.flight_numbers, ARRAY[r.flight_duration_minutes],
    r.flight_duration_minutes,
    COALESCE(
      NULLIF(r.distance_km, 0),
      admin.calculate_haversine_distance_km(origin_airport.latitude, origin_airport.longitude, destination_airport.latitude, destination_airport.longitude)
    ),
    admin.calculate_route_schedule_intersection(r.days_of_week, NULL),
    '{}'::TEXT[], 0, ARRAY['economy']::TEXT[], price.observed_amount, price.currency_code,
    admin.classify_route_connection_type(r.airline_iata, NULL),
    1.000,
    COALESCE(registry.canonical_path, '/flights/' || origin_city.slug || '-to-' || destination_city.slug)
  FROM public.direct_flight_routes r
  JOIN public.airports origin_airport ON origin_airport.id = r.origin_airport_id
  JOIN public.cities origin_city ON origin_city.id = origin_airport.city_id
  JOIN public.countries origin_country ON origin_country.id = origin_city.country_id
  JOIN public.airports destination_airport ON destination_airport.id = r.destination_airport_id
  JOIN public.cities destination_city ON destination_city.id = destination_airport.city_id
  JOIN public.countries destination_country ON destination_country.id = destination_city.country_id
  LEFT JOIN public.route_pages page
    ON page.origin_city_id = origin_city.id
   AND page.destination_city_id = destination_city.id
   AND page.locale = 'en-GB'
  LEFT JOIN public.pseo_pages registry ON registry.id = page.pseo_page_id AND registry.status <> 'archived'
  LEFT JOIN LATERAL (
    SELECT observed.observed_amount, observed.currency_code
    FROM public.flight_route_prices AS observed
    WHERE observed.origin_airport_id = origin_airport.id
      AND observed.destination_airport_id = destination_airport.id
      AND observed.transfer_count = 0
      AND observed.status = 'published'
      AND observed.valid_until > now()
      AND (
        observed.provider_airline_iata IS NULL
        OR observed.provider_airline_iata = r.airline_iata
      )
    ORDER BY
      (observed.provider_airline_iata = r.airline_iata) DESC,
      observed.observed_amount ASC NULLS LAST,
      observed.observed_at DESC
    LIMIT 1
  ) AS price ON TRUE
  WHERE r.is_active = TRUE
    AND origin_airport.status = 'active'
    AND destination_airport.status = 'active'
    AND origin_city.id <> destination_city.id;

  -- 2. Insert 1-Stop Connecting Routes via Dynamic Hubs
  INSERT INTO public.flight_route_options (
    id, publication_version_id,
    origin_city_id, origin_city_slug, origin_country_code,
    destination_city_id, destination_city_slug, destination_country_code, destination_region,
    origin_airport_id, origin_airport_iata,
    destination_airport_id, destination_airport_iata,
    stops, layover_airport_ids, layover_airports,
    operating_airlines, flight_numbers, flight_durations_minutes,
    total_duration_minutes, total_distance_km, days_of_week,
    departure_time_buckets, layover_minutes, cabins, price_amount, price_currency,
    route_type, confidence_score, route_path
  )
  SELECT
    (
      substr(md5(r1.id::TEXT || ':' || r2.id::TEXT), 1, 8) || '-' ||
      substr(md5(r1.id::TEXT || ':' || r2.id::TEXT), 9, 4) || '-' ||
      substr(md5(r1.id::TEXT || ':' || r2.id::TEXT), 13, 4) || '-' ||
      substr(md5(r1.id::TEXT || ':' || r2.id::TEXT), 17, 4) || '-' ||
      substr(md5(r1.id::TEXT || ':' || r2.id::TEXT), 21, 12)
    )::UUID,
    p_publication_version_id,
    origin_city.id, origin_city.slug, origin_country.iso2,
    destination_city.id, destination_city.slug, destination_country.iso2, destination_country.region,
    origin_airport.id, origin_airport.iata,
    destination_airport.id, destination_airport.iata,
    1, ARRAY[hub_airport.id]::UUID[], ARRAY[r1.destination_iata]::TEXT[],
    ARRAY[r1.airline_iata, r2.airline_iata],
    r1.flight_numbers || r2.flight_numbers,
    ARRAY[r1.flight_duration_minutes, r2.flight_duration_minutes],
    admin.calculate_connecting_duration_minutes(r1.flight_duration_minutes, r2.flight_duration_minutes, hub_airport.min_transit_minutes),
    (r1.distance_km + r2.distance_km),
    admin.calculate_route_schedule_intersection(r1.days_of_week, r2.days_of_week),
    '{}'::TEXT[], hub_airport.min_transit_minutes, ARRAY['economy']::TEXT[],
    price.observed_amount, price.currency_code,
    admin.classify_route_connection_type(r1.airline_iata, r2.airline_iata),
    0.950,
    COALESCE(registry.canonical_path, '/flights/' || origin_city.slug || '-to-' || destination_city.slug)
  FROM public.direct_flight_routes r1
  JOIN public.airports hub_airport ON hub_airport.id = r1.destination_airport_id AND hub_airport.is_hub = TRUE
  JOIN public.direct_flight_routes r2 ON r2.origin_airport_id = hub_airport.id
  JOIN public.airports origin_airport ON origin_airport.id = r1.origin_airport_id
  JOIN public.cities origin_city ON origin_city.id = origin_airport.city_id
  JOIN public.countries origin_country ON origin_country.id = origin_city.country_id
  JOIN public.airports destination_airport ON destination_airport.id = r2.destination_airport_id
  JOIN public.cities destination_city ON destination_city.id = destination_airport.city_id
  JOIN public.countries destination_country ON destination_country.id = destination_city.country_id
  LEFT JOIN public.route_pages page
    ON page.origin_city_id = origin_city.id
   AND page.destination_city_id = destination_city.id
   AND page.locale = 'en-GB'
  LEFT JOIN public.pseo_pages registry ON registry.id = page.pseo_page_id AND registry.status <> 'archived'
  LEFT JOIN LATERAL (
    SELECT observed.observed_amount, observed.currency_code
    FROM public.flight_route_prices AS observed
    WHERE observed.origin_airport_id = origin_airport.id
      AND observed.destination_airport_id = destination_airport.id
      AND observed.transfer_count = 1
      AND observed.status = 'published'
      AND observed.valid_until > now()
    ORDER BY observed.observed_amount ASC NULLS LAST, observed.observed_at DESC
    LIMIT 1
  ) AS price ON TRUE
  WHERE r1.is_active = TRUE
    AND r2.is_active = TRUE
    AND origin_airport.status = 'active'
    AND destination_airport.status = 'active'
    AND origin_city.id <> destination_city.id
    AND r1.origin_airport_id <> r2.destination_airport_id;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION admin.refresh_route_search_options(UUID)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.refresh_route_search_options(UUID) TO service_role;

-- >>> supabase/sql_src/functions/route_discovery/rpc_search_routes.sql

-- ============================================================================
-- Function: public.rpc_search_routes
-- Purpose: Search the pre-computed 0-stop and 1-stop route projections.
-- Responsibilities: Validate supported filters and return a bounded public route payload.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.rpc_search_routes(p_input JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SET search_path = ''
AS $$
DECLARE
  v_version_id              UUID;
  v_scope_type              TEXT;
  v_scope_key               TEXT;
  v_scope_from              TEXT;
  v_scope_to                TEXT;
  v_direction               TEXT;
  v_page_size               INTEGER := 20;
  v_offset                  INTEGER := 0;
  v_max_stops               INTEGER;
  v_airlines                TEXT[] := '{}';
  v_connection_airports     TEXT[] := '{}';
  v_departure_airports      TEXT[] := '{}';
  v_destination_countries   TEXT[] := '{}';
  v_destination_regions     TEXT[] := '{}';
  v_counterpart_query       TEXT;
  v_counterpart_countries   TEXT[] := '{}';
  v_counterpart_regions     TEXT[] := '{}';
  v_departure_time_buckets  TEXT[] := '{}';
  v_days_of_week            INTEGER[] := '{}';
  v_route_type              TEXT := 'all';
  v_max_duration_minutes    INTEGER;
  v_max_layover_minutes     INTEGER;
  v_cabin                   TEXT := 'any';
  v_max_amount              NUMERIC;
  v_currency                TEXT;
  v_result                  JSONB;
BEGIN
  IF jsonb_typeof(p_input) IS DISTINCT FROM 'object'
    OR jsonb_typeof(p_input->'scope') IS DISTINCT FROM 'object'
    OR jsonb_typeof(p_input->'filters') IS DISTINCT FROM 'object'
    OR (p_input - ARRAY['scope', 'filters', 'page_size', 'after']) <> '{}'::JSONB
    OR (
      (p_input->'filters') - ARRAY[
        'max_stops', 'airlines', 'connection_airports', 'departure_airports',
        'destination_countries', 'destination_regions', 'counterpart_query',
        'counterpart_countries', 'counterpart_regions', 'departure_time_buckets',
        'days_of_week', 'route_type', 'max_duration_minutes', 'max_layover_minutes',
        'cabin', 'max_amount', 'currency'
      ]
    ) <> '{}'::JSONB
  THEN
    RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
  END IF;

  v_scope_type := p_input #>> '{scope,type}';
  v_scope_key := p_input #>> '{scope,key}';
  v_scope_from := p_input #>> '{scope,from}';
  v_scope_to := p_input #>> '{scope,to}';
  v_direction := p_input #>> '{scope,direction}';

  IF v_scope_type NOT IN ('global', 'origin_city', 'origin_airport', 'airport', 'city_pair')
    OR (v_scope_type IN ('origin_city', 'origin_airport', 'airport') AND NULLIF(btrim(COALESCE(v_scope_key, '')), '') IS NULL)
    OR (v_scope_type = 'airport' AND v_direction NOT IN ('from', 'to'))
    OR (v_scope_type = 'city_pair' AND (NULLIF(v_scope_from, '') IS NULL OR NULLIF(v_scope_to, '') IS NULL OR v_scope_from = v_scope_to))
    OR (p_input ? 'page_size' AND (jsonb_typeof(p_input->'page_size') <> 'number' OR p_input->>'page_size' !~ '^[0-9]+$' OR (p_input->>'page_size')::INTEGER NOT BETWEEN 1 AND 100))
    OR (p_input ? 'after' AND p_input->'after' <> 'null'::JSONB AND (jsonb_typeof(p_input->'after') <> 'string' OR p_input->>'after' !~ '^offset:[0-9]+$'))
  THEN
    RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
  END IF;

  v_page_size := COALESCE((p_input->>'page_size')::INTEGER, 20);
  IF p_input->>'after' IS NOT NULL THEN
    v_offset := split_part(p_input->>'after', ':', 2)::INTEGER;
  END IF;

  IF p_input->'filters' ? 'max_stops' THEN
    IF jsonb_typeof(p_input #> '{filters,max_stops}') <> 'number' OR p_input #>> '{filters,max_stops}' !~ '^[01]$' THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    v_max_stops := (p_input #>> '{filters,max_stops}')::INTEGER;
  END IF;

  IF p_input->'filters' ? 'max_duration_minutes' THEN
    IF jsonb_typeof(p_input #> '{filters,max_duration_minutes}') <> 'number' OR p_input #>> '{filters,max_duration_minutes}' !~ '^[0-9]+$' OR (p_input #>> '{filters,max_duration_minutes}')::INTEGER NOT BETWEEN 1 AND 10080 THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    v_max_duration_minutes := (p_input #>> '{filters,max_duration_minutes}')::INTEGER;
  END IF;

  IF p_input->'filters' ? 'max_layover_minutes' THEN
    IF jsonb_typeof(p_input #> '{filters,max_layover_minutes}') <> 'number' OR p_input #>> '{filters,max_layover_minutes}' !~ '^[0-9]+$' OR (p_input #>> '{filters,max_layover_minutes}')::INTEGER NOT BETWEEN 1 AND 10080 THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    v_max_layover_minutes := (p_input #>> '{filters,max_layover_minutes}')::INTEGER;
  END IF;

  IF p_input->'filters' ? 'route_type' THEN
    IF jsonb_typeof(p_input #> '{filters,route_type}') <> 'string' OR p_input #>> '{filters,route_type}' NOT IN ('all', 'domestic', 'international') THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    v_route_type := p_input #>> '{filters,route_type}';
  END IF;

  IF p_input->'filters' ? 'cabin' THEN
    IF jsonb_typeof(p_input #> '{filters,cabin}') <> 'string' OR p_input #>> '{filters,cabin}' NOT IN ('any', 'economy', 'premium_economy', 'business', 'first') THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    v_cabin := p_input #>> '{filters,cabin}';
  END IF;

  IF p_input->'filters' ? 'counterpart_query' THEN
    IF jsonb_typeof(p_input #> '{filters,counterpart_query}') <> 'string' OR char_length(btrim(p_input #>> '{filters,counterpart_query}')) NOT BETWEEN 1 AND 80 THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    v_counterpart_query := lower(btrim(p_input #>> '{filters,counterpart_query}'));
  END IF;

  IF (p_input->'filters' ? 'max_amount') <> (p_input->'filters' ? 'currency') THEN
    RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
  END IF;

  IF p_input->'filters' ? 'max_amount' THEN
    IF jsonb_typeof(p_input #> '{filters,max_amount}') <> 'number' OR p_input #>> '{filters,max_amount}' !~ '^[0-9]+(?:\.[0-9]+)?$' OR (p_input #>> '{filters,max_amount}')::NUMERIC < 0 OR jsonb_typeof(p_input #> '{filters,currency}') <> 'string' OR p_input #>> '{filters,currency}' !~ '^[A-Z]{3}$' THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    v_max_amount := (p_input #>> '{filters,max_amount}')::NUMERIC;
    v_currency := p_input #>> '{filters,currency}';
  END IF;

  IF p_input->'filters' ? 'airlines' THEN
    IF jsonb_typeof(p_input #> '{filters,airlines}') <> 'array' OR EXISTS (SELECT 1 FROM jsonb_array_elements(p_input #> '{filters,airlines}') AS item WHERE jsonb_typeof(item) <> 'string' OR item #>> '{}' !~ '^[A-Z0-9]{2,3}$') THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    SELECT COALESCE(array_agg(DISTINCT item #>> '{}'), '{}') INTO v_airlines FROM jsonb_array_elements(p_input #> '{filters,airlines}') AS item;
  END IF;

  IF p_input->'filters' ? 'connection_airports' THEN
    IF jsonb_typeof(p_input #> '{filters,connection_airports}') <> 'array' OR EXISTS (SELECT 1 FROM jsonb_array_elements(p_input #> '{filters,connection_airports}') AS item WHERE jsonb_typeof(item) <> 'string' OR item #>> '{}' !~ '^[A-Z0-9]{3}$') THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    SELECT COALESCE(array_agg(DISTINCT item #>> '{}'), '{}') INTO v_connection_airports FROM jsonb_array_elements(p_input #> '{filters,connection_airports}') AS item;
  END IF;

  IF p_input->'filters' ? 'departure_airports' THEN
    IF jsonb_typeof(p_input #> '{filters,departure_airports}') <> 'array' OR EXISTS (SELECT 1 FROM jsonb_array_elements(p_input #> '{filters,departure_airports}') AS item WHERE jsonb_typeof(item) <> 'string' OR item #>> '{}' !~ '^[A-Z0-9]{3}$') THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    SELECT COALESCE(array_agg(DISTINCT item #>> '{}'), '{}') INTO v_departure_airports FROM jsonb_array_elements(p_input #> '{filters,departure_airports}') AS item;
  END IF;

  IF p_input->'filters' ? 'destination_countries' THEN
    IF jsonb_typeof(p_input #> '{filters,destination_countries}') <> 'array' OR EXISTS (SELECT 1 FROM jsonb_array_elements(p_input #> '{filters,destination_countries}') AS item WHERE jsonb_typeof(item) <> 'string' OR item #>> '{}' !~ '^[A-Z]{2}$') THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    SELECT COALESCE(array_agg(DISTINCT item #>> '{}'), '{}') INTO v_destination_countries FROM jsonb_array_elements(p_input #> '{filters,destination_countries}') AS item;
  END IF;

  IF p_input->'filters' ? 'counterpart_countries' THEN
    IF jsonb_typeof(p_input #> '{filters,counterpart_countries}') <> 'array' OR EXISTS (SELECT 1 FROM jsonb_array_elements(p_input #> '{filters,counterpart_countries}') AS item WHERE jsonb_typeof(item) <> 'string' OR item #>> '{}' !~ '^[A-Z]{2}$') THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    SELECT COALESCE(array_agg(DISTINCT item #>> '{}'), '{}') INTO v_counterpart_countries FROM jsonb_array_elements(p_input #> '{filters,counterpart_countries}') AS item;
  END IF;

  IF p_input->'filters' ? 'destination_regions' THEN
    IF jsonb_typeof(p_input #> '{filters,destination_regions}') <> 'array' OR EXISTS (SELECT 1 FROM jsonb_array_elements(p_input #> '{filters,destination_regions}') AS item WHERE jsonb_typeof(item) <> 'string' OR char_length(btrim(item #>> '{}')) NOT BETWEEN 1 AND 80) THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    SELECT COALESCE(array_agg(DISTINCT item #>> '{}'), '{}') INTO v_destination_regions FROM jsonb_array_elements(p_input #> '{filters,destination_regions}') AS item;
  END IF;

  IF p_input->'filters' ? 'counterpart_regions' THEN
    IF jsonb_typeof(p_input #> '{filters,counterpart_regions}') <> 'array' OR EXISTS (SELECT 1 FROM jsonb_array_elements(p_input #> '{filters,counterpart_regions}') AS item WHERE jsonb_typeof(item) <> 'string' OR char_length(btrim(item #>> '{}')) NOT BETWEEN 1 AND 80) THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    SELECT COALESCE(array_agg(DISTINCT item #>> '{}'), '{}') INTO v_counterpart_regions FROM jsonb_array_elements(p_input #> '{filters,counterpart_regions}') AS item;
  END IF;

  IF p_input->'filters' ? 'departure_time_buckets' THEN
    IF jsonb_typeof(p_input #> '{filters,departure_time_buckets}') <> 'array' OR EXISTS (SELECT 1 FROM jsonb_array_elements(p_input #> '{filters,departure_time_buckets}') AS item WHERE jsonb_typeof(item) <> 'string' OR item #>> '{}' NOT IN ('early_morning', 'morning', 'afternoon', 'evening')) THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    SELECT COALESCE(array_agg(DISTINCT item #>> '{}'), '{}') INTO v_departure_time_buckets FROM jsonb_array_elements(p_input #> '{filters,departure_time_buckets}') AS item;
  END IF;

  IF p_input->'filters' ? 'days_of_week' THEN
    IF jsonb_typeof(p_input #> '{filters,days_of_week}') <> 'array' OR EXISTS (SELECT 1 FROM jsonb_array_elements(p_input #> '{filters,days_of_week}') AS item WHERE jsonb_typeof(item) <> 'number' OR item #>> '{}' !~ '^[1-7]$') THEN
      RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid route search request.');
    END IF;
    SELECT COALESCE(array_agg(DISTINCT (item #>> '{}')::INTEGER), '{}') INTO v_days_of_week FROM jsonb_array_elements(p_input #> '{filters,days_of_week}') AS item;
  END IF;

  SELECT version.id INTO v_version_id FROM public.publication_versions AS version WHERE version.is_current = TRUE;
  IF v_version_id IS NULL THEN
    RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_ROUTE_DISCOVERY_UNAVAILABLE', 'No route publication is available.');
  END IF;

  WITH filtered AS (
    SELECT option.*, origin_country.region AS origin_region
    FROM public.flight_route_options AS option
    LEFT JOIN public.countries AS origin_country ON origin_country.iso2 = option.origin_country_code
    WHERE option.publication_version_id = v_version_id
      AND (v_scope_type <> 'origin_city' OR option.origin_city_slug = v_scope_key)
      AND (v_scope_type <> 'origin_airport' OR option.origin_airport_iata = upper(v_scope_key))
      AND (v_scope_type <> 'airport' OR (v_direction = 'from' AND option.origin_airport_iata = upper(v_scope_key)) OR (v_direction = 'to' AND option.destination_airport_iata = upper(v_scope_key)))
      AND (v_scope_type <> 'airport' OR option.stops = 0)
      AND (v_scope_type <> 'city_pair' OR (option.origin_city_slug = v_scope_from AND option.destination_city_slug = v_scope_to))
      AND (v_max_stops IS NULL OR option.stops <= v_max_stops)
      AND (cardinality(v_airlines) = 0 OR option.operating_airlines && v_airlines)
      AND (cardinality(v_connection_airports) = 0 OR option.layover_airports && v_connection_airports)
      AND (cardinality(v_departure_airports) = 0 OR option.origin_airport_iata = ANY(v_departure_airports))
      AND (cardinality(v_destination_countries) = 0 OR option.destination_country_code = ANY(v_destination_countries))
      AND (cardinality(v_destination_regions) = 0 OR option.destination_region = ANY(v_destination_regions))
      AND (v_counterpart_query IS NULL OR (v_direction = 'from' AND (replace(option.destination_city_slug, '-', ' ') ILIKE '%' || v_counterpart_query || '%' OR option.destination_airport_iata ILIKE '%' || v_counterpart_query || '%')) OR (v_direction = 'to' AND (replace(option.origin_city_slug, '-', ' ') ILIKE '%' || v_counterpart_query || '%' OR option.origin_airport_iata ILIKE '%' || v_counterpart_query || '%')))
      AND (cardinality(v_counterpart_countries) = 0 OR (v_direction = 'from' AND option.destination_country_code = ANY(v_counterpart_countries)) OR (v_direction = 'to' AND option.origin_country_code = ANY(v_counterpart_countries)))
      AND (cardinality(v_counterpart_regions) = 0 OR (v_direction = 'from' AND option.destination_region = ANY(v_counterpart_regions)) OR (v_direction = 'to' AND origin_country.region = ANY(v_counterpart_regions)))
      AND (cardinality(v_departure_time_buckets) = 0 OR option.departure_time_buckets && v_departure_time_buckets)
      AND (cardinality(v_days_of_week) = 0 OR option.days_of_week && v_days_of_week)
      AND (v_route_type = 'all' OR (v_route_type = 'domestic' AND option.origin_country_code = option.destination_country_code) OR (v_route_type = 'international' AND option.origin_country_code <> option.destination_country_code))
      AND (v_max_duration_minutes IS NULL OR option.total_duration_minutes <= v_max_duration_minutes)
      AND (v_max_layover_minutes IS NULL OR option.layover_minutes <= v_max_layover_minutes)
      AND (v_cabin = 'any' OR v_cabin = ANY(option.cabins))
      AND (v_max_amount IS NULL OR (option.price_currency = v_currency AND option.price_amount <= v_max_amount))
  ),
  paged AS (
    SELECT filtered.* FROM filtered
    ORDER BY stops ASC, total_duration_minutes ASC, confidence_score DESC, id
    OFFSET v_offset LIMIT v_page_size
  ),
  totals AS (SELECT count(*)::INTEGER AS total FROM filtered)
  SELECT jsonb_build_object(
    'data', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'route_ref', 'route_' || md5(
          origin_airport_iata || ':' || destination_airport_iata || ':' ||
          stops::TEXT || ':' || array_to_string(operating_airlines, ',') || ':' ||
          array_to_string(flight_numbers, ',') || ':' || array_to_string(layover_airports, ',')
        ),
        'from', origin_airport_iata,
        'to', destination_airport_iata,
        'origin_country', origin_country_code,
        'destination_country', destination_country_code,
        'is_international', origin_country_code <> destination_country_code,
        'origin_city_slug', origin_city_slug,
        'destination_city_slug', destination_city_slug,
        'stops', stops,
        'connection_airports', layover_airports,
        'layover_airports', layover_airports,
        'operating_airlines', operating_airlines,
        'flight_numbers', flight_numbers,
        'flight_durations_minutes', flight_durations_minutes,
        'total_flight_minutes', (SELECT COALESCE(sum(duration), 0)::INTEGER FROM unnest(flight_durations_minutes) AS duration),
        'layover_minutes', layover_minutes,
        'total_duration_minutes', total_duration_minutes,
        'total_distance_km', total_distance_km,
        'days_of_week', days_of_week,
        'departure_time_buckets', departure_time_buckets,
        'connection_type', route_type,
        'route_path', route_path,
        'confidence_score', confidence_score,
        'price', CASE WHEN price_amount IS NULL THEN jsonb_build_object('state', 'unavailable', 'reason', 'missing') ELSE jsonb_build_object('state', 'available', 'price_min', price_amount, 'price_max', price_amount, 'currency_code', price_currency) END
      ) ORDER BY stops ASC, total_duration_minutes ASC, confidence_score DESC, id) FROM paged
    ), '[]'::JSONB),
    'meta', jsonb_build_object(
      'data_version', 'v_' || md5(v_version_id::TEXT),
      'total', totals.total,
      'page_size', v_page_size,
      'next_cursor', CASE WHEN v_offset + v_page_size < totals.total THEN 'offset:' || (v_offset + v_page_size)::TEXT ELSE NULL END,
      'facets', jsonb_build_object(
        'stops', COALESCE((SELECT jsonb_agg(jsonb_build_object('value', facet.value, 'count', facet.count)) FROM (SELECT stops::TEXT AS value, count(*)::INTEGER AS count FROM filtered GROUP BY stops ORDER BY stops) AS facet), '[]'::JSONB),
        'airlines', COALESCE((SELECT jsonb_agg(jsonb_build_object('value', facet.value, 'count', facet.count)) FROM (SELECT airline AS value, count(*)::INTEGER AS count FROM filtered, unnest(operating_airlines) AS airline GROUP BY airline ORDER BY airline) AS facet), '[]'::JSONB),
        'connections', COALESCE((SELECT jsonb_agg(jsonb_build_object('value', facet.value, 'count', facet.count)) FROM (SELECT airport AS value, count(*)::INTEGER AS count FROM filtered, unnest(layover_airports) AS airport GROUP BY airport ORDER BY airport) AS facet), '[]'::JSONB),
        'countries', COALESCE((SELECT jsonb_agg(jsonb_build_object('value', facet.value, 'count', facet.count)) FROM (SELECT CASE WHEN v_scope_type = 'airport' AND v_direction = 'to' THEN origin_country_code ELSE destination_country_code END AS value, count(*)::INTEGER AS count FROM filtered GROUP BY 1 ORDER BY 1) AS facet), '[]'::JSONB),
        'regions', COALESCE((SELECT jsonb_agg(jsonb_build_object('value', facet.value, 'count', facet.count)) FROM (SELECT CASE WHEN v_scope_type = 'airport' AND v_direction = 'to' THEN origin_region ELSE destination_region END AS value, count(*)::INTEGER AS count FROM filtered WHERE CASE WHEN v_scope_type = 'airport' AND v_direction = 'to' THEN origin_region IS NOT NULL ELSE destination_region IS NOT NULL END GROUP BY 1 ORDER BY 1) AS facet), '[]'::JSONB)
      )
    ),
    'error', NULL
  ) INTO v_result FROM totals;

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.rpc_search_routes(JSONB) FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_search_routes(JSONB) TO service_role;

-- >>> supabase/sql_src/functions/route_discovery/rpc_suggest_locations.sql

-- ============================================================================
-- Function: public.rpc_suggest_locations
-- Purpose: Autocomplete and suggest airports / cities / nearby hubs by prefix or geo radius.
-- Responsibilities: Provide low-latency location suggestions for the flight search bar.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.rpc_suggest_locations(p_input JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SET search_path = ''
AS $$
DECLARE
  v_query TEXT;
  v_origin_iata TEXT;
  v_radius_km NUMERIC;
  v_limit INTEGER;
  v_origin_lat DOUBLE PRECISION;
  v_origin_lon DOUBLE PRECISION;
  v_origin_city TEXT;
  v_origin_country TEXT;
  v_result JSONB;
BEGIN
  IF jsonb_typeof(p_input) IS DISTINCT FROM 'object' THEN
    RETURN admin.build_rpc_error('[]'::JSONB, 'ERR_INVALID_REQUEST', 'Invalid location suggest request.');
  END IF;

  v_query := NULLIF(btrim(COALESCE(p_input->>'query', '')), '');
  v_origin_iata := upper(NULLIF(btrim(COALESCE(p_input->>'origin_iata', '')), ''));
  v_radius_km := COALESCE((p_input->>'radius_km')::NUMERIC, 300);
  v_limit := LEAST(GREATEST(COALESCE((p_input->>'limit')::INTEGER, 10), 1), 50);

  -- Retrieve origin airport coordinates if origin_iata is specified
  IF v_origin_iata IS NOT NULL THEN
    SELECT a.latitude, a.longitude, c.name, co.name
    INTO v_origin_lat, v_origin_lon, v_origin_city, v_origin_country
    FROM public.airports a
    LEFT JOIN public.cities c ON c.id = a.city_id
    JOIN public.countries co ON co.id = a.country_id
    WHERE a.iata = v_origin_iata
    LIMIT 1;
  END IF;

  -- 1. If query is empty and origin is provided -> list origin and nearby airports within radius
  IF v_query IS NULL AND v_origin_lat IS NOT NULL AND v_origin_lon IS NOT NULL THEN
    WITH calculated AS (
      SELECT
        a.iata,
        a.name AS airport_name,
        COALESCE(c.name, a.name) AS city_name,
        c.slug AS city_slug,
        co.name AS country_name,
        co.iso2 AS country_iso2,
        a.latitude,
        a.longitude,
        CASE
          WHEN a.iata = v_origin_iata THEN 0
          ELSE (
            6371 * 2 * asin(
              sqrt(
                power(sin(radians(a.latitude - v_origin_lat) / 2), 2) +
                cos(radians(v_origin_lat)) * cos(radians(a.latitude)) *
                power(sin(radians(a.longitude - v_origin_lon) / 2), 2)
              )
            )
          )
        END AS distance_km
      FROM public.airports a
      LEFT JOIN public.cities c ON c.id = a.city_id
      JOIN public.countries co ON co.id = a.country_id
      WHERE a.iata IS NOT NULL
        AND a.latitude IS NOT NULL
        AND a.longitude IS NOT NULL
        AND a.status = 'active'
    ),
    nearby_filtered AS (
      SELECT *
      FROM calculated
      WHERE distance_km <= v_radius_km
      ORDER BY distance_km ASC
      LIMIT v_limit
    )
    SELECT jsonb_build_object(
      'data', COALESCE(jsonb_agg(jsonb_build_object(
        'type', 'airport',
        'iata', iata,
        'name', airport_name,
        'city_name', city_name,
        'city_slug', city_slug,
        'country_name', country_name,
        'country_iso2', country_iso2,
        'distance_km', round(distance_km::numeric),
        'subtitle', CASE
          WHEN distance_km = 0 THEN country_name
          ELSE round(distance_km::numeric)::text || ' km from ' || v_origin_city || ', ' || v_origin_country
        END,
        'latitude', latitude,
        'longitude', longitude
      )), '[]'::JSONB)
    ) INTO v_result
    FROM nearby_filtered;

    RETURN v_result;
  END IF;

  -- 2. If query is provided -> prefix and substring search on IATA, City, Airport, Country
  WITH airport_matches AS (
    SELECT
      a.iata,
      a.name AS airport_name,
      COALESCE(c.name, a.name) AS city_name,
      c.slug AS city_slug,
      co.name AS country_name,
      co.iso2 AS country_iso2,
      a.latitude,
      a.longitude,
      CASE
        WHEN a.iata ILIKE v_query || '%' THEN 1
        WHEN c.name ILIKE v_query || '%' THEN 2
        WHEN a.name ILIKE v_query || '%' THEN 3
        ELSE 4
      END AS match_rank
    FROM public.airports a
    LEFT JOIN public.cities c ON c.id = a.city_id
    JOIN public.countries co ON co.id = a.country_id
    WHERE a.iata IS NOT NULL
      AND a.status = 'active'
      AND (
        a.iata ILIKE '%' || v_query || '%'
        OR a.name ILIKE '%' || v_query || '%'
        OR c.name ILIKE '%' || v_query || '%'
        OR co.name ILIKE '%' || v_query || '%'
      )
    ORDER BY match_rank ASC, a.name ASC
    LIMIT v_limit
  )
  SELECT jsonb_build_object(
    'data', COALESCE(jsonb_agg(jsonb_build_object(
      'type', 'airport',
      'iata', iata,
      'name', airport_name,
      'city_name', city_name,
      'city_slug', city_slug,
      'country_name', country_name,
      'country_iso2', country_iso2,
      'subtitle', country_name,
      'latitude', latitude,
      'longitude', longitude
    )), '[]'::JSONB)
  ) INTO v_result
  FROM airport_matches;

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.rpc_suggest_locations(JSONB) FROM public;
GRANT EXECUTE ON FUNCTION public.rpc_suggest_locations(JSONB) TO anon, authenticated, service_role;
