-- ============================================================================
-- Migration: 20260714080300_route_discovery_schema.sql
-- Source of truth: supabase/sql_src
-- Feature: route discovery schema
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/schema/pseo/shared/publication_versions.sql

-- Table: public.publication_versions
-- Feature: Shared Read Models
-- Purpose: Track atomic candidate and current read-model publications.

CREATE TABLE public.publication_versions (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  status         TEXT         NOT NULL DEFAULT 'building',
  is_current     BOOLEAN      NOT NULL DEFAULT FALSE,
  source_type    TEXT         NOT NULL,
  started_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  published_at   TIMESTAMPTZ  NULL,
  failure_code   TEXT         NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

  CONSTRAINT publication_versions_status_check
    CHECK (status IN ('building', 'published', 'failed', 'retired')),

  CONSTRAINT publication_versions_source_check
    CHECK (source_type IN ('production', 'staging', 'development_fixture')),

  CONSTRAINT publication_versions_current_check
    CHECK (is_current = FALSE OR (status = 'published' AND published_at IS NOT NULL)),

  CONSTRAINT publication_versions_failure_check
    CHECK ((status = 'failed') = (failure_code IS NOT NULL))
);

CREATE UNIQUE INDEX publication_versions_one_current_idx
ON public.publication_versions USING btree (is_current)
WHERE is_current = TRUE;

ALTER TABLE public.publication_versions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.publication_versions FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.publication_versions TO service_role;

-- >>> supabase/sql_src/schema/route_discovery/flight_route_options.sql

-- Table: public.flight_route_options
-- Feature: Flight Route Discovery
-- Purpose: Pre-computed, versioned read projection of 0-stop direct and 1-stop connecting routes.
-- Responsibilities: Provide fast, indexable search and pSEO payload aggregation without real-time graph traversal.

CREATE TABLE public.flight_route_options (
  id                        UUID              NOT NULL DEFAULT gen_random_uuid(),
  publication_version_id    UUID              NOT NULL REFERENCES public.publication_versions (id) ON DELETE CASCADE,
  origin_city_id            UUID              NOT NULL REFERENCES public.cities (id),
  origin_city_slug          TEXT              NOT NULL,
  origin_country_code       TEXT              NOT NULL,
  destination_city_id       UUID              NOT NULL REFERENCES public.cities (id),
  destination_city_slug     TEXT              NOT NULL,
  destination_country_code  TEXT              NOT NULL,
  origin_airport_id         UUID              NOT NULL REFERENCES public.airports (id),
  origin_airport_iata       TEXT              NOT NULL,
  destination_airport_id    UUID              NOT NULL REFERENCES public.airports (id),
  destination_airport_iata  TEXT              NOT NULL,
  stops                     INTEGER           NOT NULL DEFAULT 0,
  layover_airport_ids       UUID[]            NOT NULL DEFAULT '{}',
  layover_airports          TEXT[]            NOT NULL DEFAULT '{}',
  operating_airlines        TEXT[]            NOT NULL DEFAULT '{}',
  flight_numbers            TEXT[]            NOT NULL DEFAULT '{}',
  flight_durations_minutes  INTEGER[]         NOT NULL DEFAULT '{}',
  total_duration_minutes    INTEGER           NOT NULL DEFAULT 0,
  total_distance_km         INTEGER           NOT NULL DEFAULT 0,
  days_of_week              INTEGER[]         NOT NULL DEFAULT '{1,2,3,4,5,6,7}',
  route_type                TEXT              NOT NULL DEFAULT 'direct',
  confidence_score          NUMERIC(4,3)      NOT NULL DEFAULT 1.000,
  route_path                TEXT              NULL,
  created_at                TIMESTAMPTZ       NOT NULL DEFAULT now(),

  PRIMARY KEY (publication_version_id, id),

  CONSTRAINT flight_route_options_direction_check
    CHECK (origin_city_id <> destination_city_id),

  CONSTRAINT flight_route_options_stops_check
    CHECK (stops IN (0, 1)),

  CONSTRAINT flight_route_options_route_type_check
    CHECK (route_type IN ('direct', 'same_airline', 'alliance', 'self_transfer'))
);

CREATE INDEX flight_route_options_origin_idx ON public.flight_route_options
  (publication_version_id, origin_city_slug, confidence_score DESC, id);

CREATE INDEX flight_route_options_pair_idx ON public.flight_route_options
  (publication_version_id, origin_city_slug, destination_city_slug, stops, total_duration_minutes);

CREATE INDEX flight_route_options_airport_pair_idx ON public.flight_route_options
  (publication_version_id, origin_airport_iata, destination_airport_iata, stops);

ALTER TABLE public.flight_route_options ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.flight_route_options FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.flight_route_options TO service_role;
