-- ============================================================================
-- Migration: 20260714080900_pseo_functions.sql
-- Source of truth: supabase/sql_src
-- Feature: pSEO functions
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/functions/pseo/city/parse_city_page_identity.sql

-- ============================================================================
-- Function: private.parse_city_page_identity
-- Feature: Interactive pSEO
-- Purpose: Validate and normalize the city-page identity shared by pSEO read RPCs.
-- Responsibilities: Validate the JSON object, city slug, and locale contract.
-- Notes: This helper does not query page data or validate RPC-specific filters.
-- ============================================================================

CREATE OR REPLACE FUNCTION private.parse_city_page_identity(p_input JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_city_slug TEXT;
  v_locale TEXT;
  v_route_direction TEXT;
BEGIN
  IF p_input IS NULL OR jsonb_typeof(p_input) <> 'object' THEN
    RETURN jsonb_build_object(
      'data', NULL,
      'error', jsonb_build_object(
        'code', 'ERR_INVALID_REQUEST',
        'message', 'Request must be a JSON object.'
      )
    );
  END IF;

  v_city_slug := lower(btrim(COALESCE(p_input->>'city_slug', '')));
  v_locale := btrim(COALESCE(p_input->>'locale', 'en-GB'));
  v_route_direction := lower(btrim(COALESCE(p_input->>'route_direction', 'outbound')));

  IF v_city_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
    OR v_locale !~ '^[a-z]{2}(?:-[A-Z]{2})?$'
    OR v_route_direction NOT IN ('outbound', 'inbound')
  THEN
    RETURN jsonb_build_object(
      'data', NULL,
      'error', jsonb_build_object(
        'code', 'ERR_INVALID_REQUEST',
        'message', 'City slug or locale is invalid.'
      )
    );
  END IF;

  RETURN jsonb_build_object(
    'data', jsonb_build_object(
      'city_slug', v_city_slug,
      'locale', v_locale,
      'route_direction', v_route_direction
    ),
    'error', NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION private.parse_city_page_identity(JSONB)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.parse_city_page_identity(JSONB) TO service_role;

-- >>> supabase/sql_src/functions/pseo/city/resolve_city_page_context.sql

-- ============================================================================
-- Function: private.resolve_city_page_context
-- Feature: Interactive pSEO
-- Purpose: Resolve the reviewed city-page identity shared by pSEO read RPCs.
-- Responsibilities: Resolve city, city page, pSEO page, and published data version identifiers.
-- Notes: Inputs must already be normalized by private.parse_city_page_identity.
-- ============================================================================

CREATE OR REPLACE FUNCTION private.resolve_city_page_context(
  p_city_slug TEXT,
  p_locale TEXT,
  p_route_direction TEXT DEFAULT 'outbound'
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_city_id UUID;
  v_city_page_id UUID;
  v_pseo_page_id UUID;
BEGIN
  SELECT
    city_page.city_id,
    city_page.id,
    city_page.pseo_page_id
  INTO
    v_city_id,
    v_city_page_id,
    v_pseo_page_id
  FROM public.city_pages AS city_page
  JOIN public.pseo_pages AS registry
    ON registry.id = city_page.pseo_page_id
  WHERE registry.entity_key = p_city_slug
    AND registry.page_type = 'city'
    AND city_page.locale = p_locale
    AND city_page.route_direction = p_route_direction;

  IF v_city_page_id IS NULL THEN
    RETURN jsonb_build_object(
      'data', NULL,
      'error', jsonb_build_object(
        'code', 'ERR_CITY_PAGE_NOT_FOUND',
        'message', 'City page was not found.'
      )
    );
  END IF;

  RETURN jsonb_build_object(
    'data', jsonb_build_object(
      'city_id', v_city_id,
      'city_page_id', v_city_page_id,
      'pseo_page_id', v_pseo_page_id,
      'route_direction', p_route_direction
    ),
    'error', NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION private.resolve_city_page_context(TEXT, TEXT, TEXT)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.resolve_city_page_context(TEXT, TEXT, TEXT) TO service_role;

-- >>> supabase/sql_src/functions/pseo/airport/parse_airport_page_identity.sql

-- ============================================================================
-- Function: private.parse_airport_page_identity
-- Feature: Interactive pSEO
-- Purpose: Validate and normalize airport-page identity for public read RPCs.
-- Responsibilities: Validate JSON input, IATA code, and locale.
-- ============================================================================

CREATE OR REPLACE FUNCTION private.parse_airport_page_identity(p_input JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_airport_iata TEXT;
  v_locale TEXT;
BEGIN
  IF p_input IS NULL OR jsonb_typeof(p_input) <> 'object' THEN
    RETURN jsonb_build_object(
      'data', NULL,
      'error', jsonb_build_object(
        'code', 'ERR_INVALID_REQUEST',
        'message', 'Request must be a JSON object.'
      )
    );
  END IF;

  v_airport_iata := upper(btrim(COALESCE(p_input->>'airport_iata', '')));
  v_locale := btrim(COALESCE(p_input->>'locale', 'en-GB'));

  IF v_airport_iata !~ '^[A-Z]{3}$'
    OR v_locale !~ '^[a-z]{2}(?:-[A-Z]{2})?$'
  THEN
    RETURN jsonb_build_object(
      'data', NULL,
      'error', jsonb_build_object(
        'code', 'ERR_INVALID_REQUEST',
        'message', 'Airport IATA code or locale is invalid.'
      )
    );
  END IF;

  RETURN jsonb_build_object(
    'data', jsonb_build_object(
      'airport_iata', v_airport_iata,
      'locale', v_locale
    ),
    'error', NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION private.parse_airport_page_identity(JSONB)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.parse_airport_page_identity(JSONB) TO service_role;

-- >>> supabase/sql_src/functions/pseo/airport/resolve_airport_page_context.sql

-- ============================================================================
-- Function: private.resolve_airport_page_context
-- Feature: Interactive pSEO
-- Purpose: Resolve normalized airport and localized page identity.
-- Responsibilities: Return IDs and the current published read-model version.
-- ============================================================================

CREATE OR REPLACE FUNCTION private.resolve_airport_page_context(
  p_airport_iata TEXT,
  p_locale TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_airport_id UUID;
  v_city_id UUID;
  v_country_id UUID;
  v_airport_page_id UUID;
  v_pseo_page_id UUID;
BEGIN
  SELECT
    airport.id,
    airport.city_id,
    airport.country_id
  INTO
    v_airport_id,
    v_city_id,
    v_country_id
  FROM public.airports airport
  WHERE airport.iata = p_airport_iata;

  IF v_airport_id IS NULL THEN
    RETURN jsonb_build_object(
      'data', NULL,
      'error', jsonb_build_object(
        'code', 'ERR_AIRPORT_NOT_FOUND',
        'message', 'Airport was not found.'
      )
    );
  END IF;

  SELECT
    airport_page.id,
    airport_page.pseo_page_id
  INTO
    v_airport_page_id,
    v_pseo_page_id
  FROM public.airport_pages airport_page
  WHERE airport_page.airport_id = v_airport_id
    AND airport_page.locale = p_locale;

  IF v_airport_page_id IS NULL THEN
    RETURN jsonb_build_object(
      'data', NULL,
      'error', jsonb_build_object(
        'code', 'ERR_AIRPORT_PAGE_NOT_FOUND',
        'message', 'Airport page was not found.'
      )
    );
  END IF;

  RETURN jsonb_build_object(
    'data', jsonb_build_object(
      'airport_id', v_airport_id,
      'airport_page_id', v_airport_page_id,
      'pseo_page_id', v_pseo_page_id,
      'city_id', v_city_id,
      'country_id', v_country_id
    ),
    'error', NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION private.resolve_airport_page_context(TEXT, TEXT)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.resolve_airport_page_context(TEXT, TEXT) TO service_role;

-- >>> supabase/sql_src/functions/pseo/city/build_city_page_payload.sql

CREATE OR REPLACE FUNCTION private.build_city_page_payload(p_input JSONB)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY INVOKER SET search_path = '' AS $$
DECLARE
  v_slug TEXT := lower(p_input->>'city_slug');
  v_locale TEXT := COALESCE(NULLIF(p_input->>'locale',''),'en-GB');
  v_direction TEXT := COALESCE(NULLIF(p_input->>'route_direction',''),'outbound');
  v_version UUID := (p_input->>'publication_version_id')::UUID;
  v_page public.city_pages%ROWTYPE;
  v_city public.cities%ROWTYPE;
  v_registry public.pseo_pages%ROWTYPE;
BEGIN
  SELECT page.* INTO v_page FROM public.city_pages page JOIN public.pseo_pages registry ON registry.id=page.pseo_page_id
  WHERE registry.entity_key=v_slug AND page.locale=v_locale AND page.route_direction=v_direction;
  IF v_page.id IS NULL THEN RETURN private.build_rpc_error(NULL,'ERR_NOT_FOUND','City page not found.'); END IF;
  SELECT * INTO v_city FROM public.cities WHERE id=v_page.city_id;
  SELECT * INTO v_registry FROM public.pseo_pages WHERE id=v_page.pseo_page_id;
  RETURN jsonb_build_object('data',jsonb_build_object(
    'city',jsonb_build_object('id',v_city.id,'name',v_city.name,'slug',v_city.slug,'iata_code',v_city.iata_code,
      'timezone',v_city.timezone,'currency_code',v_city.currency_code,'primary_language',v_city.primary_language),
    'content',v_page.content,
    'routes',COALESCE((SELECT jsonb_agg(to_jsonb(option) ORDER BY option.confidence_score DESC) FROM public.flight_route_options option
      WHERE option.publication_version_id=v_version AND ((v_direction='outbound' AND option.origin_city_id=v_city.id) OR (v_direction='inbound' AND option.destination_city_id=v_city.id))),'[]'::jsonb)
  ),'meta',jsonb_build_object('canonical_path',v_registry.canonical_path,'is_indexable',v_registry.is_indexable,
    'noindex_reason',v_registry.noindex_reason,'data_version',v_version,'source_freshness_at',v_registry.source_freshness_at),'error',NULL);
END; $$;
REVOKE ALL ON FUNCTION private.build_city_page_payload(JSONB) FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.build_city_page_payload(JSONB) TO service_role;

-- >>> supabase/sql_src/functions/pseo/airport/build_airport_page_payload.sql

CREATE OR REPLACE FUNCTION private.build_airport_page_payload(p_input JSONB)
RETURNS JSONB LANGUAGE plpgsql STABLE SECURITY INVOKER SET search_path = '' AS $$
DECLARE
  v_iata TEXT := upper(p_input->>'airport_iata');
  v_locale TEXT := COALESCE(NULLIF(p_input->>'locale',''),'en-GB');
  v_version UUID := (p_input->>'publication_version_id')::UUID;
  v_page public.airport_pages%ROWTYPE;
  v_airport public.airports%ROWTYPE;
  v_registry public.pseo_pages%ROWTYPE;
BEGIN
  SELECT page.* INTO v_page FROM public.airport_pages page JOIN public.airports airport ON airport.id=page.airport_id
  WHERE airport.iata=v_iata AND page.locale=v_locale;
  IF v_page.id IS NULL THEN RETURN private.build_rpc_error(NULL,'ERR_NOT_FOUND','Airport page not found.'); END IF;
  SELECT * INTO v_airport FROM public.airports WHERE id=v_page.airport_id;
  SELECT * INTO v_registry FROM public.pseo_pages WHERE id=v_page.pseo_page_id;
  RETURN jsonb_build_object('data',jsonb_build_object(
    'airport',jsonb_build_object('id',v_airport.id,'iata',v_airport.iata,'icao',v_airport.icao,'name',v_airport.name,
      'slug',v_airport.slug,'image_path',v_airport.image_path,'timezone',v_airport.timezone),
    'content',v_page.content,
    'routes',COALESCE((SELECT jsonb_agg(to_jsonb(option) ORDER BY option.confidence_score DESC) FROM public.flight_route_options option
      WHERE option.publication_version_id=v_version AND (option.origin_airport_id=v_airport.id OR option.destination_airport_id=v_airport.id)),'[]'::jsonb)
  ),'meta',jsonb_build_object('canonical_path',v_registry.canonical_path,'is_indexable',v_registry.is_indexable,
    'noindex_reason',v_registry.noindex_reason,'data_version',v_version,'source_freshness_at',v_registry.source_freshness_at),'error',NULL);
END; $$;
REVOKE ALL ON FUNCTION private.build_airport_page_payload(JSONB) FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.build_airport_page_payload(JSONB) TO service_role;

-- >>> supabase/sql_src/functions/pseo/shared/resolve_route_price_estimate.sql

-- Resolve a display-safe estimate or an explicit null-state. Never substitutes zero.
CREATE OR REPLACE FUNCTION public.resolve_route_price_estimate(
  p_origin_city_id UUID,p_destination_city_id UUID,p_cabin TEXT DEFAULT 'any',p_stop_bucket TEXT DEFAULT 'any'
) RETURNS JSONB LANGUAGE plpgsql STABLE SET search_path='' AS $$
DECLARE v_row RECORD; v_any RECORD;
BEGIN
  SELECT estimate.*,source.production_display_allowed,source.derived_data_allowed,
    source.rights_effective_at,source.rights_expires_at,source.attribution_text,source.attribution_url
  INTO v_any FROM public.flight_content_observations estimate
  JOIN admin.data_sources source ON source.id=estimate.source_id
  WHERE estimate.origin_city_id=p_origin_city_id AND estimate.destination_city_id=p_destination_city_id
  ORDER BY estimate.observed_at DESC LIMIT 1;
  IF v_any.id IS NULL THEN RETURN jsonb_build_object('state','unavailable','reason','missing','estimate',NULL); END IF;
  IF NOT v_any.production_display_allowed OR NOT v_any.derived_data_allowed
    OR (v_any.rights_effective_at IS NOT NULL AND now() NOT BETWEEN v_any.rights_effective_at AND v_any.rights_expires_at)
  THEN RETURN jsonb_build_object('state','unavailable','reason','unlicensed','estimate',NULL); END IF;
  IF v_any.status <> 'published' OR v_any.valid_until <= now()
  THEN RETURN jsonb_build_object('state','unavailable','reason','expired','estimate',NULL); END IF;
  v_row := v_any;
  RETURN jsonb_build_object('state','available','reason',NULL,'observation',jsonb_build_object(
    'observed_amount',v_row.observed_amount,'currency_code',v_row.currency_code,
    'trip_type',v_row.trip_type,'direct',v_row.direct,'transfer_count',v_row.transfer_count,
    'departure_date',v_row.departure_date,'return_date',v_row.return_date,
    'observed_at',v_row.observed_at,'valid_until',v_row.valid_until,
    'disclaimer','Cached affiliate fare observed earlier; availability and final price are confirmed by the booking partner.',
    'attribution_text',v_row.attribution_text,'attribution_url',v_row.attribution_url
  ));
END;
$$;
REVOKE ALL ON FUNCTION public.resolve_route_price_estimate(UUID,UUID,TEXT,TEXT) FROM public,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.resolve_route_price_estimate(UUID,UUID,TEXT,TEXT) TO service_role;

-- >>> supabase/sql_src/functions/pseo/shared/rpc_get_flight_affiliate_handoff.sql

-- Resolve a current observation into an allowlisted Aviasales handoff URL.
-- The browser never supplies a destination host.
CREATE OR REPLACE FUNCTION public.rpc_get_flight_affiliate_handoff(p_observation_id UUID)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path=''
AS $$
  SELECT CASE
    WHEN observation.id IS NULL OR source.id IS NULL THEN jsonb_build_object('data',NULL,'error',jsonb_build_object('code','ERR_HANDOFF_UNAVAILABLE'))
    ELSE jsonb_build_object(
      'data',jsonb_build_object(
        'url','https://www.aviasales.com' || observation.affiliate_path,
        'expires_at',observation.valid_until,
        'disclosure','Tripways may earn a commission if you book through this link. Final price and availability are confirmed by Aviasales.'
      ),
      'error',NULL
    )
  END
  FROM (SELECT p_observation_id AS requested_id) input
  LEFT JOIN public.flight_content_observations observation
    ON observation.id=input.requested_id
   AND observation.status='published'
   AND observation.valid_until>now()
   AND observation.affiliate_path IS NOT NULL
  LEFT JOIN admin.data_sources source
    ON source.id=observation.source_id
   AND source.provider_code='travelpayouts'
  ;
$$;

REVOKE ALL ON FUNCTION public.rpc_get_flight_affiliate_handoff(UUID) FROM public;
GRANT EXECUTE ON FUNCTION public.rpc_get_flight_affiliate_handoff(UUID) TO anon,authenticated,service_role;

-- >>> supabase/sql_src/functions/pseo/homepage/rpc_search_places.sql

-- Search only entities present in the currently published canonical projection.
CREATE OR REPLACE FUNCTION public.rpc_search_places(p_input JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SET search_path = ''
AS $$
DECLARE
  v_query TEXT := lower(btrim(COALESCE(p_input ->> 'query', '')));
  v_locale TEXT := COALESCE(NULLIF(p_input ->> 'locale', ''), 'en-GB');
  v_limit INTEGER := COALESCE((p_input ->> 'limit')::INTEGER, 8);
  v_version_id UUID;
BEGIN
  IF char_length(v_query) < 1 OR v_limit NOT BETWEEN 1 AND 20 THEN
    RETURN private.build_rpc_error(NULL, 'ERR_INVALID_REQUEST', 'Invalid place search.');
  END IF;

  SELECT version.id INTO v_version_id
  FROM public.publication_versions AS version
  WHERE version.is_current = TRUE AND version.status = 'published';

  RETURN jsonb_build_object(
    'data', COALESCE((
      SELECT jsonb_agg(to_jsonb(result) ORDER BY result.rank_score DESC, result.name)
      FROM (
        SELECT * FROM (
          SELECT DISTINCT ON (city.id)
            'city'::TEXT AS entity_type,
            city.id,
            city.name,
            option.origin_city_slug AS code,
            option.origin_city_slug AS slug,
            CASE WHEN option.origin_city_slug = v_query THEN 2 ELSE 1 END::NUMERIC AS rank_score
          FROM public.flight_route_options AS option
          JOIN public.cities AS city ON city.id = option.origin_city_id
          WHERE option.publication_version_id = v_version_id
            AND (lower(city.name) LIKE '%' || v_query || '%'
              OR option.origin_city_slug LIKE '%' || v_query || '%')
          ORDER BY city.id, option.origin_city_slug
        ) AS cities
        UNION ALL
        SELECT * FROM (
          SELECT DISTINCT ON (airport.id)
            'airport'::TEXT,
            airport.id,
            airport.name,
            airport.iata,
            lower(airport.iata),
            CASE WHEN lower(airport.iata) = v_query THEN 2 ELSE 1 END::NUMERIC
          FROM public.flight_route_options AS option
          JOIN public.airports AS airport ON airport.id = option.origin_airport_id
          WHERE option.publication_version_id = v_version_id
            AND (lower(airport.name) LIKE '%' || v_query || '%'
              OR lower(airport.iata) LIKE v_query || '%')
          ORDER BY airport.id
        ) AS airports
      ) AS result
      LIMIT v_limit
    ), '[]'::JSONB),
    'meta', jsonb_build_object(
      'query', v_query,
      'locale', v_locale,
      'limit', v_limit,
      'data_version', v_version_id
    ),
    'error', NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION public.rpc_search_places(JSONB) FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_search_places(JSONB) TO service_role;

-- >>> supabase/sql_src/functions/pseo/homepage/rpc_resolve_homepage_origin.sql

-- ============================================================================
-- Function: public.rpc_resolve_homepage_origin
-- Feature: Homepage Discovery
-- Purpose: Resolve the nearest route-capable airport from visitor coordinates.
-- Responsibilities: Validate coordinates, rank eligible airports, and fall back to JFK.
-- Notes: Raw IP addresses never enter this function or the database.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.rpc_resolve_homepage_origin(p_input JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  ------------------------------------------------------------------
  -- Input
  ------------------------------------------------------------------
  v_latitude DOUBLE PRECISION;
  v_longitude DOUBLE PRECISION;
  v_has_valid_coordinates BOOLEAN := FALSE;

  ------------------------------------------------------------------
  -- Resolved origin
  ------------------------------------------------------------------
  v_airport RECORD;
  v_resolution TEXT := 'fallback';
  v_version_id UUID;
BEGIN
  SELECT id INTO v_version_id
  FROM public.publication_versions
  WHERE is_current = TRUE AND status = 'published';

  -- STEP 01: Accept only finite, bounded numeric coordinate pairs.
  IF jsonb_typeof(p_input) = 'object'
    AND jsonb_typeof(p_input -> 'latitude') = 'number'
    AND jsonb_typeof(p_input -> 'longitude') = 'number'
  THEN
    v_latitude := (p_input ->> 'latitude')::DOUBLE PRECISION;
    v_longitude := (p_input ->> 'longitude')::DOUBLE PRECISION;
    v_has_valid_coordinates := v_latitude BETWEEN -90 AND 90
      AND v_longitude BETWEEN -180 AND 180;
  END IF;

  -- STEP 02: Rank active airports that can actually originate a route.
  IF v_has_valid_coordinates THEN
    SELECT
      airport.iata,
      airport.name,
      airport.latitude,
      airport.longitude,
      city.name AS city_name,
      route_origin.origin_city_slug AS city_slug,
      6371 * acos(
        LEAST(
          1,
          GREATEST(
            -1,
            cos(radians(v_latitude))
              * cos(radians(airport.latitude))
              * cos(radians(airport.longitude) - radians(v_longitude))
              + sin(radians(v_latitude))
              * sin(radians(airport.latitude))
          )
        )
      ) AS distance_km,
      (
        SELECT count(*)::INTEGER
        FROM public.flight_route_options route_option
        WHERE route_option.publication_version_id = v_version_id
          AND route_option.origin_airport_id = airport.id
      ) AS route_count
    INTO v_airport
    FROM public.airports airport
    JOIN public.cities city
      ON city.id = airport.city_id
    JOIN LATERAL (
      SELECT option.origin_city_slug
      FROM public.flight_route_options option
      WHERE option.publication_version_id = v_version_id
        AND option.origin_airport_id = airport.id
      ORDER BY option.origin_city_slug
      LIMIT 1
    ) route_origin ON TRUE
    WHERE airport.status = 'active'
      AND airport.iata IS NOT NULL
      AND airport.latitude IS NOT NULL
      AND airport.longitude IS NOT NULL
      AND EXISTS (
        SELECT 1
        FROM public.flight_route_options route_option
        WHERE route_option.publication_version_id = v_version_id
          AND route_option.origin_airport_id = airport.id
      )
    ORDER BY distance_km, airport.iata
    LIMIT 1;

    IF FOUND THEN
      v_resolution := 'nearest';
    END IF;
  END IF;

  -- STEP 03: Use the explicit JFK fallback when geolocation cannot resolve.
  IF v_resolution = 'fallback' THEN
    SELECT
      airport.iata,
      airport.name,
      airport.latitude,
      airport.longitude,
      city.name AS city_name,
      route_origin.origin_city_slug AS city_slug,
      NULL::DOUBLE PRECISION AS distance_km,
      (
        SELECT count(*)::INTEGER
        FROM public.flight_route_options route_option
        WHERE route_option.publication_version_id = v_version_id
          AND route_option.origin_airport_id = airport.id
      ) AS route_count
    INTO v_airport
    FROM public.airports airport
    LEFT JOIN public.cities city
      ON city.id = airport.city_id
    LEFT JOIN LATERAL (
      SELECT option.origin_city_slug
      FROM public.flight_route_options option
      WHERE option.publication_version_id = v_version_id
        AND option.origin_airport_id = airport.id
      ORDER BY option.origin_city_slug
      LIMIT 1
    ) route_origin ON TRUE
    WHERE airport.iata = 'JFK';
  END IF;

  RETURN jsonb_build_object(
    'data', jsonb_build_object(
      'airport', jsonb_build_object(
        'iata', COALESCE(v_airport.iata, 'JFK'),
        'name', v_airport.name,
        'latitude', v_airport.latitude,
        'longitude', v_airport.longitude
      ),
      'city', CASE
        WHEN v_airport.city_slug IS NULL THEN NULL
        ELSE jsonb_build_object(
          'name', v_airport.city_name,
          'slug', v_airport.city_slug
        )
      END,
      'distance_km', CASE
        WHEN v_airport.distance_km IS NULL THEN NULL
        ELSE round(v_airport.distance_km::NUMERIC, 1)
      END,
      'route_count', COALESCE(v_airport.route_count, 0)
    ),
    'meta', jsonb_build_object(
      'resolution', v_resolution,
      'fallback_iata', 'JFK',
      'fallback_data_available', v_airport.iata = 'JFK'
    ),
    'error', NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION public.rpc_resolve_homepage_origin(JSONB)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_resolve_homepage_origin(JSONB) TO service_role;

-- >>> supabase/sql_src/functions/pseo/homepage/rpc_get_homepage_statistics.sql

-- ============================================================================
-- Function: public.rpc_get_homepage_statistics
-- Purpose: Return current canonical route coverage for the product homepage.
-- Responsibilities: Aggregate bounded data points directly from the current publication.
-- Notes: Homepage copy and layout remain frontend-owned.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.rpc_get_homepage_statistics()
RETURNS JSONB
LANGUAGE sql
STABLE
SET search_path = ''
AS $$
  SELECT jsonb_build_object(
    'data', jsonb_build_object(
      'origin_city_count', count(DISTINCT option.origin_city_id)::INTEGER,
      'origin_airport_count', count(DISTINCT option.origin_airport_id)::INTEGER,
      'published_direct_route_count', count(DISTINCT option.route_path)::INTEGER
    ),
    'meta', jsonb_build_object(
      'data_version', version.id,
      'generated_at', version.published_at
    ),
    'error', NULL
  )
  FROM public.publication_versions AS version
  LEFT JOIN public.flight_route_options AS option
    ON option.publication_version_id = version.id
  WHERE version.is_current = TRUE
    AND version.status = 'published'
  GROUP BY version.id, version.published_at;
$$;

REVOKE ALL ON FUNCTION public.rpc_get_homepage_statistics()
FROM public;
GRANT EXECUTE ON FUNCTION public.rpc_get_homepage_statistics()
TO anon, authenticated, service_role;

-- >>> supabase/sql_src/functions/pseo/route/build_route_page_payload.sql

CREATE OR REPLACE FUNCTION private.build_route_page_payload(p_input JSONB)
RETURNS JSONB LANGUAGE plpgsql STABLE SET search_path = '' AS $$
DECLARE
  v_locale TEXT := COALESCE(NULLIF(p_input->>'locale', ''), 'en-GB');
  v_page public.route_pages%ROWTYPE;
  v_registry public.pseo_pages%ROWTYPE;
  v_version UUID := (p_input->>'publication_version_id')::UUID;
BEGIN
  SELECT page.* INTO v_page
  FROM public.route_pages page
  JOIN public.pseo_pages registry ON registry.id = page.pseo_page_id
  WHERE registry.entity_key = lower(p_input->>'route_slug') AND page.locale = v_locale;
  IF v_page.id IS NULL THEN RETURN private.build_rpc_error(NULL, 'ERR_NOT_FOUND', 'Route page not found.'); END IF;
  SELECT * INTO v_registry FROM public.pseo_pages WHERE id = v_page.pseo_page_id;

  RETURN jsonb_build_object(
    'data', jsonb_build_object(
      'route', jsonb_build_object(
        'origin', (SELECT jsonb_build_object('id',id,'name',name,'slug',slug,'iata_code',iata_code) FROM public.cities WHERE id=v_page.origin_city_id),
        'destination', (SELECT jsonb_build_object('id',id,'name',name,'slug',slug,'iata_code',iata_code) FROM public.cities WHERE id=v_page.destination_city_id)
      ),
      'content', v_page.content,
      'route_options', COALESCE((SELECT jsonb_agg(jsonb_build_object(
        'from',origin_airport_iata,'to',destination_airport_iata,'airline',provider_airline_iata,
        'evidence_type',evidence_type,'confidence_score',confidence_score
      ) ORDER BY confidence_score DESC) FROM public.flight_route_options
        WHERE publication_version_id=v_version AND origin_city_id=v_page.origin_city_id AND destination_city_id=v_page.destination_city_id),'[]'::jsonb),
      'observations', COALESCE((SELECT jsonb_agg(jsonb_build_object(
        'observation_id',item.id,'observed_amount',item.observed_amount,'currency_code',item.currency_code,
        'departure_date',item.departure_date,'direct',item.direct,'valid_until',item.valid_until
      ) ORDER BY item.observed_amount NULLS LAST,item.observed_at DESC)
      FROM public.flight_content_observations item JOIN admin.data_sources source ON source.id=item.source_id
      WHERE item.origin_city_id=v_page.origin_city_id AND item.destination_city_id=v_page.destination_city_id
        AND item.status='published' AND item.valid_until>now() AND source.production_display_allowed),'[]'::jsonb),
      'disclosure', 'Cached observations are not live offers; final price and availability are confirmed by the booking partner.'
    ),
    'meta', jsonb_build_object('canonical_path',v_registry.canonical_path,'is_indexable',v_registry.is_indexable,
      'noindex_reason',v_registry.noindex_reason,'data_version',v_version,'source_freshness_at',v_registry.source_freshness_at),
    'error', NULL
  );
END; $$;
REVOKE ALL ON FUNCTION private.build_route_page_payload(JSONB) FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.build_route_page_payload(JSONB) TO service_role;

-- >>> supabase/sql_src/functions/pseo/shared/rpc_get_sitemap.sql

CREATE OR REPLACE FUNCTION public.rpc_get_sitemap(p_input JSONB DEFAULT '{}'::JSONB) RETURNS JSONB LANGUAGE sql STABLE SET search_path='' AS $$
SELECT jsonb_build_object('data',COALESCE(jsonb_agg(jsonb_build_object('path',page.canonical_path,'locale',page.locale,'page_type',page.page_type,'last_modified',page.content_updated_at) ORDER BY page.canonical_path),'[]'::jsonb),'meta',jsonb_build_object('only_indexable',TRUE),'error',NULL)
FROM public.pseo_pages page WHERE page.status='published' AND page.is_indexable AND page.noindex_reason IS NULL AND (NOT p_input?'locale' OR page.locale=p_input->>'locale');
$$;
REVOKE ALL ON FUNCTION public.rpc_get_sitemap(JSONB) FROM public,anon,authenticated;GRANT EXECUTE ON FUNCTION public.rpc_get_sitemap(JSONB) TO service_role;

-- >>> supabase/sql_src/functions/pseo/shared/refresh_page_read_models.sql

-- ============================================================================
-- Function: private.refresh_page_read_models
-- Purpose: Materialize all page-specific single-load read models for one candidate version.
-- Responsibilities: Compose bounded page payloads outside the public request path.
-- Notes: Private builders compose bounded modules only during publication.
-- ============================================================================

CREATE OR REPLACE FUNCTION private.refresh_page_read_models(p_publication_version_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SET search_path = ''
AS $$
DECLARE
  v_city_count INTEGER;
  v_airport_count INTEGER;
  v_route_count INTEGER;
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.publication_versions version
    WHERE version.id = p_publication_version_id
      AND version.status = 'building'
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'ERR_PUBLICATION_VERSION_INVALID';
  END IF;

  DELETE FROM public.city_page_read_models WHERE publication_version_id = p_publication_version_id;
  DELETE FROM public.airport_page_read_models WHERE publication_version_id = p_publication_version_id;
  DELETE FROM public.route_page_read_models WHERE publication_version_id = p_publication_version_id;

  INSERT INTO public.city_page_read_models (
    publication_version_id,
    city_id,
    locale,
    canonical_slug,
    payload
  )
  SELECT
    p_publication_version_id,
    city_page.city_id,
    city_page.locale,
    registry.entity_key,
    private.build_city_page_payload(jsonb_build_object(
      'city_slug', registry.entity_key,
      'locale', city_page.locale,
      'route_direction', city_page.route_direction,
      'destination_limit', 20,
      'publication_version_id', p_publication_version_id
    ))->'data'
  FROM public.city_pages city_page
  JOIN public.pseo_pages AS registry ON registry.id = city_page.pseo_page_id
  WHERE city_page.route_direction = 'outbound'
    AND registry.status <> 'archived';
  GET DIAGNOSTICS v_city_count = ROW_COUNT;

  INSERT INTO public.airport_page_read_models (
    publication_version_id,
    airport_id,
    locale,
    airport_iata,
    payload
  )
  SELECT
    p_publication_version_id,
    airport_page.airport_id,
    airport_page.locale,
    airport.iata,
    private.build_airport_page_payload(jsonb_build_object(
      'airport_iata', airport.iata,
      'locale', airport_page.locale,
      'publication_version_id', p_publication_version_id
    ))->'data'
  FROM public.airport_pages airport_page
  JOIN public.airports airport
    ON airport.id = airport_page.airport_id
  JOIN public.pseo_pages AS registry ON registry.id = airport_page.pseo_page_id
  WHERE registry.status <> 'archived';
  GET DIAGNOSTICS v_airport_count = ROW_COUNT;

  INSERT INTO public.route_page_read_models (
    publication_version_id,
    route_page_id,
    locale,
    canonical_slug,
    payload
  )
  SELECT
    p_publication_version_id,
    route_page.id,
    route_page.locale,
    registry.entity_key,
    private.build_route_page_payload(jsonb_build_object(
      'route_slug', registry.entity_key,
      'locale', route_page.locale,
      'publication_version_id', p_publication_version_id
    ))->'data'
  FROM public.route_pages route_page
  JOIN public.pseo_pages AS registry ON registry.id = route_page.pseo_page_id
  WHERE registry.status <> 'archived';
  GET DIAGNOSTICS v_route_count = ROW_COUNT;

  RETURN jsonb_build_object(
    'city', v_city_count,
    'airport', v_airport_count,
    'route', v_route_count
  );
END;
$$;

REVOKE ALL ON FUNCTION private.refresh_page_read_models(UUID)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.refresh_page_read_models(UUID) TO service_role;

-- >>> supabase/sql_src/functions/pseo/shared/publish_read_model_version.sql

-- ============================================================================
-- Function: public.publish_read_model_version
-- Purpose: Atomically build and publish one complete shared read-model version.
-- Responsibilities: Refresh route search and all page models before flipping the current marker.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.publish_read_model_version(p_source_type TEXT DEFAULT 'development_fixture')
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SET search_path = ''
AS $$
DECLARE
  v_version_id UUID;
  v_route_count INTEGER;
  v_page_counts JSONB;
BEGIN
  IF p_source_type NOT IN ('production', 'development_fixture') THEN
    RETURN private.build_rpc_error(NULL, 'ERR_INVALID_REQUEST', 'Invalid publication source type.');
  END IF;

  -- STEP 01: Serialize publishers so two candidates cannot race the current marker.
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('tripways:read-model-publication', 0)
  );

  INSERT INTO public.publication_versions (source_type)
  VALUES (p_source_type)
  RETURNING id
  INTO v_version_id;

  -- STEP 02: Keep candidate failures in a subtransaction and preserve the current version.
  BEGIN
    v_route_count := private.refresh_route_search_options(v_version_id);

    -- STEP 02A: Derive lifecycle only on the canonical page registry.
    UPDATE public.pseo_pages AS registry
    SET
      is_indexable = FALSE,
      noindex_reason = CASE
        WHEN p_source_type = 'development_fixture' THEN 'development_fixture'
        WHEN registry.status <> 'published' THEN 'not_published'
        WHEN registry.page_type IN ('city', 'airport', 'city_route') THEN 'source_not_seo_eligible'
        ELSE COALESCE(registry.noindex_reason, 'unsupported_page_type')
      END,
      data_version = v_version_id,
      generated_at = now();

    -- Set both constrained lifecycle fields together after the safe noindex baseline.
    UPDATE public.pseo_pages AS registry
    SET is_indexable = TRUE, noindex_reason = NULL
    WHERE p_source_type = 'production'
      AND registry.status = 'published'
      AND CASE
        WHEN registry.page_type = 'city' THEN EXISTS (
          SELECT 1
          FROM public.city_pages AS content
          JOIN public.flight_route_options AS route
           ON route.publication_version_id = v_version_id
           AND route.origin_city_id = content.city_id
          WHERE content.pseo_page_id = registry.id
            AND content.content_reviewed_at IS NOT NULL
        )
        WHEN registry.page_type = 'airport' THEN EXISTS (
          SELECT 1
          FROM public.airport_pages AS content
          JOIN public.flight_route_options AS route
           ON route.publication_version_id = v_version_id
           AND route.origin_airport_id = content.airport_id
          WHERE content.pseo_page_id = registry.id
            AND content.content_reviewed_at IS NOT NULL
        )
        WHEN registry.page_type = 'city_route' THEN EXISTS (
          SELECT 1
          FROM public.route_pages AS content
          JOIN public.flight_route_options AS route
            ON route.publication_version_id = v_version_id
           AND route.origin_city_id = content.origin_city_id
           AND route.destination_city_id = content.destination_city_id
          WHERE content.pseo_page_id = registry.id
            AND content.content_reviewed_at IS NOT NULL
        )
        ELSE FALSE
      END;

    v_page_counts := private.refresh_page_read_models(v_version_id);

    IF v_route_count = 0 THEN
      RAISE EXCEPTION USING
        ERRCODE = '23514',
        MESSAGE = 'ERR_PUBLICATION_INCOMPLETE';
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      UPDATE public.publication_versions
      SET
        status = 'failed',
        failure_code = CASE
          WHEN SQLERRM ~ '^ERR_[A-Z0-9_]+$' THEN SQLERRM
          ELSE 'ERR_PUBLICATION_FAILED'
        END
      WHERE id = v_version_id;

      RETURN private.build_rpc_error(
        NULL,
        'ERR_PUBLICATION_FAILED',
        'Read-model publication failed.'
      );
  END;

  -- STEP 03: Flip all page and search readers to the complete candidate atomically.
  UPDATE public.publication_versions
  SET
    is_current = FALSE,
    status = 'retired'
  WHERE is_current = TRUE;

  UPDATE public.publication_versions
  SET
    status = 'published',
    is_current = TRUE,
    published_at = now()
  WHERE id = v_version_id;

  RETURN jsonb_build_object(
    'data', jsonb_build_object(
      'data_version', v_version_id,
      'route_options', v_route_count,
      'pages', v_page_counts
    ),
    'meta', jsonb_build_object('data_version', v_version_id, 'published_at', now()),
    'error', NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION public.publish_read_model_version(TEXT)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.publish_read_model_version(TEXT) TO service_role;

-- >>> supabase/sql_src/functions/pseo/shared/rpc_get_page.sql

-- ============================================================================
-- Function: public.rpc_get_page
-- Purpose: Load one complete page from its dedicated current read model.
-- Responsibilities: Normalize identity and perform exactly one page-model lookup.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.rpc_get_page(p_input JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SET search_path = ''
AS $$
DECLARE
  v_page_type TEXT := p_input->>'page_type';
  v_entity_key TEXT := p_input->>'entity_key';
  v_locale TEXT := COALESCE(NULLIF(p_input->>'locale', ''), 'en-GB');
  v_version_id UUID;
  v_payload JSONB;
  v_generated_at TIMESTAMPTZ;
BEGIN
  IF jsonb_typeof(p_input) IS DISTINCT FROM 'object'
    OR p_input - ARRAY['page_type', 'entity_key', 'locale'] <> '{}'::JSONB
    OR v_page_type NOT IN ('city', 'airport', 'route')
    OR v_entity_key IS NULL
    OR v_locale !~ '^[a-z]{2}(?:-[A-Z]{2})?$'
  THEN
    RETURN private.build_rpc_error(NULL, 'ERR_INVALID_REQUEST', 'Invalid page request.');
  END IF;

  -- STEP 01: Select the requested row and its current version in one indexed statement.
  IF v_page_type = 'city' THEN
    SELECT model.payload, model.generated_at, version.id
    INTO v_payload, v_generated_at, v_version_id
    FROM public.city_page_read_models model
    INNER JOIN public.publication_versions version
      ON version.id = model.publication_version_id
      AND version.is_current = TRUE
    WHERE model.canonical_slug = lower(v_entity_key)
      AND model.locale = v_locale;
  ELSIF v_page_type = 'airport' THEN
    SELECT model.payload, model.generated_at, version.id
    INTO v_payload, v_generated_at, v_version_id
    FROM public.airport_page_read_models model
    INNER JOIN public.publication_versions version
      ON version.id = model.publication_version_id
      AND version.is_current = TRUE
    WHERE model.airport_iata = upper(v_entity_key)
      AND model.locale = v_locale;
  ELSE
    SELECT model.payload, model.generated_at, version.id
    INTO v_payload, v_generated_at, v_version_id
    FROM public.route_page_read_models model
    INNER JOIN public.publication_versions version
      ON version.id = model.publication_version_id
      AND version.is_current = TRUE
    WHERE model.canonical_slug = lower(v_entity_key)
      AND model.locale = v_locale;
  END IF;

  IF v_payload IS NULL THEN
    RETURN private.build_rpc_error(NULL, 'ERR_PAGE_NOT_FOUND', 'Current page not found.');
  END IF;

  -- STEP 02: Return the materialized payload without rebuilding page modules at request time.
  RETURN jsonb_build_object(
    'data', v_payload,
    'meta', jsonb_build_object(
      'page_type', v_page_type,
      'entity_key', v_entity_key,
      'data_version', v_version_id,
      'generated_at', v_generated_at
    ),
    'error', NULL
  );
END;
$$;

REVOKE ALL ON FUNCTION public.rpc_get_page(JSONB)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_get_page(JSONB) TO service_role;

-- >>> supabase/sql_src/operations/generate_local_geo_preview_pages.sql

-- ============================================================================
-- Function: private.generate_local_geo_preview_pages
-- Purpose: Build local-only draft/noindex City and Airport pages from base data.
-- Notes: Ambiguous city slugs are intentionally skipped until disambiguated.
-- ============================================================================

CREATE OR REPLACE FUNCTION private.generate_local_geo_preview_pages()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_city_registry_count INTEGER := 0;
  v_city_page_count INTEGER := 0;
  v_airport_registry_count INTEGER := 0;
  v_airport_page_count INTEGER := 0;
  v_route_page_count INTEGER := 0;
  v_ambiguous_city_count INTEGER := 0;
BEGIN
  SELECT count(*)
  INTO v_ambiguous_city_count
  FROM (
    SELECT city.slug
    FROM public.cities AS city
    GROUP BY city.slug
    HAVING count(*) > 1
  ) AS ambiguous;

  INSERT INTO public.pseo_pages (
    page_type,
    entity_key,
    locale,
    canonical_path,
    display_title,
    status,
    is_indexable,
    noindex_reason,
    source_freshness_at
  )
  SELECT
    'city',
    city.slug,
    'en-GB',
    '/flights-from/' || city.slug,
    'Direct flights from ' || city.name,
    'draft',
    FALSE,
    'development_preview',
    city.updated_at
  FROM public.cities AS city
  WHERE NOT EXISTS (
      SELECT 1
      FROM public.cities AS duplicate
      WHERE duplicate.slug = city.slug
        AND duplicate.id <> city.id
    )
    AND NOT EXISTS (
      SELECT 1
      FROM public.city_pages AS city_page
      WHERE city_page.city_id = city.id
        AND city_page.locale = 'en-GB'
        AND city_page.route_direction = 'outbound'
    )
  ON CONFLICT DO NOTHING;
  GET DIAGNOSTICS v_city_registry_count = ROW_COUNT;

  INSERT INTO public.city_pages (
    pseo_page_id,
    city_id,
    locale,
    route_direction,
    h1,
    subheadline,
    seo_title,
    meta_description,
    og_title,
    og_description,
    intro,
    airport_summary,
    primary_airport_id,
    content_reviewed_at
  )
  SELECT
    registry.id,
    city.id,
    'en-GB',
    'outbound',
    'Direct flights from ' || city.name,
    'Explore commercial airports and available flight connections from ' || city.name || ', ' || country.name || '.',
    'Direct Flights from ' || city.name || ' | Tripways',
    'Explore commercial airports and flight connections from ' || city.name || ', ' || country.name || '.',
    'Direct flights from ' || city.name,
    'Explore airports and flight connections from ' || city.name || ', ' || country.name || '.',
    city.name || ' is served by the commercial airport data listed below. Route schedules and fares are shown only when available.',
    CASE
      WHEN airport_rollup.airport_count = 1 THEN city.name || ' has 1 commercial airport in the current dataset.'
      ELSE city.name || ' has ' || airport_rollup.airport_count || ' commercial airports in the current dataset.'
    END,
    airport_rollup.primary_airport_id,
    NULL
  FROM public.cities AS city
  JOIN public.countries AS country ON country.id = city.country_id
  JOIN public.pseo_pages AS registry
    ON registry.page_type = 'city'
   AND registry.entity_key = city.slug
   AND registry.locale = 'en-GB'
  CROSS JOIN LATERAL (
    SELECT
      count(*)::INTEGER AS airport_count,
      (array_agg(airport.id ORDER BY
        CASE airport.airport_type WHEN 'large_airport' THEN 1 WHEN 'medium_airport' THEN 2 ELSE 3 END,
        airport.iata
      ))[1] AS primary_airport_id
    FROM public.airports AS airport
    WHERE airport.city_id = city.id
      AND airport.iata IS NOT NULL
      AND airport.status = 'active'
  ) AS airport_rollup
  WHERE airport_rollup.airport_count > 0
    AND NOT EXISTS (
      SELECT 1 FROM public.cities AS duplicate
      WHERE duplicate.slug = city.slug AND duplicate.id <> city.id
    )
    AND NOT EXISTS (
      SELECT 1 FROM public.city_pages AS existing
      WHERE existing.city_id = city.id
        AND existing.locale = 'en-GB'
        AND existing.route_direction = 'outbound'
    )
  ON CONFLICT DO NOTHING;
  GET DIAGNOSTICS v_city_page_count = ROW_COUNT;

  INSERT INTO public.pseo_pages (
    page_type,
    entity_key,
    locale,
    canonical_path,
    display_title,
    status,
    is_indexable,
    noindex_reason,
    source_freshness_at
  )
  SELECT
    'airport',
    lower(airport.iata),
    'en-GB',
    '/airports/' || airport.slug || '-' || lower(airport.iata),
    airport.name || ' (' || airport.iata || ')',
    'draft',
    FALSE,
    'development_preview',
    airport.updated_at
  FROM public.airports AS airport
  WHERE airport.iata IS NOT NULL
    AND airport.city_id IS NOT NULL
    AND airport.status = 'active'
    AND NOT EXISTS (
      SELECT 1
      FROM public.airport_pages AS airport_page
      WHERE airport_page.airport_id = airport.id
        AND airport_page.locale = 'en-GB'
    )
  ON CONFLICT DO NOTHING;
  GET DIAGNOSTICS v_airport_registry_count = ROW_COUNT;

  INSERT INTO public.airport_pages (
    pseo_page_id,
    airport_id,
    locale,
    h1,
    subheadline,
    seo_title,
    meta_description,
    og_title,
    og_description,
    intro,
    orientation_summary,
    arrival_summary,
    departure_summary,
    primary_city_area_label,
    content_reviewed_at
  )
  SELECT
    registry.id,
    airport.id,
    'en-GB',
    airport.name || ' (' || airport.iata || ')',
    'Airport information for ' || city.name || ', ' || country.name || '.',
    airport.name || ' (' || airport.iata || ') Guide | Tripways',
    'View location, city, timezone and available flight information for ' || airport.name || ' (' || airport.iata || ').',
    airport.name || ' (' || airport.iata || ')',
    'Airport information for ' || airport.name || ' serving ' || city.name || '.',
    airport.name || ' is a commercial airport serving ' || city.name || ', ' || country.name || '.',
    'Use this preview for the airport identity, location and available route data currently stored by Tripways.',
    'Arrival transport details are awaiting editorial review.',
    'Departure and terminal details are awaiting editorial review.',
    city.name,
    NULL
  FROM public.airports AS airport
  JOIN public.cities AS city ON city.id = airport.city_id
  JOIN public.countries AS country ON country.id = airport.country_id
  JOIN public.pseo_pages AS registry
    ON registry.page_type = 'airport'
   AND registry.entity_key = lower(airport.iata)
   AND registry.locale = 'en-GB'
  WHERE airport.iata IS NOT NULL
    AND airport.status = 'active'
    AND NOT EXISTS (
      SELECT 1 FROM public.airport_pages AS existing
      WHERE existing.airport_id = airport.id
        AND existing.locale = 'en-GB'
    )
  ON CONFLICT DO NOTHING;
  GET DIAGNOSTICS v_airport_page_count = ROW_COUNT;

  INSERT INTO public.route_pages (
    pseo_page_id,
    origin_city_id,
    destination_city_id,
    locale,
    h1,
    subheadline,
    seo_title,
    meta_description,
    intro,
    content_reviewed_at
  )
  SELECT
    registry.id,
    origin_city.id,
    destination_city.id,
    'en-GB',
    'Flights from ' || origin_city.name || ' to ' || destination_city.name,
    'Explore stored direct flight options from ' || origin_city.name || ' to ' || destination_city.name || '.',
    origin_city.name || ' to ' || destination_city.name || ' Flights | Tripways',
    'Explore airlines, airports and stored flight options from ' || origin_city.name || ' to ' || destination_city.name || '.',
    'Compare the route data currently available for travel from ' || origin_city.name || ' to ' || destination_city.name || '.',
    NULL
  FROM public.pseo_pages AS registry
  JOIN public.cities AS origin_city
    ON origin_city.slug = split_part(registry.entity_key, ':', 1)
  JOIN public.cities AS destination_city
    ON destination_city.slug = split_part(registry.entity_key, ':', 2)
  WHERE registry.page_type = 'city_route'
    AND registry.locale = 'en-GB'
    AND registry.entity_key LIKE '%:%'
    AND NOT EXISTS (
      SELECT 1 FROM public.route_pages AS existing
      WHERE existing.pseo_page_id = registry.id
    )
  ON CONFLICT DO NOTHING;
  GET DIAGNOSTICS v_route_page_count = ROW_COUNT;

  RETURN jsonb_build_object(
    'city_registry_created', v_city_registry_count,
    'city_pages_created', v_city_page_count,
    'airport_registry_created', v_airport_registry_count,
    'airport_pages_created', v_airport_page_count,
    'route_pages_created', v_route_page_count,
    'ambiguous_city_slugs_skipped', v_ambiguous_city_count
  );
END;
$$;

REVOKE ALL ON FUNCTION private.generate_local_geo_preview_pages()
FROM public, anon, authenticated;

GRANT EXECUTE ON FUNCTION private.generate_local_geo_preview_pages() TO service_role;

-- >>> supabase/sql_src/operations/rename_city_slug.sql

-- ============================================================================
-- Function: private.rename_city_slug
-- Purpose: Rename a city slug and every canonical pSEO identity that embeds it.
-- Notes: Service-role operation. Publish a new read-model version after calling.
-- ============================================================================

CREATE OR REPLACE FUNCTION private.rename_city_slug(
  p_current_slug TEXT,
  p_new_slug TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_city_id UUID;
  v_current_slug TEXT := lower(btrim(p_current_slug));
  v_new_slug TEXT := lower(btrim(p_new_slug));
  v_city_page_count INTEGER := 0;
  v_route_page_count INTEGER := 0;
  v_registry_count INTEGER := 0;
  v_placeholder_registry_count INTEGER := 0;
BEGIN
  IF v_current_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
     OR v_new_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' THEN
    RAISE EXCEPTION 'ERR_CITY_SLUG_INVALID';
  END IF;

  SELECT city.id
  INTO v_city_id
  FROM public.cities AS city
  WHERE city.slug = v_current_slug
  FOR UPDATE;

  IF v_city_id IS NULL THEN
    RAISE EXCEPTION 'ERR_CITY_NOT_FOUND';
  END IF;

  IF v_current_slug = v_new_slug THEN
    RETURN jsonb_build_object(
      'city_id', v_city_id,
      'old_slug', v_current_slug,
      'new_slug', v_new_slug,
      'city_pages_updated', 0,
      'route_pages_updated', 0,
      'registry_pages_updated', 0
    );
  END IF;

  IF EXISTS (SELECT 1 FROM public.cities AS city WHERE city.slug = v_new_slug) THEN
    RAISE EXCEPTION 'ERR_CITY_SLUG_CONFLICT';
  END IF;

  UPDATE public.cities
  SET slug = v_new_slug,
      updated_at = now()
  WHERE id = v_city_id;

  UPDATE public.city_pages AS city_page
  SET og_image_path = CASE
        WHEN city_page.og_image_path = '/og/flights-from/' || v_current_slug || '.png'
          THEN '/og/flights-from/' || v_new_slug || '.png'
        ELSE city_page.og_image_path
      END,
      updated_at = now()
  WHERE city_page.city_id = v_city_id;
  GET DIAGNOSTICS v_city_page_count = ROW_COUNT;

  UPDATE public.pseo_pages AS registry
  SET entity_key = v_new_slug,
      canonical_path = '/flights-from/' || v_new_slug,
      content_updated_at = now(),
      generated_at = now()
  FROM public.city_pages AS city_page
  WHERE city_page.pseo_page_id = registry.id
    AND city_page.city_id = v_city_id;
  GET DIAGNOSTICS v_registry_count = ROW_COUNT;

  UPDATE public.pseo_pages AS registry
  SET entity_key = origin_city.slug || '-to-' || destination_city.slug,
      canonical_path = '/flights/' || origin_city.slug || '-to-' || destination_city.slug,
      content_updated_at = now(),
      generated_at = now()
  FROM public.route_pages AS route_page
  JOIN public.cities AS origin_city ON origin_city.id = route_page.origin_city_id
  JOIN public.cities AS destination_city ON destination_city.id = route_page.destination_city_id
  WHERE route_page.pseo_page_id = registry.id
    AND (route_page.origin_city_id = v_city_id OR route_page.destination_city_id = v_city_id);
  GET DIAGNOSTICS v_route_page_count = ROW_COUNT;

  UPDATE public.pseo_pages AS registry
  SET entity_key = CASE
        WHEN registry.entity_key LIKE v_current_slug || ':%'
          THEN v_new_slug || substr(registry.entity_key, char_length(v_current_slug) + 1)
        WHEN registry.entity_key LIKE '%:' || v_current_slug
          THEN left(registry.entity_key, char_length(registry.entity_key) - char_length(v_current_slug)) || v_new_slug
        ELSE registry.entity_key
      END,
      canonical_path = CASE
        WHEN registry.canonical_path LIKE '/flights/' || v_current_slug || '-to-%'
          THEN '/flights/' || v_new_slug || substr(
            registry.canonical_path,
            char_length('/flights/' || v_current_slug) + 1
          )
        WHEN registry.canonical_path LIKE '/flights/%-to-' || v_current_slug
          THEN left(registry.canonical_path, char_length(registry.canonical_path) - char_length(v_current_slug)) || v_new_slug
        ELSE registry.canonical_path
      END,
      content_updated_at = now(),
      generated_at = now()
  WHERE registry.page_type = 'city_route'
    AND (
      registry.entity_key LIKE v_current_slug || ':%'
      OR registry.entity_key LIKE '%:' || v_current_slug
    );
  GET DIAGNOSTICS v_placeholder_registry_count = ROW_COUNT;
  v_registry_count := v_registry_count + v_placeholder_registry_count;

  RETURN jsonb_build_object(
    'city_id', v_city_id,
    'old_slug', v_current_slug,
    'new_slug', v_new_slug,
    'city_pages_updated', v_city_page_count,
    'route_pages_updated', v_route_page_count,
    'registry_pages_updated', v_registry_count
  );
END;
$$;

REVOKE ALL ON FUNCTION private.rename_city_slug(TEXT, TEXT)
FROM public, anon, authenticated;

GRANT EXECUTE ON FUNCTION private.rename_city_slug(TEXT, TEXT) TO service_role;
