-- ============================================================================
-- Migration: 20260714080700_user_triggers.sql
-- Source of truth: supabase/sql_src
-- Feature: user triggers
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/triggers/user/trg_handle_new_auth_user.sql

-- ============================================================================
-- Trigger: trg_handle_new_auth_user
-- Feature: User authentication
-- Purpose: Create application profile state after an Auth identity is inserted.
-- Responsibilities: Delegate bootstrap validation and insertion to the private function.
-- ============================================================================

DROP TRIGGER IF EXISTS trg_handle_new_auth_user ON auth.users;

CREATE TRIGGER trg_handle_new_auth_user
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION private.handle_new_auth_user();
