-- ============================================================================
-- Migration: 20260714081000_ingestion_functions.sql
-- Source of truth: supabase/sql_src
-- Feature: base data ingestion functions
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/functions/ingestion/ingest_direct_flight_routes_batch.sql

-- ============================================================================
-- Function: admin.ingest_direct_flight_routes_batch
-- Purpose: Validate and batch upsert direct non-stop flight routes from licensed providers.
-- Responsibilities:
--   - Verify data source identity and permissions.
--   - Resolve airport and airline foreign keys by IATA codes.
--   - Upsert into public.direct_flight_routes with complete lineage and schedule metadata.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.ingest_direct_flight_routes_batch(
  p_source_code TEXT,
  p_routes      JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_source_id UUID;
  v_count     INTEGER := 0;
BEGIN
  IF p_source_code IS NULL OR NULLIF(btrim(p_source_code), '') IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'ERR_INVALID_SOURCE_CODE';
  END IF;

  IF p_routes IS NULL OR jsonb_typeof(p_routes) <> 'array' THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'ERR_INVALID_ROUTES_PAYLOAD';
  END IF;

  SELECT id INTO v_source_id
  FROM admin.data_sources
  WHERE code = p_source_code;

  IF v_source_id IS NULL THEN
    -- Fallback: auto-register provider data source if not present
    INSERT INTO admin.data_sources (
      id, code, name
    ) VALUES (
      gen_random_uuid(), p_source_code, 'AeroDataBox Flight Routes'
    ) RETURNING id INTO v_source_id;
  END IF;

  IF jsonb_array_length(p_routes) = 0 THEN
    RETURN jsonb_build_object('status', 'success', 'upserted_count', 0);
  END IF;

  WITH route_items AS (
    SELECT
      upper(btrim(r->>'origin_iata')) AS origin_iata,
      upper(btrim(r->>'destination_iata')) AS destination_iata,
      upper(btrim(r->>'airline_iata')) AS airline_iata,
      COALESCE(NULLIF(btrim(r->>'airline_name'), ''), upper(btrim(r->>'airline_iata'))) AS airline_name,
      COALESCE(
        ARRAY(SELECT jsonb_array_elements_text(r->'flight_numbers')),
        '{}'::TEXT[]
      ) AS flight_numbers,
      GREATEST(1, COALESCE((r->>'flight_duration_minutes')::INTEGER, 60)) AS flight_duration_minutes,
      NULLIF((r->>'distance_km')::INTEGER, 0) AS distance_km,
      COALESCE(
        ARRAY(SELECT (jsonb_array_elements_text(r->'days_of_week'))::INTEGER),
        '{1,2,3,4,5,6,7}'::INTEGER[]
      ) AS days_of_week,
      COALESCE(
        ARRAY(SELECT jsonb_array_elements_text(r->'aircraft_types')),
        '{}'::TEXT[]
      ) AS aircraft_types,
      COALESCE(
        NULLIF(btrim(r->>'source_record_id'), ''),
        p_source_code || '-' || upper(btrim(r->>'origin_iata')) || '-' || upper(btrim(r->>'destination_iata')) || '-' || upper(btrim(r->>'airline_iata'))
      ) AS source_record_id
    FROM jsonb_array_elements(p_routes) AS r
    WHERE NULLIF(btrim(r->>'origin_iata'), '') IS NOT NULL
      AND NULLIF(btrim(r->>'destination_iata'), '') IS NOT NULL
      AND NULLIF(btrim(r->>'airline_iata'), '') IS NOT NULL
  ),
  upserted AS (
    INSERT INTO public.direct_flight_routes (
      origin_airport_id,
      destination_airport_id,
      origin_iata,
      destination_iata,
      airline_iata,
      airline_name,
      airline_id,
      flight_numbers,
      flight_duration_minutes,
      distance_km,
      days_of_week,
      aircraft_types,
      source_id,
      source_record_id,
      last_synced_at,
      is_active
    )
    SELECT
      orig.id,
      dest.id,
      item.origin_iata,
      item.destination_iata,
      item.airline_iata,
      COALESCE(al.name, item.airline_name),
      al.id,
      item.flight_numbers,
      item.flight_duration_minutes,
      COALESCE(
        item.distance_km,
        admin.calculate_haversine_distance_km(orig.latitude, orig.longitude, dest.latitude, dest.longitude),
        500
      ),
      item.days_of_week,
      item.aircraft_types,
      v_source_id,
      item.source_record_id,
      now(),
      TRUE
    FROM route_items item
    JOIN public.airports orig ON orig.iata = item.origin_iata
    JOIN public.airports dest ON dest.iata = item.destination_iata
    LEFT JOIN public.airlines al ON al.iata = item.airline_iata
    WHERE orig.id <> dest.id
    ON CONFLICT (source_id, source_record_id)
    DO UPDATE SET
      flight_numbers = EXCLUDED.flight_numbers,
      flight_duration_minutes = EXCLUDED.flight_duration_minutes,
      distance_km = EXCLUDED.distance_km,
      days_of_week = EXCLUDED.days_of_week,
      aircraft_types = EXCLUDED.aircraft_types,
      airline_name = EXCLUDED.airline_name,
      airline_id = EXCLUDED.airline_id,
      last_synced_at = now(),
      is_active = TRUE
    RETURNING id
  )
  SELECT count(*) INTO v_count FROM upserted;

  RETURN jsonb_build_object(
    'status', 'success',
    'source_code', p_source_code,
    'upserted_count', v_count
  );
END;
$$;

REVOKE ALL ON FUNCTION admin.ingest_direct_flight_routes_batch(TEXT, JSONB)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.ingest_direct_flight_routes_batch(TEXT, JSONB) TO service_role;

-- >>> supabase/sql_src/functions/ingestion/rpc_ingest_direct_flight_routes.sql

-- ============================================================================
-- Function: public.rpc_ingest_direct_flight_routes
-- Purpose: PostgREST transport wrapper for direct flight route ingestion.
-- Responsibilities: Forward batch to internal admin function, enforce service_role only.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.rpc_ingest_direct_flight_routes(
  p_source_code TEXT,
  p_routes      JSONB
)
RETURNS JSONB
LANGUAGE sql
SECURITY INVOKER
SET search_path = ''
AS $$
  SELECT admin.ingest_direct_flight_routes_batch(p_source_code, p_routes);
$$;

REVOKE ALL ON FUNCTION public.rpc_ingest_direct_flight_routes(TEXT, JSONB)
FROM public, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.rpc_ingest_direct_flight_routes(TEXT, JSONB) TO service_role;

-- >>> supabase/sql_src/functions/ingestion/publish_base_data_batch.sql

-- ============================================================================
-- Function: admin.publish_base_data_batch
-- Purpose: Validate and atomically publish one canonical base-data batch.
-- Responsibilities:
--   - Enforce source eligibility and replay safety.
--   - Preserve raw records and bounded operational evidence.
--   - Publish countries, cities, and airports only after complete validation.
-- Notes:
--   - P0A supports atomic mode only.
--   - Optional provider values remain NULL and never imply production eligibility.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.publish_base_data_batch(
  p_source_code       TEXT,
  p_idempotency_key   TEXT,
  p_checksum          TEXT,
  p_provider_version  TEXT,
  p_source_time       TIMESTAMPTZ,
  p_records           JSONB,
  p_import_metadata   JSONB DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  -- Auth and source
  v_source_id       UUID;

  -- Batch and run
  v_batch_id        UUID;
  v_existing_batch  admin.raw_import_batches%ROWTYPE;
  v_record_count    INTEGER;
  v_invalid_count   INTEGER;
  v_previous_eligible_count INTEGER;
  v_eligible_count  INTEGER;
  v_deactivation_count INTEGER;

  -- Publication
  v_country         JSONB;
  v_city            JSONB;
  v_airport         JSONB;
  v_country_id      UUID;
  v_city_id         UUID;
  v_slug            TEXT;
  v_city_record     JSONB;
BEGIN
  -- STEP 01: Validate bounded invocation fields and source rights.
  IF p_source_code IS NULL
    OR p_source_code <> btrim(p_source_code)
    OR p_idempotency_key IS NULL
    OR char_length(p_idempotency_key) NOT BETWEEN 8 AND 128
    OR p_checksum !~ '^[a-f0-9]{64}$'
    OR p_provider_version <> 'base-data.v1'
    OR jsonb_typeof(p_records) <> 'object'
    OR jsonb_typeof(p_records -> 'countries') <> 'array'
    OR jsonb_typeof(p_records -> 'cities') <> 'array'
    OR jsonb_typeof(p_records -> 'airports') <> 'array'
    OR (p_import_metadata IS NOT NULL AND jsonb_typeof(p_import_metadata) <> 'object')
  THEN
    RETURN jsonb_build_object(
      'status', 'failed',
      'errorCode', 'ERR_INGESTION_INVALID_REQUEST'
    );
  END IF;

  SELECT source.id
  INTO v_source_id
  FROM admin.data_sources AS source
  WHERE source.code = p_source_code;

  IF v_source_id IS NULL THEN
    RETURN jsonb_build_object(
      'status', 'failed',
      'errorCode', 'ERR_INGESTION_SOURCE_NOT_ALLOWED'
    );
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext(p_source_code));

  -- STEP 02: Return the stable result for checksum or idempotency replays.
  SELECT batch.*
  INTO v_existing_batch
  FROM admin.raw_import_batches AS batch
  WHERE batch.source_id = v_source_id
    AND (
      batch.checksum = p_checksum
      OR batch.idempotency_key = p_idempotency_key
    )
  ORDER BY batch.received_at
  LIMIT 1;

  IF v_existing_batch.id IS NOT NULL THEN
    RETURN jsonb_build_object(
      'status', v_existing_batch.status,
      'batchId', v_existing_batch.id,
      'duplicate', TRUE,
      'errorCode', 'ERR_INGESTION_BATCH_DUPLICATE'
    );
  END IF;

  -- STEP 03: Persist the raw receipt and an atomic publication run.
  INSERT INTO admin.raw_import_batches (
    source_id,
    provider_version,
    checksum,
    idempotency_key,
    source_time,
    source_url,
    source_etag,
    downloaded_bytes,
    raw_record_count,
    eligible_record_count,
    filtered_record_count,
    invalid_record_count,
    filter_version,
    status
  )
  VALUES (
    v_source_id,
    p_provider_version,
    p_checksum,
    p_idempotency_key,
    p_source_time,
    p_import_metadata ->> 'sourceUrl',
    p_import_metadata ->> 'sourceEtag',
    (p_import_metadata ->> 'downloadedBytes')::INTEGER,
    (p_import_metadata ->> 'rawRecordCount')::INTEGER,
    (p_import_metadata ->> 'eligibleRecordCount')::INTEGER,
    (p_import_metadata ->> 'filteredRecordCount')::INTEGER,
    (p_import_metadata ->> 'invalidRecordCount')::INTEGER,
    p_import_metadata ->> 'filterVersion',
    'received'
  )
  RETURNING id INTO v_batch_id;

  INSERT INTO admin.raw_base_data_records (
    batch_id,
    record_type,
    source_key,
    payload
  )
  SELECT
    v_batch_id,
    records.record_type,
    records.source_key,
    records.payload
  FROM (
    SELECT
      'country'::TEXT AS record_type,
      country ->> 'iso2' AS source_key,
      country AS payload
    FROM jsonb_array_elements(p_records -> 'countries') AS country

    UNION ALL

    SELECT
      'city',
      city ->> 'sourceId',
      city
    FROM jsonb_array_elements(p_records -> 'cities') AS city

    UNION ALL

    SELECT
      'airport',
      airport ->> 'sourceId',
      airport
    FROM jsonb_array_elements(p_records -> 'airports') AS airport
  ) AS records;

  GET DIAGNOSTICS v_record_count = ROW_COUNT;

  -- STEP 04: Hold anomalous production snapshots for review before canonical mutation.
  v_eligible_count := jsonb_array_length(p_records -> 'airports');

  SELECT batch.eligible_record_count
  INTO v_previous_eligible_count
  FROM admin.raw_import_batches AS batch
  WHERE batch.source_id = v_source_id
    AND batch.status = 'published'
    AND batch.id <> v_batch_id
    AND batch.eligible_record_count IS NOT NULL
  ORDER BY batch.received_at DESC
  LIMIT 1;

  SELECT count(*)::INTEGER
  INTO v_deactivation_count
  FROM public.airports AS airport
  WHERE airport.source_id = v_source_id
    AND airport.status = 'active'
    AND NOT EXISTS (
      SELECT 1
      FROM jsonb_array_elements(p_records -> 'airports') AS candidate
      WHERE candidate ->> 'sourceId' = airport.source_record_id
    );

  IF p_source_code = 'ourairports'
    AND v_previous_eligible_count > 0
    AND (
      v_eligible_count < v_previous_eligible_count * 0.95
      OR abs(v_eligible_count - v_previous_eligible_count) > v_previous_eligible_count * 0.15
      OR v_deactivation_count > greatest(1, ceil(v_previous_eligible_count * 0.02))
    )
  THEN
    UPDATE admin.raw_import_batches
    SET status = 'awaiting_review', updated_at = now()
    WHERE id = v_batch_id;

    RETURN jsonb_build_object(
      'status', 'awaiting_review',
      'batchId', v_batch_id,
      'acceptedCount', 0,
      'rejectedCount', v_record_count,
      'errorCode', 'ERR_INGESTION_ANOMALY_REVIEW_REQUIRED'
    );
  END IF;

  -- STEP 05: Validate all required fields, coordinates, duplicates, and references.
  SELECT count(*)
  INTO v_invalid_count
  FROM admin.raw_base_data_records AS record
  WHERE record.batch_id = v_batch_id
    AND (
      record.source_key IS NULL
      OR record.source_key = ''
      OR (
        record.record_type = 'country'
        AND (
          record.payload ->> 'iso2' !~ '^[A-Z]{2}$'
          OR record.payload ->> 'iso3' !~ '^[A-Z]{3}$'
          OR NULLIF(btrim(record.payload ->> 'name'), '') IS NULL
        )
      )
      OR (
        record.record_type = 'city'
        AND (
          NULLIF(btrim(record.payload ->> 'name'), '') IS NULL
          OR record.payload ->> 'countryIso2' !~ '^[A-Z]{2}$'
          OR ((record.payload -> 'latitude') IS NULL) <> ((record.payload -> 'longitude') IS NULL)
          OR (
            (record.payload -> 'latitude') IS NOT NULL
            AND (
              (record.payload ->> 'latitude')::DOUBLE PRECISION NOT BETWEEN -90 AND 90
              OR (record.payload ->> 'longitude')::DOUBLE PRECISION NOT BETWEEN -180 AND 180
            )
          )
        )
      )
      OR (
        record.record_type = 'airport'
        AND (
          NULLIF(btrim(record.payload ->> 'name'), '') IS NULL
          OR record.payload ->> 'countryIso2' !~ '^[A-Z]{2}$'
          OR NULLIF(btrim(record.payload ->> 'type'), '') IS NULL
          OR ((record.payload -> 'latitude') IS NULL) <> ((record.payload -> 'longitude') IS NULL)
          OR (
            (record.payload -> 'latitude') IS NOT NULL
            AND (
              (record.payload ->> 'latitude')::DOUBLE PRECISION NOT BETWEEN -90 AND 90
              OR (record.payload ->> 'longitude')::DOUBLE PRECISION NOT BETWEEN -180 AND 180
            )
          )
        )
      )
    );

  v_invalid_count := v_invalid_count + (
    SELECT count(*)::INTEGER
    FROM (
      SELECT record_type, source_key
      FROM admin.raw_base_data_records
      WHERE batch_id = v_batch_id
      GROUP BY record_type, source_key
      HAVING count(*) > 1
    ) AS duplicates
  );

  v_invalid_count := v_invalid_count + (
    SELECT count(*)::INTEGER
    FROM admin.raw_base_data_records AS record
    WHERE record.batch_id = v_batch_id
      AND record.record_type IN ('city', 'airport')
      AND NOT EXISTS (
        SELECT 1
        FROM admin.raw_base_data_records AS country
        WHERE country.batch_id = v_batch_id
          AND country.record_type = 'country'
          AND country.payload ->> 'iso2' = record.payload ->> 'countryIso2'
      )
      AND NOT EXISTS (
        SELECT 1
        FROM public.countries AS country
        WHERE country.iso2 = record.payload ->> 'countryIso2'
      )
  );

  v_invalid_count := v_invalid_count + (
    SELECT count(*)::INTEGER
    FROM admin.raw_base_data_records AS record
    WHERE record.batch_id = v_batch_id
      AND record.record_type = 'airport'
      AND NULLIF(record.payload ->> 'citySourceId', '') IS NOT NULL
      AND NOT EXISTS (
        SELECT 1
        FROM admin.raw_base_data_records AS city
        WHERE city.batch_id = v_batch_id
          AND city.record_type = 'city'
          AND city.source_key = record.payload ->> 'citySourceId'
      )
  );

  IF v_invalid_count > 0 THEN
    UPDATE admin.raw_base_data_records
    SET validation_state = 'invalid'
    WHERE batch_id = v_batch_id;

    UPDATE admin.raw_import_batches
    SET
      status = 'rejected',
      updated_at = now()
    WHERE id = v_batch_id;

    RETURN jsonb_build_object(
      'status', 'rejected',
      'batchId', v_batch_id,
      'acceptedCount', 0,
      'rejectedCount', v_record_count,
      'errorCode', 'ERR_INGESTION_VALIDATION_FAILED'
    );
  END IF;

  UPDATE admin.raw_base_data_records
  SET validation_state = 'valid'
  WHERE batch_id = v_batch_id;

  -- STEP 06: Publish countries, then cities, then airports.
  FOR v_country IN
    SELECT value
    FROM jsonb_array_elements(p_records -> 'countries')
  LOOP
    v_slug := trim(BOTH '-' FROM regexp_replace(lower(v_country ->> 'name'), '[^a-z0-9]+', '-', 'g'));

    INSERT INTO public.countries (
      iso2,
      iso3,
      name,
      slug,
      region,
      subregion,
      source_id,
      source_record_id
    )
    VALUES (
      v_country ->> 'iso2',
      v_country ->> 'iso3',
      btrim(v_country ->> 'name'),
      v_slug,
      NULLIF(btrim(v_country ->> 'region'), ''),
      NULLIF(btrim(v_country ->> 'subregion'), ''),
      v_source_id,
      v_country ->> 'iso2'
    )
    ON CONFLICT (iso2) DO NOTHING;

    UPDATE public.countries AS country
    SET
      iso3 = v_country ->> 'iso3',
      name = btrim(v_country ->> 'name'),
      slug = v_slug,
      region = COALESCE(NULLIF(btrim(v_country ->> 'region'), ''), country.region),
      subregion = COALESCE(NULLIF(btrim(v_country ->> 'subregion'), ''), country.subregion),
      updated_at = now()
    WHERE country.source_id = v_source_id
      AND country.source_record_id = v_country ->> 'iso2';
  END LOOP;

  FOR v_city IN
    SELECT value
    FROM jsonb_array_elements(p_records -> 'cities')
  LOOP
    SELECT country.id
    INTO v_country_id
    FROM public.countries AS country
    WHERE country.iso2 = v_city ->> 'countryIso2'
    ORDER BY (country.source_id = v_source_id) DESC
    LIMIT 1;

    v_slug := trim(BOTH '-' FROM regexp_replace(lower(v_city ->> 'name'), '[^a-z0-9]+', '-', 'g'));

    INSERT INTO public.cities (
      country_id,
      name,
      slug,
      iata_code,
      currency_code,
      primary_language,
      latitude,
      longitude,
      timezone,
      source_id,
      source_record_id
    )
    VALUES (
      v_country_id,
      btrim(v_city ->> 'name'),
      v_slug,
      NULLIF(btrim(v_city ->> 'iataCode'), ''),
      NULLIF(btrim(v_city ->> 'currencyCode'), ''),
      NULLIF(btrim(v_city ->> 'primaryLanguage'), ''),
      (v_city ->> 'latitude')::DOUBLE PRECISION,
      (v_city ->> 'longitude')::DOUBLE PRECISION,
      NULLIF(btrim(v_city ->> 'timezone'), ''),
      v_source_id,
      v_city ->> 'sourceId'
    )
    ON CONFLICT (country_id, slug) DO NOTHING;

    UPDATE public.cities AS city
    SET
      country_id = v_country_id,
      name = btrim(v_city ->> 'name'),
      slug = v_slug,
      iata_code = COALESCE(NULLIF(btrim(v_city ->> 'iataCode'), ''), city.iata_code),
      currency_code = COALESCE(NULLIF(btrim(v_city ->> 'currencyCode'), ''), city.currency_code),
      primary_language = COALESCE(NULLIF(btrim(v_city ->> 'primaryLanguage'), ''), city.primary_language),
      latitude = COALESCE((v_city ->> 'latitude')::DOUBLE PRECISION, city.latitude),
      longitude = COALESCE((v_city ->> 'longitude')::DOUBLE PRECISION, city.longitude),
      timezone = COALESCE(NULLIF(btrim(v_city ->> 'timezone'), ''), city.timezone),
      updated_at = now()
    WHERE city.source_id = v_source_id
      AND city.source_record_id = v_city ->> 'sourceId';
  END LOOP;

  FOR v_airport IN
    SELECT value
    FROM jsonb_array_elements(p_records -> 'airports')
  LOOP
    SELECT country.id
    INTO v_country_id
    FROM public.countries AS country
    WHERE country.iso2 = v_airport ->> 'countryIso2'
    ORDER BY (country.source_id = v_source_id) DESC
    LIMIT 1;

    v_city_id := NULL;
    IF NULLIF(v_airport ->> 'citySourceId', '') IS NOT NULL THEN
      SELECT city.id
      INTO v_city_id
      FROM public.cities AS city
      WHERE city.source_id = v_source_id
        AND city.source_record_id = v_airport ->> 'citySourceId';

      IF v_city_id IS NULL THEN
        SELECT record.payload
        INTO v_city_record
        FROM admin.raw_base_data_records AS record
        WHERE record.batch_id = v_batch_id
          AND record.record_type = 'city'
          AND record.source_key = v_airport ->> 'citySourceId';

        IF v_city_record IS NOT NULL THEN
          v_slug := trim(
            BOTH '-'
            FROM regexp_replace(lower(v_city_record ->> 'name'), '[^a-z0-9]+', '-', 'g')
          );

          SELECT city.id
          INTO v_city_id
          FROM public.cities AS city
          JOIN public.countries AS country
            ON country.id = city.country_id
          WHERE country.iso2 = v_city_record ->> 'countryIso2'
            AND city.slug = v_slug
          LIMIT 1;
        END IF;
      END IF;
    END IF;

    v_slug := trim(
      BOTH '-'
      FROM regexp_replace(
        lower(
          COALESCE(
            NULLIF(v_airport ->> 'iata', ''),
            v_airport ->> 'name'
          )
        ),
        '[^a-z0-9]+',
        '-',
        'g'
      )
    );

    INSERT INTO public.airports (
      iata,
      icao,
      name,
      slug,
      image_path,
      city_id,
      country_id,
      latitude,
      longitude,
      timezone,
      airport_type,
      status,
      source_id,
      source_record_id
    )
    VALUES (
      NULLIF(v_airport ->> 'iata', ''),
      NULLIF(v_airport ->> 'icao', ''),
      btrim(v_airport ->> 'name'),
      v_slug,
      NULLIF(btrim(v_airport ->> 'imagePath'), ''),
      v_city_id,
      v_country_id,
      (v_airport ->> 'latitude')::DOUBLE PRECISION,
      (v_airport ->> 'longitude')::DOUBLE PRECISION,
      NULLIF(btrim(v_airport ->> 'timezone'), ''),
      v_airport ->> 'type',
      'active',
      v_source_id,
      v_airport ->> 'sourceId'
    )
    ON CONFLICT (source_id, source_record_id)
    DO UPDATE SET
      iata = EXCLUDED.iata,
      icao = EXCLUDED.icao,
      name = EXCLUDED.name,
      slug = EXCLUDED.slug,
      image_path = COALESCE(EXCLUDED.image_path, airports.image_path),
      city_id = EXCLUDED.city_id,
      country_id = EXCLUDED.country_id,
      latitude = EXCLUDED.latitude,
      longitude = EXCLUDED.longitude,
      timezone = COALESCE(EXCLUDED.timezone, airports.timezone),
      airport_type = EXCLUDED.airport_type,
      status = 'active',
      updated_at = now();
  END LOOP;

  IF p_source_code = 'ourairports' THEN
    UPDATE public.airports AS airport
    SET
      status = 'inactive',
      updated_at = now()
    WHERE airport.source_id = v_source_id
      AND airport.status = 'active'
      AND NOT EXISTS (
        SELECT 1
        FROM jsonb_array_elements(p_records -> 'airports') AS candidate
        WHERE candidate ->> 'sourceId' = airport.source_record_id
      );
  END IF;

  -- STEP 07: Complete the operational evidence after canonical publication.
  UPDATE admin.raw_import_batches
  SET
    status = 'published',
    updated_at = now()
  WHERE id = v_batch_id;

  -- STEP 08: Bound receipt retention independently from read-model publication.
  DELETE FROM admin.raw_import_batches AS batch
  WHERE batch.source_id = v_source_id
    AND batch.id <> v_batch_id
    AND batch.received_at < now() - interval '30 days';

  RETURN jsonb_build_object(
    'status', 'published',
    'batchId', v_batch_id,
    'acceptedCount', v_record_count,
    'rejectedCount', 0,
    'errorCode', NULL,
    'dataVersion', NULL
  );
EXCEPTION
  WHEN unique_violation OR check_violation OR foreign_key_violation THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'ERR_INGESTION_PUBLISH_FAILED';
END;
$$;

REVOKE ALL ON FUNCTION admin.publish_base_data_batch(
  TEXT,
  TEXT,
  TEXT,
  TEXT,
  TIMESTAMPTZ,
  JSONB,
  JSONB
) FROM public, anon, authenticated;

GRANT EXECUTE ON FUNCTION admin.publish_base_data_batch(
  TEXT,
  TEXT,
  TEXT,
  TEXT,
  TIMESTAMPTZ,
  JSONB,
  JSONB
) TO service_role;

-- >>> supabase/sql_src/functions/ingestion/rpc_publish_base_data_batch.sql

-- ============================================================================
-- Function: public.rpc_publish_base_data_batch
-- Purpose: Provide a service-role-only PostgREST transport to internal publication.
-- Responsibilities:
--   - Forward the bounded canonical batch to the internal transactional function.
--   - Keep the exposed wrapper security-invoker and unavailable to public clients.
-- Notes:
--   - Domain validation and mutation remain in admin.publish_base_data_batch.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.rpc_publish_base_data_batch(
  p_source_code       TEXT,
  p_idempotency_key   TEXT,
  p_checksum          TEXT,
  p_provider_version  TEXT,
  p_source_time       TIMESTAMPTZ,
  p_records           JSONB,
  p_import_metadata   JSONB DEFAULT NULL
)
RETURNS JSONB
LANGUAGE sql
SET search_path = ''
AS $$
  SELECT admin.publish_base_data_batch(
    p_source_code,
    p_idempotency_key,
    p_checksum,
    p_provider_version,
    p_source_time,
    p_records,
    p_import_metadata
  );
$$;

REVOKE ALL ON FUNCTION public.rpc_publish_base_data_batch(
  TEXT,
  TEXT,
  TEXT,
  TEXT,
  TIMESTAMPTZ,
  JSONB,
  JSONB
) FROM public, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.rpc_publish_base_data_batch(
  TEXT,
  TEXT,
  TEXT,
  TEXT,
  TIMESTAMPTZ,
  JSONB,
  JSONB
) TO service_role;

-- >>> supabase/sql_src/functions/ingestion/rpc_get_ourairports_denylist.sql

-- ============================================================================
-- Function: public.rpc_get_ourairports_denylist
-- Purpose: Return reviewed OurAirports exclusions to the privileged ingestion worker.
-- Responsibilities: Keep the admin table unavailable to public API roles.
-- Notes: This security-invoker wrapper is executable only by service_role.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.rpc_get_ourairports_denylist()
RETURNS TEXT[]
LANGUAGE sql
STABLE
SET search_path = ''
AS $$
  SELECT COALESCE(array_agg(entry.iata ORDER BY entry.iata), '{}'::TEXT[])
  FROM admin.ourairports_denylist AS entry;
$$;

REVOKE ALL ON FUNCTION public.rpc_get_ourairports_denylist()
FROM public, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.rpc_get_ourairports_denylist() TO service_role;

-- >>> supabase/sql_src/functions/ingestion/rpc_acquire_price_refresh_lease.sql

-- ============================================================================
-- Function: admin.rpc_acquire_price_refresh_lease
-- Purpose: Atomically acquire a price cache refresh lease or return fresh data.
-- Responsibilities: Prevent duplicate provider calls and manage refresh leases.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.rpc_acquire_price_refresh_lease(
  p_origin_iata TEXT,
  p_destination_iata TEXT DEFAULT NULL,
  p_currency_code TEXT DEFAULT 'USD',
  p_market_code TEXT DEFAULT 'us'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_origin_norm CHAR(3);
  v_dest_norm CHAR(3);
  v_curr_norm VARCHAR(3);
  v_market_norm VARCHAR(2);
  v_lease RECORD;
  v_fresh_count INTEGER;
  v_observations JSONB;
BEGIN
  v_origin_norm := upper(trim(p_origin_iata));
  v_dest_norm := CASE WHEN p_destination_iata IS NOT NULL AND length(trim(p_destination_iata)) > 0 THEN upper(trim(p_destination_iata)) ELSE NULL END;
  v_curr_norm := upper(trim(coalesce(p_currency_code, 'USD')));
  v_market_norm := lower(trim(coalesce(p_market_code, 'us')));

  IF v_origin_norm !~ '^[A-Z]{3}$' OR (v_dest_norm IS NOT NULL AND v_dest_norm !~ '^[A-Z]{3}$') THEN
    RETURN jsonb_build_object('status', 'failed', 'error', 'ERR_INVALID_IATA');
  END IF;

  -- 1. Check existing fresh published prices
  SELECT count(*), jsonb_agg(
    jsonb_build_object(
      'observation_ref', p.public_reference,
      'observed_amount', p.observed_amount,
      'currency_code', p.currency_code,
      'departure_date', p.departure_date,
      'direct', p.direct,
      'transfer_count', p.transfer_count,
      'duration_minutes', p.duration_minutes,
      'observed_at', p.observed_at,
      'valid_until', p.valid_until
    ) ORDER BY p.observed_amount ASC NULLS LAST
  )
  INTO v_fresh_count, v_observations
  FROM public.flight_route_prices AS p
  JOIN public.cities AS oc ON oc.id = p.origin_city_id
  JOIN public.airports AS oa ON oa.city_id = oc.id AND oa.iata = v_origin_norm
  LEFT JOIN public.cities AS dc ON dc.id = p.destination_city_id
  LEFT JOIN public.airports AS da ON da.city_id = dc.id AND da.iata = v_dest_norm
  WHERE p.status = 'published'
    AND p.valid_until > now()
    AND p.currency_code = v_curr_norm
    AND p.market_code = v_market_norm
    AND (v_dest_norm IS NULL OR da.id IS NOT NULL);

  IF v_fresh_count > 0 THEN
    RETURN jsonb_build_object(
      'status', 'fresh',
      'origin', v_origin_norm,
      'destination', v_dest_norm,
      'count', v_fresh_count,
      'observations', v_observations
    );
  END IF;

  -- 2. Check or upsert lease state
  INSERT INTO admin.route_price_cache_leases (
    origin_iata, destination_iata, market_code, currency_code, status, lease_expires_at, last_attempted_at, next_allowed_refresh_at
  ) VALUES (
    v_origin_norm, v_dest_norm, v_market_norm, v_curr_norm, 'refreshing', now() + interval '30 seconds', now(), now() + interval '30 seconds'
  )
  ON CONFLICT (origin_iata, destination_iata, market_code, currency_code)
  DO UPDATE SET
    last_attempted_at = now(),
    status = CASE
      WHEN route_price_cache_leases.lease_expires_at < now() THEN 'refreshing'
      ELSE route_price_cache_leases.status
    END,
    lease_expires_at = CASE
      WHEN route_price_cache_leases.lease_expires_at < now() THEN now() + interval '30 seconds'
      ELSE route_price_cache_leases.lease_expires_at
    END
  RETURNING * INTO v_lease;

  IF v_lease.status = 'refreshing' AND v_lease.lease_expires_at >= now() THEN
    RETURN jsonb_build_object(
      'status', 'lease_acquired',
      'origin', v_origin_norm,
      'destination', v_dest_norm,
      'lease_id', v_lease.id
    );
  ELSIF v_lease.next_allowed_refresh_at > now() AND v_lease.status IN ('empty', 'failed') THEN
    RETURN jsonb_build_object(
      'status', 'cooldown',
      'origin', v_origin_norm,
      'destination', v_dest_norm,
      'next_allowed_refresh_at', v_lease.next_allowed_refresh_at
    );
  ELSE
    RETURN jsonb_build_object(
      'status', 'refreshing',
      'origin', v_origin_norm,
      'destination', v_dest_norm
    );
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION admin.rpc_acquire_price_refresh_lease(TEXT, TEXT, TEXT, TEXT)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.rpc_acquire_price_refresh_lease(TEXT, TEXT, TEXT, TEXT) TO service_role;

-- >>> supabase/sql_src/functions/ingestion/rpc_publish_price_observations.sql

-- ============================================================================
-- Function: admin.rpc_publish_price_observations
-- Purpose: Atomically publish normalized price observations from provider adapter.
-- Responsibilities: Insert prices with 7-day TTL and update cache lease status.
-- ============================================================================

CREATE OR REPLACE FUNCTION admin.rpc_publish_price_observations(
  p_origin_iata TEXT,
  p_destination_iata TEXT,
  p_currency_code TEXT,
  p_market_code TEXT,
  p_observations JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_origin_norm CHAR(3);
  v_dest_norm CHAR(3);
  v_curr_norm VARCHAR(3);
  v_market_norm VARCHAR(2);
  v_source_id UUID;
  v_obs_count INTEGER := 0;
  v_inserted_count INTEGER := 0;
  v_item RECORD;
  v_origin_city_id UUID;
  v_dest_city_id UUID;
  v_origin_airport_id UUID;
  v_dest_airport_id UUID;
  v_airline_id UUID;
BEGIN
  v_origin_norm := upper(trim(p_origin_iata));
  v_dest_norm := CASE WHEN p_destination_iata IS NOT NULL AND length(trim(p_destination_iata)) > 0 THEN upper(trim(p_destination_iata)) ELSE NULL END;
  v_curr_norm := upper(trim(coalesce(p_currency_code, 'USD')));
  v_market_norm := lower(trim(coalesce(p_market_code, 'us')));

  SELECT id INTO v_source_id
  FROM admin.data_sources
  WHERE provider_code = 'travelpayouts'
  LIMIT 1;

  IF v_source_id IS NULL THEN
    INSERT INTO admin.data_sources (provider_code, name, source_type, is_active)
    VALUES ('travelpayouts', 'Travelpayouts Data API', 'api', true)
    RETURNING id INTO v_source_id;
  END IF;

  -- Count items in payload
  IF p_observations IS NOT NULL AND jsonb_typeof(p_observations) = 'array' THEN
    v_obs_count := jsonb_array_length(p_observations);
  END IF;

  IF v_obs_count = 0 THEN
    -- Update lease to empty with 6-hour cooldown
    UPDATE admin.route_price_cache_leases
    SET status = 'empty',
        last_attempted_at = now(),
        next_allowed_refresh_at = now() + interval '6 hours',
        lease_expires_at = NULL,
        updated_at = now()
    WHERE origin_iata = v_origin_norm
      AND destination_iata IS NOT DISTINCT FROM v_dest_norm
      AND market_code = v_market_norm
      AND currency_code = v_curr_norm;

    RETURN jsonb_build_object('published_count', 0, 'status', 'empty');
  END IF;

  -- Iterate and insert observations
  FOR v_item IN
    SELECT
      upper(trim((elem->>'originIata')::TEXT)) AS origin_iata,
      upper(trim((elem->>'destinationIata')::TEXT)) AS destination_iata,
      upper(trim(coalesce(elem->>'providerAirlineIata', '')))::TEXT AS provider_airline,
      (elem->>'observedAmount')::NUMERIC(14,2) AS observed_amount,
      upper(trim(coalesce(elem->>'currencyCode', v_curr_norm)))::TEXT AS currency,
      coalesce((elem->>'direct')::BOOLEAN, true) AS direct,
      (elem->>'transferCount')::INTEGER AS transfer_count,
      (elem->>'durationMinutes')::INTEGER AS duration_minutes,
      (elem->>'departureDate')::DATE AS departure_date,
      (elem->>'returnDate')::DATE AS return_date,
      coalesce((elem->>'observedAt')::TIMESTAMPTZ, now()) AS observed_at,
      least(
        coalesce((elem->>'validUntil')::TIMESTAMPTZ, now() + interval '7 days'),
        now() + interval '7 days'
      ) AS valid_until,
      coalesce(elem->>'affiliatePath', '/search/' || (elem->>'originIata') || (elem->>'destinationIata')) AS affiliate_path
    FROM jsonb_array_elements(p_observations) AS elem
  LOOP
    -- Lookup origin airport & city
    SELECT a.id, a.city_id INTO v_origin_airport_id, v_origin_city_id
    FROM public.airports AS a
    WHERE a.iata = v_item.origin_iata
    LIMIT 1;

    -- Lookup destination airport & city
    SELECT a.id, a.city_id INTO v_dest_airport_id, v_dest_city_id
    FROM public.airports AS a
    WHERE a.iata = v_item.destination_iata
    LIMIT 1;

    -- Skip if origin or destination airport not in base database or origin == dest
    IF v_origin_city_id IS NULL OR v_dest_city_id IS NULL OR v_origin_city_id = v_dest_city_id THEN
      CONTINUE;
    END IF;

    -- Lookup airline if present
    v_airline_id := NULL;
    IF v_item.provider_airline IS NOT NULL AND length(v_item.provider_airline) >= 2 THEN
      SELECT id INTO v_airline_id
      FROM public.airlines
      WHERE iata = v_item.provider_airline
      LIMIT 1;
    END IF;

    -- Insert or update price observation
    INSERT INTO public.flight_route_prices (
      origin_city_id, destination_city_id, origin_airport_id, destination_airport_id,
      canonical_airline_id, provider_airline_iata, observation_type, trip_type,
      direct, transfer_count, observed_amount, currency_code, market_code, locale,
      departure_date, return_date, duration_minutes, source_id, provider_code,
      source_record_id, observed_at, valid_until, affiliate_path, status
    ) VALUES (
      v_origin_city_id, v_dest_city_id, v_origin_airport_id, v_dest_airport_id,
      v_airline_id, NULLIF(v_item.provider_airline, ''), 'cached_fare', 'one_way',
      v_item.direct, coalesce(v_item.transfer_count, CASE WHEN v_item.direct THEN 0 ELSE 1 END),
      v_item.observed_amount, v_item.currency, v_market_norm, 'en-GB',
      v_item.departure_date, v_item.return_date, v_item.duration_minutes, v_source_id, 'travelpayouts',
      'tp_' || v_item.origin_iata || '_' || v_item.destination_iata || '_' || to_char(coalesce(v_item.departure_date, CURRENT_DATE), 'YYYYMMDD') || '_' || v_item.currency,
      v_item.observed_at, v_item.valid_until, v_item.affiliate_path, 'published'
    )
    ON CONFLICT (source_id, source_record_id)
    DO UPDATE SET
      observed_amount = EXCLUDED.observed_amount,
      currency_code = EXCLUDED.currency_code,
      observed_at = EXCLUDED.observed_at,
      valid_until = EXCLUDED.valid_until,
      affiliate_path = EXCLUDED.affiliate_path,
      status = 'published';

    v_inserted_count := v_inserted_count + 1;
  END LOOP;

  -- Update lease status to fresh
  UPDATE admin.route_price_cache_leases
  SET status = 'fresh',
      last_succeeded_at = now(),
      next_allowed_refresh_at = now() + interval '24 hours',
      lease_expires_at = NULL,
      updated_at = now()
  WHERE origin_iata = v_origin_norm
    AND destination_iata IS NOT DISTINCT FROM v_dest_norm
    AND market_code = v_market_norm
    AND currency_code = v_curr_norm;

  RETURN jsonb_build_object(
    'published_count', v_inserted_count,
    'status', 'fresh'
  );
END;
$$;

REVOKE ALL ON FUNCTION admin.rpc_publish_price_observations(TEXT, TEXT, TEXT, TEXT, JSONB)
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.rpc_publish_price_observations(TEXT, TEXT, TEXT, TEXT, JSONB) TO service_role;

-- >>> supabase/sql_src/operations/configure_ingestion_crons.sql

-- ============================================================================
-- Function: admin.configure_ingestion_crons
-- Purpose: Install and configure ingestion & cache schedules.
-- Responsibilities: Validate Vault and manage all ingestion jobs idempotently.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

CREATE OR REPLACE FUNCTION admin.configure_ingestion_crons()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_project_url           TEXT;
  v_worker_secret         TEXT;
  v_ourairports_job       BIGINT;
  v_aerodatabox_job       BIGINT;
  v_tp_warm_job           BIGINT;
  v_tp_day6_job           BIGINT;
BEGIN
  SELECT secret.decrypted_secret
  INTO v_project_url
  FROM vault.decrypted_secrets AS secret
  WHERE secret.name = 'project_url';

  SELECT secret.decrypted_secret
  INTO v_worker_secret
  FROM vault.decrypted_secrets AS secret
  WHERE secret.name = 'ingestion_worker_secret';

  IF v_project_url IS NULL
    OR v_project_url !~ '^https://'
    OR v_worker_secret IS NULL
    OR char_length(v_worker_secret) < 16
  THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'ERR_CRON_VAULT_PREREQUISITES_MISSING';
  END IF;

  -- Unschedule existing jobs
  PERFORM cron.unschedule(job.jobid)
  FROM cron.job AS job
  WHERE job.jobname IN (
    'tripways-ourairports-daily',
    'tripways-aerodatabox-monthly',
    'tripways-travelpayouts-top-warm',
    'tripways-travelpayouts-day6-smart-refresh'
  );

  -- 1. OurAirports Daily (Tầng 1 - 02:00 UTC)
  SELECT cron.schedule(
    'tripways-ourairports-daily',
    '0 2 * * *',
    $cron$SELECT net.http_post(
        url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'project_url') || '/functions/v1/ingestion-base-data',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'ingestion_worker_secret'),
          'Idempotency-Key', 'ourairports-' || to_char(CURRENT_DATE, 'YYYY-MM-DD')
        ),
        body := jsonb_build_object('sourceCode', 'ourairports', 'providerMode', 'ourairports')
      );$cron$
  )
  INTO v_ourairports_job;

  -- 2. AeroDataBox Monthly Direct Routes Batch (Tầng 2 - Ngày 1 lúc 03:00 UTC)
  SELECT cron.schedule(
    'tripways-aerodatabox-monthly',
    '0 3 1 * *',
    $cron$SELECT net.http_post(
        url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'project_url') || '/functions/v1/ingestion/routes',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'ingestion_worker_secret'),
          'Idempotency-Key', 'aerodatabox-' || to_char(CURRENT_DATE, 'YYYY-MM')
        ),
        body := jsonb_build_object('providerMode', 'aerodatabox', 'scope', 'top_airports')
      );$cron$
  )
  INTO v_aerodatabox_job;

  -- 3. Travelpayouts Warm Top 200 Routes (Tầng 3 - 04:00 UTC mỗi 3 ngày)
  SELECT cron.schedule(
    'tripways-travelpayouts-top-warm',
    '0 4 */3 * *',
    $cron$SELECT net.http_post(
        url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'project_url') || '/functions/v1/flight/route-cache',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'ingestion_worker_secret')
        ),
        body := jsonb_build_object('mode', 'warm_top_routes')
      );$cron$
  )
  INTO v_tp_warm_job;

  -- 4. Travelpayouts Day 6 Active Demand Smart Refresh (Tầng 3 - 05:00 UTC hàng ngày)
  SELECT cron.schedule(
    'tripways-travelpayouts-day6-smart-refresh',
    '0 5 * * *',
    $cron$SELECT net.http_post(
        url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'project_url') || '/functions/v1/flight/route-cache',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'ingestion_worker_secret')
        ),
        body := jsonb_build_object('mode', 'day6_active_refresh')
      );$cron$
  )
  INTO v_tp_day6_job;

  RETURN jsonb_build_object(
    'ourairports_job_id', v_ourairports_job,
    'aerodatabox_job_id', v_aerodatabox_job,
    'tp_warm_job_id', v_tp_warm_job,
    'tp_day6_job_id', v_tp_day6_job
  );
END;
$$;

REVOKE ALL ON FUNCTION admin.configure_ingestion_crons()
FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION admin.configure_ingestion_crons() TO service_role;
