-- ============================================================================
-- Migration: 20260714080000_platform.sql
-- Source of truth: supabase/sql_src
-- Feature: platform
-- NOTE: AUTO-GENERATED by scripts/regenerate-supabase-migrations.sh
-- ============================================================================

-- >>> supabase/sql_src/schema/_platform/private.sql

-- Schema: private
-- Purpose: Raw provider data and internal staging records that must never be exposed by Data API.

CREATE SCHEMA IF NOT EXISTS private;

REVOKE ALL ON SCHEMA private FROM anon, authenticated;
GRANT USAGE ON SCHEMA private TO service_role;

-- >>> supabase/sql_src/schema/_platform/admin.sql

-- Schema: admin
-- Purpose: Operational state for ingestion, publishing, and maintenance workflows.

CREATE SCHEMA IF NOT EXISTS admin;

REVOKE ALL ON SCHEMA admin FROM anon, authenticated;

-- >>> supabase/sql_src/schema/_platform/analytics.sql

-- Schema: analytics
-- Purpose: Internal product and operational events written through controlled backend boundaries.

CREATE SCHEMA IF NOT EXISTS analytics;

REVOKE ALL ON SCHEMA analytics FROM anon, authenticated;
